### ISSUE TITLE
4 weekly schedule

### ISSUE THREAD

**Issue by NielsFeenstra** [bruxy70/Garbage-Collection#1]
Is it possible to create a 4 weekly schedule?

In the Netherlands they pick up the paper every 4 weeks.

**Comment by bruxy70** [comment]
Sure, I can do that. What if I make it generic - collection every x weeks with the first collection on week y?
But I guess you might need to re-configure that every year if the year has 53 weeks, I suppose they will do it 4th week from the last collection at the end of the year... Or how do they define that? Is there a formula?

**Comment by NielsFeenstra** [comment]
Thanks,

No there is no formula. It can change every year so I have to re-configure it every year, no problem. This year it starts on 01/24/2019 and then every 4 weeks.

**Comment by bruxy70** [comment]
This is a new feature introduced in the release 1.5. 
Closing the issue.
