### ISSUE TITLE
(Request) Support for different icons

### ISSUE THREAD

**Issue by amaximus** [bruxy70/Garbage-Collection#10]
Thanks for your work on Garbage Collection custom component, it's really useful.

I'd request a new feature, namely support for being able to specify different icons for the different sensors.

Thanks.

**Comment by bruxy70** [comment]
Ok. Will do. There are 3 icons: Normal, collection tomorrow and collection today. I will make them configurable.

**Comment by amaximus** [comment]
Thanks. I really appreciate it.

**Comment by bruxy70** [comment]
Thanks for the Lovelace card BTW :)

**Comment by amaximus** [comment]
You're welcome. It was fun creating it.

**Comment by bruxy70** [comment]
Done. You might also want to check the verbose_state parameter in the readme ;)

**Comment by 1DontEx1st** [comment]
Wow, to both of you. I was working up something similar for myself (although directly in my ui YAML)...I really need to get into the mindset that maybe my ideas/problems/etc aren't unique to me... thanks :)

**Comment by amaximus** [comment]
Thanks, it works great.

**Comment by stackner** [comment]
how do i change the icons instead of it saying 0, 1 or 2?

**Comment by bruxy70** [comment]
Configuration parameters:
verbose_state: True
