### ISSUE TITLE
Feature Request: Odd/Even Months

### ISSUE THREAD

**Issue by shbatm** [bruxy70/Garbage-Collection#104]
**Is your feature request related to a problem? Please describe.**
My city alternates tree/yard waste and large junk waste on alternating months.

**Describe the solution you'd like**
Support for `odd` and `even` months.

**Describe alternatives you've considered**
Right now they just use a monthly shared sensor. But it'd be nice to split them up.

**Additional context**
Should be the same options as "monthly" just with an extra option to set "odd" or "even" only.

**Comment by bruxy70** [comment]
Ok guys. I have been thinking about this one for a while. I did not want to add yet another type of frequency. And I wanted to make it more generic. So this is what I am doing.
I will allow configuring `period` for the monthly frequency as well. And in combination with `first_month`, you will be able to configure it for even or odd month (or even every 3rd month  if you want to do a quarterly thing).
So if you said `period : 2` and `first_month: 'jan'`, it will be every odd month (jan, mar, may, ...). And with `period : 2` and `first_month: 'feb'` it would be even (feb, apr, ...). And with `period : 3` and `first_month: 'jan'` it would be quarterly (jan, apr, jul, oct) etc.
I have it on the development branch and I am testing it. The last thing I need to do is to allow configuration of `period` for `monthly` frequency on the web configuration (it works with yaml config only right now). 
WDYT?

**Comment by shbatm** [comment]
Works for me! I agree, keeping things as generic as possible but allowing flexibility for each config sounds like the way to go. I will test when I get a chance.

**Comment by bruxy70** [comment]
Ok, it seems to work, and I added the web configuration (it is on the 3ds screen). And documentation.
I made a beta release 2.18-beta3,
Please test it and let me know. 
The release is fixing another issue with groups, so if all works, I will be making this release in 2 weeks or so.

**Comment by shbatm** [comment]
Looks like it's working fine in YAML mode.

**Comment by chillkiller** [comment]
seems to work also in configuratio-mode... Realy Thank you for that, now my paper and cardboard waste works without exclusing dates ;)
