### ISSUE TITLE
Feature Request: Different attribute for name and friendly_name

### ISSUE THREAD

**Issue by olijouve** [bruxy70/Garbage-Collection#105]
**Is your feature request related to a problem? Please describe.**
In order to keep sensors organized / filterable, naming logics could be use to prefix sensor name " (ie: with "trash_" => sensor.trash_glass, sensor.trash_waste...)

Problem is that the same name is used for both entity_id(with underscore in place of space) and for display.

**Describe the solution you'd like**
It would be great to be able to have a friendly_name attribute for customize displayed name whatever the entity_id we choose.

**Comment by bruxy70** [comment]
The name is actually the friendly_name, so you can put there whatever you want to display.
The entity_id is created automatically. If you make the configuration in YAML, you cannot change teh entity_id. But if you configure the integration on the web, then you can change the display name and entity_id as usual.
![image](https://user-images.githubusercontent.com/44951610/76209598-82ac2d80-6202-11ea-9a48-d495624ebb7f.png)

**Comment by olijouve** [comment]
Thanks for your answer.
I've finished to migrate from yaml to UI config. Everthing is fine now.
