### ISSUE TITLE
Missing verbose_format: ".... {date} ......" in UI mode

### ISSUE THREAD

**Issue by olijouve** [bruxy70/Garbage-Collection#106]
**Describe the bug**
Argument verbose_format is missing in UI configuration mode, resulting in a display regression compared to the yaml mode.

I was using the conf below to produce a simple date (ie : 13 Mar )
  verbose_state: True
  verbose_format: "{date}"
  date_format: %d %b

UI mode doesn't allow verbose_format option and the output is on 13 Mar, in 4 days 

**Version**
Last version for everythings

**Comment by bruxy70** [comment]
The UI does support verbose format configuration 
![Screenshot_20200309_152238](https://user-images.githubusercontent.com/44951610/76222239-9d8a9c00-621a-11ea-8ea2-06e0317b6421.jpg)

**Comment by olijouve** [comment]
Ok thanks, might be a cache issue as i don’t have the verbose format field on my UI

**Comment by bruxy70** [comment]
Weird. It is on the first step, where you configure the frequency. And it is not a recent feature.

**Comment by olijouve** [comment]
I found why, my fault in fact because i've put literal curly bracket in this label when i had done the french translation

**Comment by olijouve** [comment]
Thanks for your screenshot !
