### ISSUE TITLE
More noticable graphics 

### ISSUE THREAD

**Issue by Alloc186** [bruxy70/Garbage-Collection#108]
Hello, thanks for your great card. 

I would like to have a little enhancement a day before waste collection change icon lets say to orange colour from green and in the day icon should be red and blinking. Is that possible?

Thank you.

**Comment by bruxy70** [comment]
This repo is for the integration (sensor), not the card. It does not control how you display it.
The Readme contains some examples of Lovelace config. Personally, I change the color between Gray/Amber/Green using standard Picture entity: https://github.com/bruxy70/Garbage-Collection#with-images-picture-entity
Suppose you can do some more crazy stuff with card-mod: https://github.com/thomasloven/lovelace-card-mod

If you want to suggest the feature to the garbage collection card, you can post it here: 
https://github.com/amaximus/garbage-collection-card
