### ISSUE TITLE
Lovelace Config With images ( picture entity )

### ISSUE THREAD

**Issue by SuperNeo84** [bruxy70/Garbage-Collection#109]
**Describe the bug**
i tried to copy the example of the home page of this integration. But the image don't show

**Configuration**
YAML or Config Flow (GUI):

` entity: sensor.secco
          name_template: '{{ states.sensor.secco.attributes.days }} days'
          show_name: true
          show_state: false
          state_image:
            '0': /local/images/cartone_red.jpg
            '1': /local/cartone_orange.jpg
            '2': /local/cartone.jpg
          type: picture-entity
        entities:
          - sensor.secco
        type: 'custom:card-templater'`
Copy the sensor configuration here (for config flow, describe parameters or add screenshots)
``

**Error log/debug information**

**Screenshots**
![image](https://user-images.githubusercontent.com/56050309/76340791-71dfe280-62fc-11ea-8f68-ac5acaa219a3.png)

**Version**
![image](https://user-images.githubusercontent.com/56050309/76340870-8ae89380-62fc-11ea-88ec-a4516bcc5534.png)

![image](https://user-images.githubusercontent.com/56050309/76340915-9b990980-62fc-11ea-908a-ddf1b2ed4ea0.png)

![image](https://user-images.githubusercontent.com/56050309/76340946-a8b5f880-62fc-11ea-8da8-b99c357d4d87.png)

**Comment by bruxy70** [comment]
What is the configuration of the sensor, what is the current state? 
I suppose the images exist and you have the custom card-templater plugin installed.

**Comment by bruxy70** [comment]
What is the configuration of the sensor, what is the current state? 
I suppose the images exist.

**Comment by SuperNeo84** [comment]
this is the configuration of sensor, and his current state is: "To Day"

![image](https://user-images.githubusercontent.com/56050309/76497379-2bdd6880-643b-11ea-9f62-5aa710601e7d.png)
![image](https://user-images.githubusercontent.com/56050309/76497421-3d267500-643b-11ea-897e-6a845e2a6b73.png)
![image](https://user-images.githubusercontent.com/56050309/76497445-47487380-643b-11ea-917e-9e5de5d5ff7c.png)

and yes the images exist!

**Comment by bruxy70** [comment]
Ok, that cannot work. You cannot turn on "verbose output" and then have a picture entity card set for values 0,1 and 2.
What you have is, you configured the sensor to have a text state (like `Today`, `Tomorrow`, `il 15 Mar 2010, entro 3 giorni`, and then in Lovelace, you said if the state is `0`, show the image `/local/images/cartone_red.jpg`. It worn't work. The state will never be 0,1 or 2. You disabled it.

**Comment by SuperNeo84** [comment]
It works! Great it was so simple 🗡 

![image](https://user-images.githubusercontent.com/56050309/76504009-20903a00-6447-11ea-8963-00a9483f74aa.png)

Sorry, but i have another question, i tried to use my perzonalized image (.jpg) directly in the sensor configuration

![image](https://user-images.githubusercontent.com/56050309/76504195-841a6780-6447-11ea-9bd2-6f2023d784ff.png)

but when in Lovelace UI i use "Garbage-Collector-Card" the icon don't show. 
am I wrong?

![image](https://user-images.githubusercontent.com/56050309/76504248-a2806300-6447-11ea-8d21-02870823c2c3.png)

![image](https://user-images.githubusercontent.com/56050309/76504318-c8a60300-6447-11ea-9ddb-30b7a59b076b.png)

**Comment by bruxy70** [comment]
Home Assistant does not allow for JPG images to be used as sensor icons. It only works with Material Design Icons: https://materialdesignicons.com/
And they do not support colors, there is nothing I can do about that, sorry.

**Comment by SuperNeo84** [comment]
ok thanks
