### ISSUE TITLE
lovelace config for HA 0.107

### ISSUE THREAD

**Issue by pilot1981** [bruxy70/Garbage-Collection#116]
**Is your feature request related to a problem? Please describe.**
with HA 0.107 version I'm unable to add your lovelace example:

      - type: 'custom:card-templater'
        card:
          type: picture-entity
          name_template: >-
            {{ states.sensor.bio.attributes.days }} days
          show_name: True
          show_state: False
          entity: sensor.bio
          state_image:
            "0": "/local/containers/bio_today.png"
            "1": "/local/containers/bio_tomorrow.png"
            "2": "/local/containers/bio_off.png"
        entities:
          - sensor.bio

**Describe the solution you'd like**
Can you give updated syntax for lovelace config and images for this config?

**Describe alternatives you've considered**
redo config

**Additional context**
NA

**Comment by bruxy70** [comment]
I have  0.107.5 and it works for me.
![image](https://user-images.githubusercontent.com/44951610/77316584-f6bdf980-6d09-11ea-95b7-bb1afd0d0c9c.png)

**Comment by pilot1981** [comment]
with this config:

card:
  entity: sensor.raccolta_organico_mattino
  name_template: '{{ states.sensor.bio.attributes.days }} days'
  show_name: True
  show_state: False
  state_image:
    "0": "/local/containers/bio_today.png"
    "1": "/local/containers/bio_tomorrow.png"
    "2": "/local/containers/bio_off.png"
  type: picture-entity
entities:
  - sensor.bio
type: 'custom:card-templater'

I have this error:

Error: Custom element not found: card-templater

**Comment by bruxy70** [comment]
Ok, and do you have the card-templater plugin installed?

**Comment by pilot1981** [comment]
<img width="984" alt="Schermata 2020-03-23 alle 15 04 27" src="https://user-images.githubusercontent.com/46350465/77324846-a8aff280-6d17-11ea-87d3-f7a24799769e.png">

yes, sure

**Comment by pilot1981** [comment]
I have to modify something?

**Comment by bruxy70** [comment]
Home Assistant complains that it does have card templater installed.
You say that you have it, but then you send a screenshot of Multiple Entity Row, which is a different plugin. So I'd say the issue is, that you do not have the card templater installed or included in your resources. But if you say you do, I do not know what the issue is.
![image](https://user-images.githubusercontent.com/44951610/77325444-997d7480-6d18-11ea-994a-67fa50a1db80.png)

**Comment by pilot1981** [comment]
You are right, Now I installed also Lovelace card templater, but now I have this error:

No visual editor available for: custom:card-templater

**Comment by bruxy70** [comment]
This is not an error. It is just a message from Home Assistant that the card templater does not have visual editor, because it is a custom card. So that you have to configure it in text editor. Which you did.
The important thing is, does it show the card now?

**Comment by pilot1981** [comment]
it look empty:

<img width="348" alt="Schermata 2020-03-23 alle 15 34 48" src="https://user-images.githubusercontent.com/46350465/77327697-e282f800-6d1b-11ea-9164-cc105bb5e096.png">

**Comment by pilot1981** [comment]
I arranged better my lovelace code:

card:
  entity: sensor.raccolta_organico_mattino
  name_template: '{{ states.sensor.raccolta_organico_mattino.attributes.days }} days'
  show_name: True
  show_state: False
  state_image:
    "0": "/local/containers/bio_today.png"
    "1": "/local/containers/bio_tomorrow.png"
    "2": "/local/containers/bio_off.png"
  type: picture-entity
entities:
  - sensor.raccolta_organico_mattino
type: 'custom:card-templater'

but it seem not found image:

<img width="351" alt="Schermata 2020-03-23 alle 15 40 15" src="https://user-images.githubusercontent.com/46350465/77328286-9dab9100-6d1c-11ea-93e8-a9da58de2172.png">


where I can find these image?

- /local/containers/bio_today.png
- /local/containers/bio_tomorrow.png
- /local/containers/bio_off.png

**Comment by bruxy70** [comment]
These are your images. You can put there any image you like. Draw it. Get it on Google. Up to you. That's the point of picture-entity card.
If this is too much effort for you, use the standard glance view.

**Comment by pilot1981** [comment]
ok, thanks very much

**Comment by pilot1981** [comment]
@bruxy70 last question: you know where is the location on HASSIO 0.107 lovelace storage?

/local/containers/bio_today.png

**Comment by bruxy70** [comment]
config/www/containers

**Comment by pilot1981** [comment]
thanks again for your help!
