### ISSUE TITLE
Unknown Error Occurred

### ISSUE THREAD

**Issue by Coedy** [bruxy70/Garbage-Collection#118]
**Describe the bug**
'Unknown Error Occured' when trying to change icons after initial set up using the UI.
go into the Integration list, Click one of your Garbage Devices (to see entity list view) that you set up previously, Click the cog in the rop right corner and try and change any of the information (I'm only trying to change all Icons).
(Not sure if this was present previously as I've only been using this for 4 days)

**Configuration**
UI - Initial set up is fine, only shows when trying to change 'icon', 'icon collection tomorrow' or 'icon collection today'. See screenshot section below.
(Also - "icon collection tomorrow" has a typo, collection is missing it's 'n')

**Error log/debug information**
Not sure where the issues start, presumably only the last two lines.
```
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 227, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/garbage_collection/config_flow.py", line 504, in async_step_init
    self._data.update(user_input)
AttributeError: 'mappingproxy' object has no attribute 'update'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26841217/78148132-629c1280-742c-11ea-8c77-8fd77bb1071e.png)

**Version**
Integration: 2.18
Home Assistant Version: 0.107.7  
Supervisor: 214
Configuration: Home Assistant (full fat), in Docker on Debian

**Comment by bruxy70** [comment]
Thanks, looks like it stopped working in recent Home Assistant update. Will figure out what has changed :(. Thanks!

**Comment by Coedy** [comment]
No probs!
If you need anything else for this just let me know.
