### ISSUE TITLE
Add option for start and end on week numbers

### ISSUE THREAD

**Issue by fillwe** [bruxy70/Garbage-Collection#120]
Hello! Thanks for an awesome integration!

I have a very special garbage collection schedule. Our normal one is every even week on mondays. That i had no trouble setting up. But during the summer, between week 25 to 34 we have garbage collection every week. 

I tried setting that up as a seperate sensor, i might be missing something but i can't set a sensor to start a certain week and end on another week number right? Can just find setting for start a certain week and end on a month.

I know this request is very niche, but would really appreciate som help!:-)

**Comment by bruxy70** [comment]
You can have a sensor to start and stop on a specific month, not on a specific week number.
You can do that and then use include/exclude dates to fix the difference, but I understand this is annoying, as you'd have to adjust it every year.
Said that, if I did have a configuration on a week number, you'd have to adjust it every year as well, as summer starts on different week number each year (I think it is June 21 or 20 on a leap year, and that comes to a different week number depending on what day the year starts).
The config currently allows for so many different options and it is quite bloated, so I am always looking for other ways to achieve the same result.

**Comment by fillwe** [comment]
I understand that, can't meet everyones needs! I think i solved this with a seperate week number sensor and using that in conjuction with the integration. Thanks for the reply, and the amazing work!
