### ISSUE TITLE
3 red stripes after opening the app/browser

### ISSUE THREAD

**Issue by damiantje99** [bruxy70/Garbage-Collection#127]
**Describe the bug**
When I open my browser or app for the first time (every time), it shows the cards I've setup with the Garbage-Collection as 3 red stripes.

After when i'm opening the menu and switch between boards or when I open and close the configure-UI, the pictures will appear.

I'm using the custom card-templater
**Configuration**
YAML or Config Flow (GUI):

```
This is my configuration: https://pastebin.com/XCV5tQjn
```

**Error log/debug information**
```
I can't find any logging
```
To enable debug logging, add `custom_components.garbage_collection: debug` to your config under logger/logs.

**Screenshots**
Here u can see the screenshots: https://imgur.com/a/4EJ9Nos

**Version**
I'm running Home Assistant 0.108.3

**Comment by bruxy70** [comment]
Is this a bug in the garbage collection integration? Can you try simple entity card? Will that be red as well?
Or is this an issue with Lovelace config? In that case, it is hard to troubleshoot from here. What I'd do is, I'd start simple - take 1 card, no card-templater. See if that works. And then start adding the complexity back, until you figure out what is causing it.
