### ISSUE TITLE
 line-break is not working

### ISSUE THREAD

**Issue by Kozze** [bruxy70/Garbage-Collection#130]
Hi,

I am trying to use your code to insert a "line break" but this is not working.
------------------------------------------------------------------
entities:
  - entity: sensor.restafval
  - entity: sensor.pmd
  - entity: sensor.gft
  - entity: sensor.glas_papier_en_karton
style:
  .entity:
    $: |
      :host {}
      div:nth-of-type(2) {
        white-space: inherit !important
      }
type: glance
------------------------------------------------------------------

This error is showing up: 

Expected a value of type `undefined` for `style` but received `{".entity":{"$":":host {}\ndiv:nth-of-type(2) {\n white-space: inherit !important\n}\n"}}`.

![garbage](https://user-images.githubusercontent.com/34898705/80892650-0860cc80-8ccc-11ea-9f26-69f4caef15ea.png)

**Comment by bruxy70** [comment]
Thanks for bringing this up. I will remove it from the examples then.
If you figure out how to make line breaks in the glance values, please let me know, I'd put it back in.
