### ISSUE TITLE
Problem with translation

### ISSUE THREAD

**Issue by svaneepoel** [bruxy70/Garbage-Collection#136]
**Describe the bug**
[](https://i.imgur.com/sKIZPvt.png)
As you can see in the screenshot, I use Dutch as interface language but 'Morgen' is displayed as 'Tomorrow'. My HA and Chrome are both configured to use Dutch as language.

Am I doing something wrong?

**Configuration**
YAML or Config Flow (GUI): /

```
Copy the sensor configuration here (for config flow, describe parameters or add screenshots)
```

**Error log/debug information**
```
Copy the error message from Developer tools/Logs here. 
```
To enable debug logging, add `custom_components.garbage_collection: debug` to your config under logger/logs.

**Screenshots**

**Version**
Integration version, Home Assistant version and configuration

**Comment by bruxy70** [comment]
Thanks for bringing this up, I did not notice. Looks like the 0.109 changed the translations more.
Hopefully, this will work.

**Comment by svaneepoel** [comment]
> Thanks for bringing this up, I did not notice. Looks like the 0.109 changed the translations more.
> Hopefully, this will work.

Hi! Thank you for the fast support (and great plugin!).

Just want to let you know that I just updated to the new version, but I still have the same 'problem'.

**Comment by bruxy70** [comment]
Then the problem is somewhere else. It works here:
![image](https://user-images.githubusercontent.com/44951610/81195870-aa2f3480-8fbe-11ea-8540-c0de355d0395.png)
Did you restart HA?
Can you check in the Ontwikkelhulpmiddelen (wow, can you actually pronounce it?) and click on the (i) to see if it translates? (the actual sensor state is always in lowercase English, otherwise, you'd have to make a different version of automation for each language/user)

**Comment by svaneepoel** [comment]
> Then the problem is somewhere else. It works here:
> ![image](https://user-images.githubusercontent.com/44951610/81195870-aa2f3480-8fbe-11ea-8540-c0de355d0395.png)
> Did you restart HA?
> Can you check in the Ontwikkelhulpmiddelen (wow, can you actually pronounce it?) and click on the (i) to see if it translates? (the actual sensor state is always in lowercase English, otherwise, you'd have to make a different version of automation for each language/user)

Haha because I'm from Belgium, I can pronounce it! ;-)
Created the ticket in English because maybe it could help others with solving this problem.

But the problem has been solved, thank you! I did another restart and now it shows it perfectly!
_Ik zie nu dat ik dadelijk het vuilnis buiten kan gaan zetten! :-)_
