### ISSUE TITLE
translation sensor

### ISSUE THREAD

**Issue by Guille-Mas-Coll** [bruxy70/Garbage-Collection#142]
The translation of the sensor in Spanish does not appear in that language, it comes out in English.
{
     "state": {
         "_": {
             "today": "hoy",
             "tomorrow": "mañana"
         }
     }
}

![bug-garbage](https://user-images.githubusercontent.com/54454077/82070728-739b9d00-96d5-11ea-84a2-aae83fd0d88c.jpg)

**Comment by bruxy70** [comment]
What version do you use? I have tried right now and it seems to work:
![image](https://user-images.githubusercontent.com/44951610/82074095-85337380-96da-11ea-9396-7e2d461a38d9.png)

**Comment by bruxy70** [comment]
Tested Italian, works as well
![image](https://user-images.githubusercontent.com/44951610/82089956-e6684080-96f4-11ea-89b3-93e3a1aec0d0.png)

There are some important questions you deleted when opening the question. Without them, I do not know what I am looking at. What is the configuration of the integration? What is the Lovelace configuration? What is the version of HA?

**Comment by sira87** [comment]
HA version is latest: 0.109.6

I added 4 Garbage-Collection integrations, 1 for each of the 4 sensors I needed, and configured them via config-flow.

![chrome_2020-05-15_21-53-13](https://user-images.githubusercontent.com/62727221/82090991-e5381300-96f6-11ea-8543-e99b552b80bf.png)

Lovelace cards tested:
- Custom entites row (for sorting purposes):
`type: 'custom:auto-entities'
card:
  type: glance
  title: Raccolta Rifiuti
filter:
  include:
    - name: Umido
    - name: Indifferenziato
    - name: Plastica
    - name: Carta
sort:
  method: state`

and also the default entity card:

`type: entity
entity: sensor.indifferenziato
`
![chrome_2020-05-15_21-58-25](https://user-images.githubusercontent.com/62727221/82091239-495ad700-96f7-11ea-9670-d7281f81ffa1.png)

**Comment by bruxy70** [comment]
Hmm. I did exactly that. Configured in GUI, added entity card and switched to Italian:
![image](https://user-images.githubusercontent.com/44951610/82091765-3e547680-96f8-11ea-8c71-c8d769d82167.png)
Can you please check in your config/custom_components/garbage_collection folder, if there is a directory translations. Is it .translations or translations without the dot?

**Comment by sira87** [comment]
Sure, it is translations without the dot.

![chrome_2020-05-15_22-08-30](https://user-images.githubusercontent.com/62727221/82091975-a6a35800-96f8-11ea-9a5a-ff6929dd70e3.png)

**Comment by sira87** [comment]
Update: restarting HA again and Shift-F5 solved the issue for me.

**Comment by bruxy70** [comment]
Good one. Thanks. I would not find that one.

**Comment by Luke95vl** [comment]
sorry if I reopen, but I also have the same problem with the Italian language, even if I restart HA and press shift + f5 or try on another browser with a clean cache I don't see the translations. 
I noticed that sometimes, after a HA restart, the translation works, but after some time it returns to English, this happens both via browser and via smartphone apps.

Garbage collection is at the latest update
The problem occurred with both HA 109 and 110

**Comment by LasseRheinstroem** [comment]
same here

(HassOS 4.8 Supervisor 226)
all file checket
lastest update (2.28)
Shift + F5 checkt
different device checkt

no solution

**Comment by bruxy70** [comment]
@LasseRheinstroem , @Luke95vl , can you please check the 3.00-beta3. I have changed the device class and the state translations. Not sure if it solves the issue, but it changes the way it works in any case.

**Comment by LasseRheinstroem** [comment]
> @LasseRheinstroem , @Luke95vl , can you please check the 3.00-beta3. I have changed the device class and the state translations. Not sure if it solves the issue, but it changes the way it works in any case.

on 3.00-beta3 it works fine. btw good job with the integration
