### ISSUE TITLE
Error without attribute expire_after

### ISSUE THREAD

**Issue by cobradodo** [bruxy70/Garbage-Collection#143]
**Describe the bug**

if you do not use the expire_after attribute you receive the indicated error. With the attribute used everything ok (test in first sensor)

**Configuration**
YAML or Config Flow (GUI):

```
  sensors:
  - name: "Carta"
    frequency: "every-n-weeks"
    collection_days: "fri"
    move_country_holidays: IT
    period: 2
    first_week: 2
    verbose_state: True
    verbose_format: "il {date} fra {days} giorni)"
```

**Error log/debug information**
```
   next_date = self.get_next_date(today)
  File "/config/custom_components/garbage_collection/sensor.py", line 397, in get_next_date
    if next_date == now.date() and now.time() >= self.__expire_after:
TypeError: '>=' not supported between instances of 'datetime.time' and 'NoneType'
```
To enable debug logging, add `custom_components.garbage_collection: debug` to your config under logger/logs.

**Version**
Integration version : Installed: 2.22
Home Assistant version 0.109.6  HassOS 3.13

**Comment by bruxy70** [comment]
Thanks. Fixed. New release in a few minutes.

**Comment by bruxy70** [comment]
Can you please upgrade to 2.23 and let me know if this fixes that? Thanks!

**Comment by cobradodo** [comment]
All right. Perfect works. Thank you very much
