### ISSUE TITLE
User Input Malformed

### ISSUE THREAD

**Issue by bwoodworth** [bruxy70/Garbage-Collection#145]
**Describe the bug**
When clicking submit on the final screen using the integration UI an error occurs.

**Configuration**
YAML or Config Flow (GUI): Config Flow (GUI)

```
https://imgur.com/a/yOl3jHf
```

**Error log/debug information**
```
No errors in logs
```
To enable debug logging, add `custom_components.garbage_collection: debug` to your config under logger/logs.

**Screenshots**
See above

**Version**
2.23

**Comment by bruxy70** [comment]
Interesting. I have no idea where this error comes from - not one of the messages I put in. What are the parameters configured in the previous steps?
I added an additional debug details in the configuration. Would you mind grabbing the file https://github.com/bruxy70/Garbage-Collection/blob/development/custom_components/garbage_collection/config_flow.py
And putting it in your /config/custom_components/garbage_collection (replace the old one), restart HA, try again and check the logs? Thanks!

**Comment by Gavin-A92** [comment]
Hi
I get the same error when editing an existing Integration through the UI, though not when creating a new Integration (or editing it afterwards) if that's any help.

Replaced the config_flow.py as per your note above but not seeing any errors or warnings in logs from this component.......

**Comment by bruxy70** [comment]
Looks normal, except for "removed" in unique_id. Not sure how it got there. It should be a unique number, something like b46db311-54e8-43b2-b1f4-cb60b9ad6e31
And there is another copy called "options", that is exactly the same, correct?

**Comment by Gavin-A92** [comment]
Sorry, I removed the ID before I pasted it in here....should have mentioned that.

**Comment by bruxy70** [comment]
Hmm, nothing obviously wrong. I just made a 2.23-beta, where I try to clean-up the data at the start. Can you please try that?

**Comment by Gavin-A92** [comment]
Updated to new Beta.......
When trying to edit an existing Integration I'm getting a message saying "Please wait while the integration is being installed" and that pops up and then stays on screen.......no errors in logs that I can see.
Integrations created in the previous version can be edited no problem.

Let me know if you need anything else

PS - I edited my original Integrations via the core.config_entries to add the expiry time and that worked no problem

PPS (and off-topic so sorry) given that this does so much more than Garbage what's involved in changing the component name............more curious than anything else...cheers

**Comment by bruxy70** [comment]
Weird, I do exactly the same, and it works smoothly. So what you say is, when you create a new integration, and then go to edit the options, it always does that, correct?

About changing the name, I thought about that. But then I suppose everybody would have to configure everything again I suppose. Not sure if it is worth it.
I'l also probably need to remove it from HACS and insert the new one, which would again be quite disruptive.

**Comment by Gavin-A92** [comment]
_Weird, I do exactly the same, and it works smoothly. So what you say is, when you create a new integration, and then go to edit the options, it always does that, correct?_
Yeah that's exactly it.....bizarre 
Create a new one and not a prob editing or even running through the edit process without changing anything but on an "older" on it throws the error and will not save changes.
Not an issue for me so maybe the "fix" is recreate if you want then editable through the UI.

Thanks for the response on the naming too......you're right, the current name vs the hassle of changing it is prob too disruptive.

**Comment by ministryofsillywalks** [comment]
+1 on this issue. Tried adding an expiration time to existing collection and keep getting the error.

**Comment by Gavin-A92** [comment]
@ministryofsillywalks  while not yet a fix, if you add `"expire_after": "12:00",` to both the data and options section of the core.config_entries in .storage for the Integration you are looking to edit, this will achieve the same result as editing through UI.

Also as I mentioned above if you recreate your Integration it appears you can edit/update without issue.

**Comment by bruxy70** [comment]
Hold on guys, I am able to replicate it now, I am closing on the issue...

**Comment by bruxy70** [comment]
I think i cracked it 🎉
Can you please upgrade to 2.24-beta and confirm (available through HACS).
Thanks!

**Comment by Gavin-A92** [comment]
I've just updated there and ran through an edit (though changed nothing) - all seems fine, the process ran through without issue so looks like issue resolved.

**Comment by ministryofsillywalks** [comment]
Can confirm it's working now. Updated my integrations without an issue.
Thanks for the quick fix!

**Comment by bruxy70** [comment]
@Gavin-A92 
You brought up the issue with the duplicate config in options and data. I made a beta of 2.27 (available from HACS). If you could help and test that one, it would be great. This hopefully fixes that (removes options, keeps data). Thanks.

**Comment by Gavin-A92** [comment]
Updated last night and the component works as normal........didn't know the Data & Options thing was an "issue" so never checked it until I saw your post......

No changes in core.config_entries though, both sections exist for each of the entities I've created. Created a new one to test too and that creates Options & Data in the core file.
As I mentioned didn't know that was an "issue" to be honest as all works fine and unless you're digging in the .storage files you'd not see it but anyway let me know if you need anything else.....
