### ISSUE TITLE
New feature for multiple monthly_day_order_number ?

### ISSUE THREAD

**Issue by olijouve** [bruxy70/Garbage-Collection#15]
Hi,

Awesome work, thanks a lot !!
Where i live large waste are collected the 2nd and 4th friday of each month.
Could it be possible to have multiple days(2) for monthly_day_order_number ?

Your plugin is so usefull, far better than filling every dates in a google calendar   !!

Olivier

**Comment by bruxy70** [comment]
Glad you find it useful. Ok, I will look at that.

**Comment by bruxy70** [comment]
Included in v1.12. Enjoy!

**Comment by olijouve** [comment]
You rock !!  Many thanks !
