### ISSUE TITLE
0.110 icons are no longer there

### ISSUE THREAD

**Issue by nickrout** [bruxy70/Garbage-Collection#150]
After updating to 0.110 the garbage icons have disappeared.
A clear and concise description of what the bug is. Steps to reproduce.

**Configuration**
Config Flow (GUI):

```
This is what annoys me about config-flow!
```

**Error log/debug information**
```
Copy the error message from Developer tools/Logs here. 
```
To enable debug logging, add `custom_components.garbage_collection: debug` to your config under logger/logs.

**Screenshots**

**Version**
2.25 but was present on 2.23 too.

**Comment by bruxy70** [comment]
I cannot reproduce it. The icons look fine.
One of the ways to check the config is in the /config/.storage/core.config_entries
Search for the garbage_collection sensor.

**Comment by Porzeczek** [comment]
I have this on two hasses, here is log:

```
Logger: frontend.js.latest.202005190
Source: components/system_log/__init__.py:209
First occurred: 8:42:02 (1 occurrences)
Last logged: 8:42:02

http://10.8.0.108:8123/hacsfiles/custom-header/custom-header.js:1:16344 Uncaught TypeError: Cannot read property 'style' of null
```

**Comment by bruxy70** [comment]
Not sure what this has to do with the custom-header plugin.
Please go to the developer tools/states, search for the sensor, click on the (i) icon and send me what the window looks like. The icon should be in the left top corner. 
![image](https://user-images.githubusercontent.com/44951610/82531822-5e44c980-9b40-11ea-9772-c3d6dd0782b2.png)

Is it missing? Then please try to send me the configuration - either a screenshot of the OptionFlow or as I wrote before. 
Are there any errors from garbage_collection?
Thanks.

**Comment by Porzeczek** [comment]
Ops, sorry i'm before first cofee :)

And you have absolutely right it's not 'garbage-collection' problem its another plugin fault - 'garbage collection-card'  and it has issue for this: https://github.com/amaximus/garbage-collection-card/issues/36

@nickrout do you use 'garbage-collection-card'?

**Comment by amaximus** [comment]
The custom Garabage Collection Card has been updated to fix the disappeared icons issue.

**Comment by nickrout** [comment]
Yes the custom card update fixed it. Thanks all.
