### ISSUE TITLE
.110 & 2.25 can't edit previously added gabrages

### ISSUE THREAD

**Issue by Porzeczek** [bruxy70/Garbage-Collection#151]
This is another bug on my two hasses: 
Can't edit previously added integrations. It stops with info 'Please wait, installing integrations'.
But if i add another (new) one i can edit it, configuration dialog shows immediately. 
I probably should re add all my garbage and forget about it but i ve enabled debug log for previous issue so here it is (i hope this time with more sense ;> ) :

```
Logger: aiohttp.server
Source: custom_components/garbage_collection/config_singularity.py:49
First occurred: 8:47:26 (1 occurrences)
Last logged: 8:47:26

Error handling request
Traceback (most recent call last):
  File "/home/hass/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/hass/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/hass/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/hass/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/home/hass/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/home/hass/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/home/hass/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 125, in handle
    result = await result
  File "/home/hass/homeassistant/lib/python3.7/site-packages/homeassistant/components/config/config_entries.py", line 186, in post
    return await super().post(request)
  File "/home/hass/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/data_validator.py", line 54, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/home/hass/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/data_entry_flow.py", line 72, in post
    "show_advanced_options": data["show_advanced_options"],
  File "/home/hass/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 129, in async_init
    flow, flow.init_step, data, init_done
  File "/home/hass/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/home/hass/homeassistant/.homeassistant/custom_components/garbage_collection/config_flow.py", line 379, in async_step_init
    CONFIGURATION.clean(self.config_entry.options)
  File "/home/hass/homeassistant/.homeassistant/custom_components/garbage_collection/config_singularity.py", line 49, in clean
    del data[key]
TypeError: 'mappingproxy' object does not support item deletion
```

**Comment by bruxy70** [comment]
Can send me the configuration of the integration from /config/.storage/core.config_entries
I will configure the same and try to replicate that. It would help a lot. Thanks!

**Comment by Porzeczek** [comment]
I think i've found problem:
If entry has set `"force_week_order_numbers": true,` then you cant edit it. After removing this line from core.config_entries dialog is showing up.
Also when adding new garbage with this setting it's not stored.

**Comment by bruxy70** [comment]
It is right, it should not be stored. This is an added complication from someone's feature request, that allows counting week numbers instead of the normal nth weekday of the month. It made the config quite messy. It is a switch in the config flow that switches between use of week_order_number and weekday_order_number. I should not have done this. Anyhow. thanks, will check that one.

**Comment by bruxy70** [comment]
I tried to add it in, and it correctly fixed that (removed that), no errors, no complaints.
Please try to send me the full config of this sensor, I will try to replicate it.
You use version 2.25, correct?

**Comment by Porzeczek** [comment]
Yes, 2.25 & hass 0.110.1
these are trash taken two times a month in 2nd and 5th week on wednesday. 

```
            {
                "connection_class": "local_poll",
                "data": {
                    "collection_days": [
                        "wed"
                    ],
                    "date_format": "%d-%b-%Y",
                    "exclude_dates": [],
                    "first_month": "jan",
                    "force_week_order_numbers": true,
                    "frequency": "monthly",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "include_dates": [],
                    "last_month": "dec",
                    "move_country_holidays": "PL",
                    "observed": true,
                    "period": 1,
                    "prov": "",
                    "state": "",
                    "unique_id": "4a451b92-4227-4aa7-b285-0bfc974faa31",
                    "verbose_format": "on {date}, in {days} days",
                    "verbose_state": false,
                    "week_order_number": [
                        2,
                        5
                    ],
                    "weekday_order_number": []
                },
                "domain": "garbage_collection",
                "entry_id": "edbd67dcccfc4a098ef2d1ae1f06a86b",
                "options": {
                    "collection_days": [
                        "wed"
                    ],
                    "date_format": "%d-%b-%Y",
                    "exclude_dates": [],
                    "first_month": "jan",
                    "force_week_order_numbers": true,
                    "frequency": "monthly",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "include_dates": [],
                    "last_month": "dec",
                    "move_country_holidays": "PL",
                    "observed": true,
                    "period": 1,
                    "prov": "",
                    "state": "",
                    "unique_id": "4a451b92-4227-4aa7-b285-0bfc974faa31",
                    "verbose_format": "on {date}, in {days} days",
                    "verbose_state": false,
                    "week_order_number": [
                        2,
                        5
                    ],
                    "weekday_order_number": []
                },
                "source": "user",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "Plastiki",
                "unique_id": null,
                "version": 1
            },
```

**Comment by bruxy70** [comment]
@Porzeczek , This was fixed in 2.26.
There is a beta of 2.27 (available from HACS). If you could help and test that one, it would be great.
You brought up the issue with the duplicate config in options and data. This hopefully fixes that (removes options, keeps data). Thanks.

**Comment by joselito11** [comment]
After some update, this sensor gives error:
- name: Plastika
      frequency: "monthly"
      collection_days: "tue"
      #period: 4
      first_date: '2020-01-14'
      verbose_state: True

garbage_collection: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/garbage_collection/sensor.py", line 460, in async_update
    next_date = self.get_next_date(today)
  File "/config/custom_components/garbage_collection/sensor.py", line 389, in get_next_date
    next_date = self.find_candidate_date(first_day)
  File "/config/custom_components/garbage_collection/sensor.py", line 336, in find_candidate_date
    return self.__monthly_candidate(day1)
  File "/config/custom_components/garbage_collection/sensor.py", line 262, in __monthly_candidate
    for weekday_order_number in self._weekday_order_numbers:
TypeError: 'NoneType' object is not iterable

**Comment by bruxy70** [comment]
Hi,
Can you please add the parameter `weekday_order_number: 1` into the config? I think it lost the default value some time ago, when I was adding the alternative `week_order_number`. The two parameters are competing, and based on which one is there it will figure out how to count. So they do not have default value. 
Also, the `first_date` parameter is not used in monthly frequency, it has a meaning for every_n_days, where it means - every n days starting from the date.
You have commented period with value 4, so it will default to 1, ok?
Can you please change that, restart HA and check if it still gives the error? Thanks.

**Comment by joselito11** [comment]
Thank you, the sensor is working now. For the next week it is showing ok, will this function with these table: https://imgur.com/a/Ynynmjb . They are starting on 14.jan and drive it evey month on tuesday, but different dates

**Comment by bruxy70** [comment]
I do not think these dates follow any generic rule, like 2nd Tuesday every month. Some months they are on 2nd, but then on the 1st. They do not even follow the week number. It looks like somebody just decided them manually, they do not follow and rule.
What I'd do for these is, I'd add them to google calendar, and google calendar event https://www.home-assistant.io/integrations/calendar.google/

**Comment by joselito11** [comment]
Thank for help!

**Comment by bruxy70** [comment]
Or maybe, they are not monthly, but every 4 weeks. So if you use frequency every_n_weeks, period 4 and first_week 3.....

**Comment by bruxy70** [comment]
Alternatively, you can do every_n_days, with period of 28, and leave the first_date :)

**Comment by joselito11** [comment]
Thank you!
