### ISSUE TITLE
Config flow does not have 'Garbage Collection' as an option.

### ISSUE THREAD

**Issue by charmanr** [bruxy70/Garbage-Collection#160]
Installed with HACS.  Config flow does not show Garbage Collection as an option, and when attempting to add the config to the configuration.yaml file I cannot get the config to validate before restarting.  Attempting to validate just gives me the spinning wheel.  I let it go for an hour before giving up.

Forgive me if this is something simple that I am missing, but I only started my Home Assistant journey 3 days ago.

**Comment by bruxy70** [comment]
I think you have to restart HA after adding new integration. After that, after that it is dynamic, you do not have to restart - if you configure it from ConfigFlow.

**Comment by charmanr** [comment]
Thank you.  I have restarted and still have the same issue.  

I am using the latest version of HA (updated yesterday) on a Raspberry Pi.  Not sure if that makes a difference?

**Comment by bruxy70** [comment]
Ok, so apparently you need to refresh your browser cache, and it will show up. Let me know.  Thanks.
https://hacs.xyz/docs/configuration/basic#clear-your-browser-cache

**Comment by charmanr** [comment]
Thank you!!!  It now appears and I'm setting it up.  

Thank you for taking the time to create this and help with setting it up.

Have a (socially distanced) handshake and a thumbs up from me!

**Comment by broyuken** [comment]
I cleared my browser cache and it's still not showing up. Restarted HA, cleared cache, restarted HA again and its still not there. Any ideas?
