### ISSUE TITLE
3.00-beta testing - Home Assistant Calendar

### ISSUE THREAD

**Issue by bruxy70** [bruxy70/Garbage-Collection#161]
Feedback from testing the version 3.00-beta1 is very welcome.
Does it work?
Is it useful?
Suggestions?

**Comment by hasenbolle** [comment]
For the callendar does work. Thank you for the implemantation.

Just one suggestion:
Would it be possible to show all garbage collection dates in the calendar and not just the next collection date?

**Comment by bruxy70** [comment]
Yes, I think it should be possible. I'll need to change the integration quite a bit, but I think this can be done.

**Comment by bruxy70** [comment]
@hasenbolle , try the beta3. It should work. But it was quite brutal. I had to re-write the whole logic of the entity registration and much other stuff. I wonder how it works on things like RPi. I guess I'll leave it on beta for about a week to make sure it is tested properly.

**Comment by hasenbolle** [comment]
Thank you for the fast implementation. 
Did a quick test yesterday evening. So far looking good, except for one little bug.

Collection days in the past do not take a holiday into account.
For example: On 5th April  (Monday) is a holiday in germany. So with the option "holiday_in_week_move", it should move the collection day to the following day. 
I look in the log and saw that holidays are only collected from today on. I think this should be the reason.

Yes, i know, nobody looks for collection days in the past, but it is a little bit confusing.

First call of the calendar tab took around 3-4 seconds on a RPi4 (4GB).

**Comment by bruxy70** [comment]
Right, I missed that one. Thanks! It was designed to work the closest collection from today, so it also loads the holidays from today onwards - will need to change that too :). The same thing was with the groups - it took the current state of the sensors and did not re-calculate them etc. Looks like there will be one more beta :).

**Comment by bruxy70** [comment]
Can you please install and do a quick test of the development branch? I pulled loading of the holidays to a separate method and I call it in before the daily update as well as when refreshing the calendar. So it should work.
I also added a `hidden` attribute BTW, that will hide the sensor from the calendar (in case they are used in groups).

**Comment by hasenbolle** [comment]
Works flawlessly for me. Big thanks :)

**Comment by amaximus** [comment]
@bruxy70 , it's a good idea to make it a more general scheduler. You could freeze the garbage-collection and take it as a base for the general scheduler (in its inital version would require only renaming). The use case/example would be the garbage collection schedule.
As for moving to calendars, it's a lot of administrations on user side to have separate calendars for the different garbage collections. I'm not sure users want to create extra calendars for this as usually they already have several ones to manage (private, work, public/shared with wife). So I would stick with sensors.
