### ISSUE TITLE
Problem in IT language

### ISSUE THREAD

**Issue by lrzdeveloper** [bruxy70/Garbage-Collection#163]
Hi! 
I installed the extension and configured it correctly, everything works. The thing that bothers me is that when it has to warn me that they have to come and pick up the garbage, there is no italian translation (there's English). How can I manage that?

**Comment by bruxy70** [comment]
How did you set-up the warning? Is it an automation? Then you just do that one in Italian. Or is it another custom component? Then check with the author of this component.

**Comment by lrzdeveloper** [comment]
I did some reboots, 5 to be precise, because I made some changes on other things and now everything fixed on its own. In the previous reboots the language didn't change.

**Comment by Metus88** [comment]
Could I know how to set the Italian language? I used from 3 months and I didn't know that it was possible to change language...
