### ISSUE TITLE
Where is the Calendar?

### ISSUE THREAD

**Issue by PierreScerri** [bruxy70/Garbage-Collection#165]
**Write your question here**

I cannot figure out how to make the garbage collection calendar visible in Lovelace.

I have Calendar set up in HA and it shows me my iCloud and Google calendars.

What am I missing?

**Comment by bruxy70** [comment]
It should automatically add a new calendar Garbage Collection with all your sensors, right after upgrade/restart.
Not sure why yours is not there. Does it give any error message?
If you go to the developer tools/states, does it have calendar.garbage_collection?
![image](https://user-images.githubusercontent.com/44951610/83943529-4b4b1e00-a7fd-11ea-963e-635239f5d55a.png)

**Comment by PierreScerri** [comment]
Oops!  Didn't restart HA.  Ok got it.  Thanks.

**Comment by fi-sch** [comment]
Hey! Silly question. How can I disable calendar integration or sensor?
I don't use any calendars in my HA and it's quite annoying that a new icon appeared at my sidebar. Thank you!

**Comment by bruxy70** [comment]
I do not know, but I tend to agree that HA should have an option to configure tabs in the menu or configure common options for the integrations (like setting the calendar name or disabling it).

**Comment by fi-sch** [comment]
> I do not know, but I tend to agree that HA should have an option to configure tabs in the menu or configure common options for the integrations (like setting the calendar name or disabling it).
Is it possible to stop your integration from creating this calendar entity?

**Comment by bruxy70** [comment]
Oops, typo. It is `hidden`. Thanks for the find.
I can stop creating the calendar, but it will stop it for everybody. Ideally, this would be an option you could configure for the whole integration, but as I said, HA does not allow such a general configuration option. 
I guess the easiest option is to use the previous version.

**Comment by fi-sch** [comment]
Ok, I totally get it :) Thank you for such quick response!

**Comment by bruxy70** [comment]
I have tried something. Download `__init__.py` from the development repository, put it in your HA, set all sensors as hidden, restart HA ane let me know if that works.
I moved the calendar creation to each entity, making sure I only create one (hopefully), and skip it if the sensor is hidden. So this should work.
It is kind of sad you do not like the calendars though. I chatted with balloob a few weeks back and he was quite excited about the calendar - even suggesting that there is no need for garbage collection anymore, as it should be easy with calendars. So I assume there will be more features comming with automation based on calendars. So I'd get used to them,
I am even thinking to move from using sensors to calendars. It is kind of redundant, it will do same thing, and unlike the sensors, the calendars will show all collections, not only the next one.

**Comment by fi-sch** [comment]
I'm about to leave my home, so I will test that tomorrow :) Thanks! I will let you know about the outcome.

Don't get me wrong. It's a great feature! I'm just not using any calendars in HA at this moment and having this calendar icon just for garbage collection is a little bit overkill. Vertical space on this sidebar is quite precious to me so +1 icon makes a huge difference. Especially because I'm not able to set their order to preferred one and I have to scroll to the bottom everyday for a couple of times... :/
I will use calendars in the future, for sure. And yes, there is a huge potential there :) Can't wait to see more!

**Comment by fi-sch** [comment]
@bruxy70 Ok, so I've just tried what you proposed.
'hidden' property was not accepted just after I updated the `__init__.py`, so at first I restarted my HA with the new file in place. After restart I got this error:
```
Logger: homeassistant.setup
Source: setup.py:139 
First occurred: 12:07:31 (1 occurrences) 
Last logged: 12:07:31

Setup failed for garbage_collection: Unable to import component: No module named 'custom_components.garbage_collection.calendar'
```
So I went to config and uncommented 'hidden' properties for all sensors. But now when I try to restart HA it gives me the same error:
```
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:300 
Integration: Hass.io (documentation, issues) 
First occurred: 12:08:37 (1 occurrences) 
Last logged: 12:08:37

Component error: garbage_collection - No module named 'custom_components.garbage_collection.calendar'
```

**Comment by fi-sch** [comment]
@bruxy70 Forget what I wrote in the post I've just deleted. I forget that I did downgrade the Garbage Collection integration as you suggested before :) 

So I did what you said and right now I get the following error on HA startup:
```
Logger: homeassistant.components.sensor
Source: custom_components/garbage_collection/sensor.py:219 
Integration: Sensor (documentation, issues) 
First occurred: 12:21:13 (1 occurrences) 
Last logged: 12:21:13

Error while setting up garbage_collection platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 444, in _async_add_entity
    await entity.async_added_to_hass()
  File "/config/custom_components/garbage_collection/sensor.py", line 219, in async_added_to_hass
    self.hass.data[DOMAIN][CALENDAR_PLATFORM].add_entity(self.entity_id)
KeyError: 'calendar'
```

**Comment by bruxy70** [comment]
Right, missed that one. Ok, again, please get `__init__.py` and `sensor.py` and try again. I moved it even further to the sensor registration. Seems to work here. Let me know.

**Comment by fi-sch** [comment]
I can confirm that this works as intended :) Thank you!
