### ISSUE TITLE
Weekly trash/ Bi-weekly Recycling

### ISSUE THREAD

**Issue by fiservedpi** [bruxy70/Garbage-Collection#167]
**Write your question here**

I'm struggling wrapping my head around how I would do weekly trash  AND Bi-weekly recycling, any advice?

**Comment by bruxy70** [comment]
You add two sensors - one frequency weekly, second be-weekly (odd/even weeks or every n weeks).
If you do it from GUI, just add the garbage collection, and then add it again, it will add them together.
So you will have 1 sensor for weekly trash and second for recycling.
If you want to combine them to have one only, you can create another one frequency group, put them together and then ignore the others. But people usually keep them separate so they know which one is due (I have like 5 - rubbish, plastics, paper, bio and large items). And some of them have a different schedule in winter and in summer - this is what I use the group for - I create one for summer, another one for winter and then group them together.

**Comment by fiservedpi** [comment]
Awesome! Thanks I didn't realize I could add a second sensor
