### ISSUE TITLE
Automation is not triggerred by state change

### ISSUE THREAD

**Issue by pomkos** [bruxy70/Garbage-Collection#171]
**Describe the bug**

After setting up automation to notify me when trash day is 1 day away, it only works manually (IE: I click "execute" and my notification is sent. But if I wait for the appropriate day to come, no notification is sent).

I am on the latest hassio, however the automation did not work on previous version either.

I am wondering if my automation is setup incorrectly?

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 
Config Flow

```yaml

```

**Error log/debug information**

```txt
Unavailable until next week, when next state change happens.
```

**Screenshots**

Configuration:

![image](https://user-images.githubusercontent.com/8731022/84382351-7d230280-abb8-11ea-8309-223cc95f27b6.png)

Automation:

![image](https://user-images.githubusercontent.com/8731022/84382468-a80d5680-abb8-11ea-9075-9cef47253d34.png)

**Version**

Integration version: 3.01

Home Assistant version: HassOS 4.8

os_version: 5.4.42-v7

**Comment by bruxy70** [comment]
If you enable verbose state, the state will be verbose. It will be text, instead of number.
So it will not be 2 and 1

If you want to test that quickly, go to the Developers Tools, States. Click on the sensor, change the state and hit set... It should trigger it.

**Comment by pomkos** [comment]
Ah, that was it. Thanks for the tip!
