### ISSUE TITLE
Translation doesnt seem to be changed after language change

### ISSUE THREAD

**Issue by KrzesloSzatan** [bruxy70/Garbage-Collection#173]
Hi there, it seems that something doesnt work as it should with the translations either on my side or the integration. I have installed your integration via hacs now and regardless of language that i set for my user it still shows Tommorow or Today in english as shown on the picture. 
![obraz](https://user-images.githubusercontent.com/63119934/85025633-ec2fc680-b177-11ea-9e23-5f0e559b788c.png)

Is it something i have done wrong with the configuration or its something with my HA configuration ? While it doesnt really bother me personally my parents are complaining ;) I tried on polish and italian translation an it is still Today and Tomorrow in english.

**Comment by bruxy70** [comment]
Try refreshing the browser cache, some people said this helped with missing translation. If this does not help..
What does it show in Developer Tools/States under the (i) icon?
How does the configuration look like?
I am sorry, I do not know what I am looking at. This could be coming from different places 0 it could be the Lovelace card config, it could be the sensor config.

**Comment by KrzesloSzatan** [comment]
I understand its not easy for you to say something while you have to vase only on my description. But refreshing the cache, reloging and browsing in private doesnt help. I have done a restart after language change and it was still the same. What actualy helped right a moment ago was when i have istalled something via hacs completeley unrelated to your integration and when i opened my view again it was in proper language. Problem is not accureing only on one user so im assuming its not user related, but rather HA or integration itself. Dunno the process how it should work to debug anything, but i assume its as simple as matching the same prefix for language  ?

**Comment by bruxy70** [comment]
Ok, not sure what is it. HA provides front end localization services. The integration contains the directories with all the translations. So it should take it from there. But there were some changes in HA architecture for localization, and I know it was causing an issue with the browser cache to some users.
Good that it works now.

**Comment by KrzesloSzatan** [comment]
Not exactly it works xD Well, like i said it happened few times already and it appears to repair itself while im doing something with configuration completely unrelated to your integration. Anyway, if you dont have any clue whats going on i will try to investigate it more or try to trigger it somehow.
