### ISSUE TITLE
Give ability to set many specific dates

### ISSUE THREAD

**Issue by mike240se** [bruxy70/Garbage-Collection#174]
**Is your feature request related to a problem? Please describe.**
yes, my recycle is on a fixed schedule, every year before the new year we get a calendar with all the dates for the year.  every year this changes but i know every date for the upcoming year ahead of time.  there is no way to just add all these dates all at once in one single collection.

**Describe the solution you'd like**
in addtion to the annual give a collection option to let you add multiple dates manually, perhaps comma seperated, etc.

**Describe alternatives you've considered**
would need to create an annual for every single specific date, then have to delete them all because they will change the next year.  

The docs say "Using include dates you can add additional dates manually." i thought this meant i would have the option to add addtional dates to the annual but didnt see any way to do it and got errors when trying to include multiple dates.  perhaps i am just doing something wrong.

for now i am using a every 3 week option as it catches 90% of my dates but the other non-standard 10% are the problem.

for my use case, just being able to type in the dates once a year for the upcoming year would be the best option as its not that many dates to type in and its only once a year it needs to be done.

**Comment by bruxy70** [comment]
Yes, you can add multiple dates with the include_dates option. Comma separated, or a list if you configure it in YAML. Make sure you use the correct format ('yyyy-mm-dd'). If this is in YAML, make sure they are in quotes. If in GUI, just a comma separated list (there is a validator that should check that you enter the right format). 
See the [example](https://github.com/bruxy70/Garbage-Collection#configuration)

I'd also think if using a google calendar integration would not be a better option. The garbage collection is great for events that have some pattern. But to set different events with random dates, a standard calendar might be e better choice.
