### ISSUE TITLE
RE: holiday_in_week_move

### ISSUE THREAD

**Issue by quiglag** [bruxy70/Garbage-Collection#175]
Currently when "holiday_in_week_move" is enabled, the collection day is moved to the next day even if the holiday is after the collection day. Is it supposed to act that way? Shouldn't it only move to the next day if the holiday is before the collection day and not on a weekend? Thx

**Comment by bruxy70** [comment]
@chriss158 , can you please explain how this works? Thanks!

**Comment by chriss158** [comment]
> Currently when "holiday_in_week_move" is enabled, the collection day is moved to the next day even if the holiday is after the collection day. Is it supposed to act that way? Shouldn't it only move to the next day if the holiday is before the collection day and not on a weekend? Thx
> 

Yes your are right. It shouldn't act this way. I will have closer look at this today.

**Comment by 1h8fulkat** [comment]
"shouldn't it only move to the next day if the holiday is before the collection day and not on a weekend?"

This is correct with the caveat that it should be bumped back 1 day if the holiday occurs before **or on** the collection day and not on a weekend.

**Comment by chriss158** [comment]
> "shouldn't it only move to the next day if the holiday is before the collection day and not on a weekend?"
> 
> This is correct with the caveat that it should be bumped back 1 day if the holiday occurs before **or on** the collection day and not on a weekend.

But that should be configurable. This does not apply for my garbage collection company.
For me following rule is applied:
If a holiday is in week and it is before the collection day, then move the collection day, one day further incl. Saturday. But not Sunday.

Maybe there should be an option for the number of the days which the collection day should be moved.
"move_days".  For this would be "1" and for you this would be "-1".

**Comment by bruxy70** [comment]
Here we come again. There were already quite a few feature requests for different handling of exceptions, and each of them was different. There is no way to make a simple yet universal rule that will fit all scenarios, the configuration is already confusing enough, with move holidays and holidays in week move. I find the concept of moving a collection if there is a holiday on that week strange. But it exists apparently, and there are plenty of even more strange scenarios. Let's not make it even more confusing. 
For these exceptions, I added include_dates and exclude_dates parameters. You can now check the calendar once a year when you set it up, and add the exceptions.

**Comment by chriss158** [comment]
OK, I see. 
What do you think, should @quiglag initial issue fixed? As it does not make sense (at least for me) to move the collection day forward, if a holiday is after the collection. But as you already said, there could be some other scenario which needs exactly the current implementation. So there is no right or wrong solution for the problem.

It would be quite an easy (fix): https://github.com/chriss158/Garbage-Collection/commit/937d4a72b2d4ea2b0b8afa267f68c8c9043df29c

**Comment by quiglag** [comment]
I think @1h8fulkat was agreeing with us but clarifying that the collection day should also move 1 day if a Holiday is **on** the normal collection day. I forgot to say this in my initial post. At least that is how I read it.  And when I said excluding weekends, I meant only excluding Holidays on weekends. I understand if a trash day needs to be moved to a weekend if your normal collection day is a Friday.

**Comment by bruxy70** [comment]
@chriss158, If the current functionality makes no sense and the change will improve that, ok, go ahead and send the PR.
But I would like to avoid adding additional parameters to support specific scenarios.

**Comment by 1h8fulkat** [comment]
Correct @quiglag , I was agreeing and specifying the "on picking day" as well
