### ISSUE TITLE
Allow users to select trash company recognized holidays

### ISSUE THREAD

**Issue by 1h8fulkat** [bruxy70/Garbage-Collection#176]
**Is your feature request related to a problem? Please describe.**

The garbage collection is getting bumped back 1 day for non-recognized (by the trash company, in my case [Waste Management](https://www.wm.com/location/california/cabay/ukiah/collection-holidays.jsp)) holidays like Veterans day and Black Friday which are considered "Public Holidays" in the US.

**Describe the solution you'd like**

Users should be able to enter the names of excluded holidays to avoid bumping back trash collection on non-recognized holidays.

**Describe alternatives you've considered**

Display a check box list of all "public holidays" and uncheck the ones that are not recognized. 

**Additional context**

In my case November is 50% wrong.  The Integration is bumping the second week by a day and it should not be bumped at all as Veterans day is not recognized by WM.  It is also bumping Thanksgiving week by 2 days but it should only be bumped by 1 day since Black Friday is not recognized by WM.

**Comment by bruxy70** [comment]
Thanks for the suggestion, but I am not planning to extend the exception handling for hollidays. There are so many different rules and it is confusing enough already.
There are two parameters you can use - include dates and exclude dates. There you can add the dates you'd like to skip or add.
