### ISSUE TITLE
Start and end months, how to force calendar to recognise them?

### ISSUE THREAD

**Issue by sym0nd0** [bruxy70/Garbage-Collection#178]
Hi,
I've just been looking through the calendar and have Garbage Collection entries showing for every month, past and present. I have start and end dates set for each sensor but it doesn't appear to be understood by the calendar. :/

Sadly, my council change their collection dates (December to November for most bins and April to March for one) each year, so there is no point having the dates continue past the end dates and they will more than likely change for the next 12 months.

How can I force the calendar to only show the date ranges set for each sensor?

Thanks!

**Comment by bruxy70** [comment]
I am not sure what you mean by start date and end date, but if you mean first and last month then that's weird, they should work with the calendar. I have tested that and it works for me.
The whole integration is made for schedules based on some defined rules. If the rules keep changing, you have two options.
Either update the rules when they change (e.g. at the beginning of new year) - it would update the calendar.
Or use a different integration, like the integration with google calendar, where you can also create recurrent events, but you can also re-schedule them individually.

**Comment by sym0nd0** [comment]
Sorry, I used the wrong terminology, it should have been first collection month and last collection month.

Where I have a bin sensor with a first collection month of April and the last of March I (probably incorrectly, now I think about it) assumed that it would only populate entries on the calendar for those months and there would be no entries (before or after). 

But now I type it out, and based on what you've said, why would it. Sorry, ignore me!
