### ISSUE TITLE
Calendar entries confused in Jan 2021

### ISSUE THREAD

**Issue by rccoleman** [bruxy70/Garbage-Collection#179]
**Describe the bug**

My trash collection is on Monday and every week I either have landscape debris *or* recycling in addition to normal household trash.  I've set up 2 sensors, one for recycling and one for landscape, each on Monday and alternating weeks.  I'm finding that the entries are created correctly until Jan 11 2021, where weirdly both end up on that same day, and then they alternate on the wrong weeks from then on.  Here's a screenshot:

<img width="1361" alt="Screen Shot 2020-07-06 at 1 08 16 AM" src="https://user-images.githubusercontent.com/860888/86571199-e8e15c80-bf25-11ea-9765-6c03152544ff.png">

I've tried setting each of them to every-n-weeks and odd/even weeks, and also starting them at different week numbers during the year.  They always start failing on Jan 11, 2021.  Maybe it's happening because there's no Monday in the first week of January?  My collection dates don’t really start or end in a certain month and instead just continue on in perpetuity alternating weeks, so maybe that’s the disconnect.  Maybe I need a ‘start now, no end month’ option for this. I see that ‘last collection month’ is an optional parameter, but I don’t see how to leave it empty in the config flow. 

In any case, Jan 11 should only have Recycling, and the next week should be Landscape, and so on.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? :  Config Flow

```json
            {                                                           
                "connection_class": "local_poll",                       
                "data": {                                                                                                           
                    "collection_days": [                                
                        "mon"                                           
                    ],                                                  
                    "date_format": "%d-%b-%Y",                          
                    "exclude_dates": [                                  
                        "2020-09-07"                                    
                    ],                                                  
                    "first_month": "jan",                               
                    "frequency": "odd-weeks",                           
                    "holiday_in_week_move": false,                      
                    "icon_normal": "mdi:recycle",                       
                    "icon_today": "mdi:calendar-check",          
                    "icon_tomorrow": "mdi:calendar-arrow-right",
                    "include_dates": [                                  
                        "2020-09-08"                                    
                    ],                                                  
                    "last_month": "dec",                                
                    "observed": true,                                   
                    "unique_id": "9a669dca-a9c0-4ae2-b4a4-145eeaf39a45",
                    "verbose_format": "on {date}, in {days} days"
                },                                             
                "domain": "garbage_collection",                
                "entry_id": "72c950a7848b4675be05a50a546f80c3", 
                "options": {},                                  
                "source": "user",                               
                "system_options": {                                     
                    "disable_new_entities": false                       
                },                                                      
                "title": "Recycling",                                   
                "unique_id": null,                                      
                "version": 1                                            
            },
            {                                                           
                "connection_class": "local_poll",                
                "data": {                                      
                    "collection_days": [                       
                        "mon"                                  
                    ],                                                  
                    "date_format": "%d-%b-%Y",                   
                    "first_month": "jan",                      
                    "frequency": "even-weeks",   
                    "holiday_in_week_move": false,             
                    "icon_normal": "mdi:pine-tree",
                    "icon_today": "mdi:calendar-check",
                    "icon_tomorrow": "mdi:calendar-arrow-right",
                    "last_month": "dec",                        
                    "observed": true,                           
                    "unique_id": "53a90107-3d4c-4d8b-9339-e2775b9c6efc",
                    "verbose_format": "on {date}, in {days} days"       
                },                                                      
                "domain": "garbage_collection",                         
                "entry_id": "bb44f1daee574e2687eb2086e502b91b",         
                "options": {},                                          
                "source": "user",                                       
                "system_options": {                                     
                    "disable_new_entities": false                       
                },                                                      
                "title": "Landscape",                                   
                "unique_id": null,                                      
                "version": 1                                            
            }
```

**Error log/debug information**

Nothing obviously wrong in the logs.
```txt

```

**Screenshots**

**Version**

Integration version: 3.01, installed through HACS

Home Assistant version: 0.112.2

**Comment by bruxy70** [comment]
Thanks for finding the bug. 11th should not show both. It is 2nd week of the month, so it should only show Landscape.
The fact that they "switch" after that is correct though. Look at the calendar - 1st week is after 53rd, so there are 2 odd week number one after the other, that is normal. If you want to switch every 14 days, regardless of the week number, then use frequency every-n-days.
![image](https://user-images.githubusercontent.com/44951610/86573691-0984d300-bf75-11ea-8fd3-b6d9a520630a.png)

**Comment by bruxy70** [comment]
You can check it in 3.02-beta

**Comment by rccoleman** [comment]
You’re right about the even/odd weeks - sorry about that. Many experiments late at night.

I’m still truly to puzzle through how to make a ‘continuous’ schedule that seamlessly transitions from year to year work.  Setting it up as ‘every-n-weeks’ with recycling starting on week 1 and landscape starting on week lines the days up properly for this year (today is a landscape day), but then I end up with this in Dec/Jan 2021:

![2C03BC64-47CB-43A9-977A-8DA0F11C91B5](https://user-images.githubusercontent.com/860888/86603232-98372700-bf58-11ea-90fe-be6b322ec569.png)

**Comment by bruxy70** [comment]
As I said "If you want to switch every 14 days, regardless of the week number, then use frequency every-n-days." So you basically pick a date, and it will repeat 14 days from that date.

There is an international standard for week numbers, what I use is that - https://en.wikipedia.org/wiki/ISO_week_date. There are many other variants used by some countries, but I will not support configuring that, most people would not know how to do that anyhow.

**Comment by rccoleman** [comment]
Indeed, every 14 days works exactly as I expect. Thanks for your work on this!
