### ISSUE TITLE
New feature for friendly_name??

### ISSUE THREAD

**Issue by k1asa** [bruxy70/Garbage-Collection#18]
Hi, Awesome work, thanks a lot !!

I live in Japan.
I set Japanese name(2-byte font) by 'friendly_name' each sensors/switch.
Could you plz support 'friendly_name' ?

**Comment by bruxy70** [comment]
What happens if you enter your 'friendly name' in the name attribute? I am a bit confused by the difference between the friendly name and name, my current understanding is, that it is essentially the same thing - in the past we used to have mandatory entity_id and optional friendly name, but as the config slowly moves from yaml, we do not set entity_id manually and the friendly name is just the name. But I might be wrong...

**Comment by k1asa** [comment]
Thanks to reply, bruxy70.
I'll try to explain why I want friendly_name id.

When I enter the Japanese language into a name of entity like below,
>     - platform: garbage_collection
>       name: '金属ごみ'
>       frequency: "weekly"
>       verbose_state: true
>       collection_days: "sat"

However, the word "金属" is automatically changed into a chinese language transribe.
Like this,
> sensor.jin_shu_gomi
("jin_shu" is Chinese and "ごみ" is Japanese.)

the word above is nothing to mean for Japanese people.

So,I expect the name of entity is only alphanumeric.
In most cases, HA changes KANJI into a chinese transribe.

If it's adopted a friendly_name,I think it will be solved this issue.
For exmple;
>     - platform: garbage_collection
>       name: garbage_burnable
>       friendly_name: '可燃ゴミ'
>       verbose_state: true
>       frequency: "weekly"
>       collection_days: 
>       - mon
>       - thu
>
>     - platform: garbage_collection
>       name: garbage_mixpaper
>       friendly_name: 'ミックスペーパー'
>       verbose_state: true
>       frequency: "weekly"
>       collection_days: "sat"
>     
>     - platform: garbage_collection
>       name: garbage_metal
>       friendly_name: '小物金属/粗大'
>       frequency: "weekly"
>       verbose_state: true
>       collection_days: "sat"

**Comment by bruxy70** [comment]
Ok, get it. But what you describe is, you want to manually define the `entity_id`, not the `friendly_name`.

The `name` or (`friendly name`) is what Home Assistant displays on the screen. `name` and `friendly_name` is the same thing.  I think `name` is used recently as it is shorter.  If you look in the sensor attributes, you will see. I have tried to define both, but it does not do anything, it just overwrites itself with what is in `name`.

`sensor.jin_shu_gomi` is entity id. It is generated automatically. It is not shown anywhere for the user, it is internal to HA - why is it an issue?

**Comment by k1asa** [comment]
Ok. I got it, too.
I'll wait for you code the way to change the entity_id.
Thanks.

**Comment by bruxy70** [comment]
After some research, I decided to come up with a quick fix, that should solve your issue. I think I might be breaking the rules a bit, so I will keep looking at better solutions. But it should do the trick. After you update to v1.14, you can go to Configuration/Entity Registry and change the entity_id. Let me know if it worked.

**Comment by bruxy70** [comment]
@k1asa, I just made a new release with the permanent solution for your request. This will be a breaking change for you. Please review the release notes. In your case I think you should move the configuration from YAML to the GUI config from the Integrations page.
