### ISSUE TITLE
Not recognizing US holidays 

### ISSUE THREAD

**Issue by PrayerfulDrop** [bruxy70/Garbage-Collection#195]
The latest update is not recognizing US based holidays. This past Monday was Labor Day. Trash pickup is usually Thursdays. It did not advance a day. Screen shots below. 

![740E587D-8594-4EF3-813A-791CB11851B1](https://user-images.githubusercontent.com/999665/92539965-bba47980-f208-11ea-8c5a-a273ab7e745e.jpeg)

![985B8E45-542F-44AD-9F9F-AC4B81F4F591](https://user-images.githubusercontent.com/999665/92539986-d4ad2a80-f208-11ea-930f-c5050e7f42d5.png)

![28279AD9-FABC-4901-8780-E96C53B4808F](https://user-images.githubusercontent.com/999665/92539990-d971de80-f208-11ea-986b-ae2fb8494a33.jpeg)

![991764A1-75E2-4537-A5C6-ED28DAC2665F](https://user-images.githubusercontent.com/999665/92539999-decf2900-f208-11ea-8d9f-7ccb62fff6f7.jpeg)

**Comment by patdemko** [comment]
I'm seeing this issue as well.  BTW, I just installed this integration this past weekend and it was factoring in the labor day holiday when I first installed it.  I think I updated it at least once if not more since then so maybe one of the updates changed something?

**Comment by bruxy70** [comment]
Can you guys check the 3.06 version? It should fix it - hopefully before you pull your trash out a day earlier :).

**Comment by bruxy70** [comment]
@patdemko , the issue was that the integration was loading the holdays from today onwards. So on the weekend, it calculated properly, but from Tuesday it stopped seeing the holiday. Thanks for the catch @PrayerfulDrop

**Comment by PrayerfulDrop** [comment]
@bruxy70 that fixed it!  Great job!!

**Comment by patdemko** [comment]
> @patdemko , the issue was that the integration was loading the holdays from today onwards. So on the weekend, it calculated properly, but from Tuesday it stopped seeing the holiday. Thanks for the catch @PrayerfulDrop

Yeah, that fixed my issue as well.  Thanks for the very fast fix!
