### ISSUE TITLE
Holiday Offset

### ISSUE THREAD

**Issue by nmsousa76** [bruxy70/Garbage-Collection#198]
Holiday offset seems not not be working correctly.  It is fine up  to day of trash pickup.  On trash pickup day, rather than saying "today" it says for next week.   

ie

My normal trash day is Wednesday (moved to Thursday due to Holiday).  Prior to Thursday, Date collection date was accurate.  But on Thursday rather than displaying "Today", it was displaying "on xx/xx/xx, in 6 days"

![2020-09-10 10_06_38-Configuration - Home Assistant](https://user-images.githubusercontent.com/65356035/92742229-7047b380-f34d-11ea-8086-2ac80dd731a6.png)

**Comment by bruxy70** [comment]
Please try the 3.07-beta, I have done a change that should skip back if there is a holiday in week move. This feature really messed up many things :(.

**Comment by bruxy70** [comment]
I made another change (beta2). I wonder if that fixes that.
