### ISSUE TITLE
Garbage - expire after not being respected when holiday happens in week

### ISSUE THREAD

**Issue by PrayerfulDrop** [bruxy70/Garbage-Collection#199]
As you can see below the settings state to reset the garbage day after the 22:00 hour.  It is 08:00 currently and the Garbage indicator has reset for the next pickup date.

![image](https://user-images.githubusercontent.com/999665/92996360-9b0e4500-f4d0-11ea-981d-29168cb67d34.png)

![image](https://user-images.githubusercontent.com/999665/92996372-a8c3ca80-f4d0-11ea-9fb4-d7c1ae1c47d5.png)

**Comment by bruxy70** [comment]
Can you please tell me what is the rest of the configuration, and what version do you use? Could it be related to #198? Have you tried the beta?

**Comment by PrayerfulDrop** [comment]
I just upgraded to your latest beta version and it still has the same issues.  The number of collection days should be zero until 22:00 tonight when it should reset.  Looks like you are not taking into account the holiday with the reset time.

Configuration below:
![image](https://user-images.githubusercontent.com/999665/92997708-cbf37780-f4da-11ea-9fd0-608c2e17ffe2.png)
![image](https://user-images.githubusercontent.com/999665/92997717-d877d000-f4da-11ea-9c2b-7754bdb92825.png)
![image](https://user-images.githubusercontent.com/999665/92997726-e299ce80-f4da-11ea-995f-c182001c988b.png)
![image](https://user-images.githubusercontent.com/999665/92997742-fa715280-f4da-11ea-9a42-cce24f86f87c.png)

**Comment by bruxy70** [comment]
I believe it is the same issue as #198. I made another change (beta2). I wonder if that fixes that.
