### ISSUE TITLE
transform component into generic reminder

### ISSUE THREAD

**Issue by thundergreen** [bruxy70/Garbage-Collection#20]
I love this component and this idea. I was just wondering why not turning this into a more generic component. Because I miss strongly the annual events (Yes I am talking about birthday dates :P). Would that be possible somehow with the actual state of this component?

**Comment by bruxy70** [comment]
Thanks for the suggestion. I will look at this. I am thinking to restructure the configuration to make it simpler, so I'll take it as part of that.

**Comment by thundergreen** [comment]
@bruxy70 That sounds promising :) Because the app already inpires me to use it for more than garbage and it would be just a pity to limit its capacities :) It might be an offical component one day dor hoe assistant as we don't have thse great featue yet

**Comment by bruxy70** [comment]
@thundergreen, it is included in the new release. This is a breaking change, please review the release notes for instructions.

**Comment by thundergreen** [comment]
Hi @bruxy70 I really appreciate your component... I now have a small "problem" .... I added my wife*s birthday and it appears in "Garbage Collection" :P well... the WAF fell down to zero :P Would you mind to rename this awesome custom component into maybe something like "Event planner" "generic Event Planner" ? but your integration is reallllyyy mega cool! Thanks a lot!
