### ISSUE TITLE
Did .115 break this integration?

### ISSUE THREAD

**Issue by mattclair** [bruxy70/Garbage-Collection#200]
**Write your question here**
Is this integration broken on .115?  
After installing 0.115 the garbage-collection integration is no longer working. The error from the log is below.

Setup failed for garbage_collection: Requirements for garbage_collection not found: ['typing'].

**Comment by bruxy70** [comment]
Do you use the latest version?

**Comment by mattclair** [comment]
Latest version does work.  Thanks.
