### ISSUE TITLE
Start and end date-time should not be the same

### ISSUE THREAD

**Issue by Pirol62** [bruxy70/Garbage-Collection#208]
**Is your feature request related to a problem? Please describe.**

Hi, I use a calendar card in order to display the incoming garbage events.
The problem is, that the card alculates the day before as part of the incoming event:
![image](https://user-images.githubusercontent.com/48820003/98934823-ed74dd80-24e2-11eb-8638-7115e1b845aa.png)

The calendar entity looks like this:
![image](https://user-images.githubusercontent.com/48820003/98916126-0ffafc80-24cb-11eb-9149-1196b1b40380.png)
That causes problems because there is no timeframe to display, where this date is active.
For example, the holiday calendar looks like this:
![image](https://user-images.githubusercontent.com/48820003/98916322-54869800-24cb-11eb-9683-0e9610b9819d.png)

I would propose, to set the start and end time of a garbage collection event so that a timeframe can be calculated out of that.

**Describe alternatives you've considered**

**Additional context**

**Comment by Pirol62** [comment]
Additional proposal:
There is expire_after option available.
The end time shoud simply be : date + expire_after
If not set then it is date and 00:00:00

Start_time should be always active date + 00:00:00

**Comment by bruxy70** [comment]
Included in 3.09. Check it out. Thanks for bringing that up. I did not know the all day events needed to have the end date on the next day. Does not seem very logical, I'd expect it would then make all day event for both days. Anyhow, it will work hopefully. And when there is expiration time, I do not create whole day events but regular events with start and end time.

**Comment by Pirol62** [comment]
Already updated. Works fine.
I agree, it is not really logical but now the data, the calendar card obviously need.
Thanks a lot!!
