### ISSUE TITLE
Config Flow can't ignore holidays

### ISSUE THREAD

**Issue by broyuken** [bruxy70/Garbage-Collection#209]
**Describe the bug**

I cannot choose holidays to ignore when setup via config flow. There is no place to input the holiday_pop_named parameter.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 
Config Flow

**Version**

Integration version: 3.07

Home Assistant version: 0.117.6

**Comment by bruxy70** [comment]
Hoe about here? 
![image](https://user-images.githubusercontent.com/44951610/99901598-01c19300-2cb8-11eb-9ca1-e2087cbd846a.png)

**Comment by broyuken** [comment]
Where are those options? I only have this 
![523DAAB0-22A8-4256-9237-1975AE020AA6](https://user-images.githubusercontent.com/1593391/99904799-56a2e080-2c9b-11eb-913d-b2ed824998d2.png)

**Comment by bruxy70** [comment]
On the 3rd page. Hit submit, it will show second page.

**Comment by broyuken** [comment]
Wow, I feel dumb haha. Thank you!
