### ISSUE TITLE
Offset and Holidays

### ISSUE THREAD

**Issue by charliesoap4** [bruxy70/Garbage-Collection#217]
The offset is taking place after checking for holidays instead of before.  I needed to offset it a week because it was happening on the wrong off-weeks.  However, it checks to see if it's on a holiday, moves to the next day, and THEN offsets by 7.  It should follow the offset first.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : YAML

- name: "Recycling"      
  frequency: "every-n-weeks"
  period: 2
  offset: 7
  collection_days: "thu"
  expire_after: "07:00"
  move_country_holidays: "US"
  holiday_in_week_move: "true"
  state: "nc"

```

**Error log/debug information**
<!--Copy the error message from Developer tools/Logs below.
    To enable debug logging, add `custom_components.garbage_collection: debug` 
    to your config under logger/logs.-->

```txt

```

**Screenshots**

**Version**

Integration version:  3.10

Home Assistant version: 2020.12.0

**Comment by bruxy70** [comment]
Please check 3.11-beta2. This should fix the issue. Hopefully, it won't break thinks. It got quite complex with all the offsets and holiday moves.

**Comment by bruxy70** [comment]
Once more, can you please check 3.12 beta? I did rewrite of the whole procedure. So far, tests look good, but I do not have any holiday offsets to check. Thanks.
