### ISSUE TITLE
List of Holidays

### ISSUE THREAD

**Issue by PrayerfulDrop** [bruxy70/Garbage-Collection#219]
I cannot seem to exclude Martin Luther King Day, Valentine's Day and Presidents' Day from the list of holidays that should be excluded.  All other holidays that I put into the "Ignore holidays (list) - optional" such as "Columbus Day","Veteran's Day" work without any issues.  But when I put the following list: "Columbus Day","Veteran's Day","Presidents' Day","Martin Luther King Day","Valentine's Day" then MLK, V-Day and President' Day are not respected and in turn move the holiday out a day for that week.

It would be great to see a list of holidays being reported by Garbage-Collection in the Options screen within Integrations->Garbage Collection->Options->Page 3.  Place under the "Move to next day if holiday in week (optional)" an option to dynamically list all of the holidays Garbage Collection is referencing.  The holiday names Garbage-Collection is acquiring appears to be different than what google or outlook show as valid holiday names.

![image](https://user-images.githubusercontent.com/999665/102818603-95f64700-4397-11eb-86a3-08efe0170fff.png)
![image](https://user-images.githubusercontent.com/999665/102818615-9db5eb80-4397-11eb-9f0b-85beaca69dad.png)
![image](https://user-images.githubusercontent.com/999665/102818578-870f9480-4397-11eb-89b9-1c60da74179b.png)
![image](https://user-images.githubusercontent.com/999665/102818549-77904b80-4397-11eb-83bd-89ccd1aa1f67.png)

**Comment by bruxy70** [comment]
I have no way of doing that I am afraid. The config flow is using a HA functionality that does not give me a way to interact with the screen until you submit it. And it won't fit to the screen I am afraid. 
You could check the list of holidays on the debug log. But I understand this is not user friendly. So what I did is, I added the list of holidays as an attribute to the sensor. So if you install 6.12-beta2, then you can check the sensor attributes. It will list the holidays for the current year, the year before and after.

**Comment by PrayerfulDrop** [comment]
That makes sense. I just updated and looking in the attributes of the sensor I can see why I would have never found the other dates as they don’t match. Much appreciated for this visibility!

**Comment by PrayerfulDrop** [comment]
Closing
