### ISSUE TITLE
'custom:garbage-collection-card' no longer working

### ISSUE THREAD

**Issue by caddyblack** [bruxy70/Garbage-Collection#22]
With the change to version 2.0 the custom card "garbage-collection-card'does not show the icon nor the days. Only the text  IN DAYS  is visible. 
Anyone a clue what to change?
Example single card that was working in previous version of garbage-collection:
entity: sensor.papier
hide_before: 7
hide_date: false
icon_color: grey
icon_size: 35px
type: 'custom:garbage-collection-card'

![image](https://user-images.githubusercontent.com/48408773/67127976-c0c89680-f1fa-11e9-861a-03e462bed995.png)

(Sorry if I am off-topic with my question)

**Comment by bruxy70** [comment]
This should not change. Please check the sensor, if it has the same entity_id. Did you remove the old entity from the entity registry? If not, please check the release notes.

**Comment by caddyblack** [comment]
Thanks, you are right. The sensors were re-numbered by the system. Sensor.plastic became sensor.plastic_2
