### ISSUE TITLE
Every-n-weeks breaks on year end (bi-weekly)

### ISSUE THREAD

**Issue by B0ndo2** [bruxy70/Garbage-Collection#223]
I am trying to setup garbage and recycling collection every 2 weeks (they alternate). My next garbage collection is on Thursday 31 December so the next recycling is on the 7th of January 2021. I created the following 2 configurations and they both do the same wrong calculation:

garbage_collection:
  sensors:
  - name: "garbage" # Every 2 weeks on Thursday.
    frequency: "even-weeks"
    collection_days: "thu"
  - name: "recycling" # Bi-weekly (odd weeks) on Thursday.
    frequency: "odd-weeks"
    collection_days: "thu"

garbage_collection:
  sensors:
  - name: "garbage" # Each 2 weeks on Thursday.
    frequency: "every-n-weeks"
    collection_days: "thu"
    period: 2
    first_week: 2
  - name: "recycling" # Bi-weekly (odd weeks) on Thursday.
    frequency: "every-n-weeks"
    collection_days: "thu"
    period: 2
    first_week: 1

**Result for both**
Recycling on 31 Dec  - - Correct (in the calendar recycling repeats on the 7th of Jan)
Garbage on 14 Jan - - Wrong, expected 7 Jan

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

```yaml

```

**Error log/debug information**

```txt

```

**Screenshots**

**Version**

Integration version: 

Home Assistant version:

**Comment by bruxy70** [comment]
This is how it is supposed to work both these work based on a week number. Read the documentation. Use every n days.

**Comment by B0ndo2** [comment]
I was able to do it based on the n days but n weeks in not clear in the docs
