### ISSUE TITLE
Something is wrong with my next Recycling Pickup date

### ISSUE THREAD

**Issue by danielbrunt57** [bruxy70/Garbage-Collection#224]
**Describe the bug**
Something is wrong with my next Recycling Pickup date.  
It is on Thursdays except if there is a holiday in the week _**on or before**_ the day of the pickup.  
Holidays **after** the day of pickup have no effect so next week should still be Thu Dec 31 here in BC, Canada.  
Stat holidays this month are Fri Dec 25 and next month Fri Jan 1 but Recycling Pickup is saying 02-Jan-2021, in 7 days

**Configuration**
Config Flow

```
            {
                "entry_id": "ed79fdfe21e859c329031e49c0167fd9",
                "version": 1,
                "domain": "garbage_collection",
                "title": "Recycling",
                "data": {
                    "unique_id": "209e7269-c8ce-400a-afe2-e1ddce9da2ac",
                    "frequency": "weekly",
                    "icon_normal": "mdi:recycle",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "expire_after": "09:00",
                    "verbose_state": true,
                    "verbose_format": "on {date}, in {days} days",
                    "date_format": "%d-%b-%Y",
                    "collection_days": [
                        "thu"
                    ],
                    "first_month": "jan",
                    "last_month": "dec",
                    "move_country_holidays": "CA",
                    "holiday_move_offset": 1,
                    "holiday_in_week_move": true,
                    "prov": "BC",
                    "observed": true
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_poll",
                "unique_id": null
            },
```

**Error log/debug information**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/49846893/103164016-b882c880-47ba-11eb-8bd6-04d735af5e7a.png)

**Version**
Integration version:  3.11
Home Assistant version: 2020.12.1

**Comment by bruxy70** [comment]
Can you try 6.12-beta4? I have done code refactoring as it was getting quite complex. I have tried the same parameters, and it gives Jan 1 (as the 31st is a public holiday)

**Comment by danielbrunt57** [comment]
Installed 6.12-beta4 and it shows a day earlier now but still not right...

![image](https://user-images.githubusercontent.com/49846893/103177217-4f886880-482d-11eb-9777-32a90a753507.png)

**Comment by bruxy70** [comment]
I think it actually worked correctly before (or what am I missing?), but it is actually broken in the beta - so great that you tested that!
The logic works the following: there is a public holiday on Monday 28th, and you configured to move if there is a holiday in the week.  The regular collection is on 31st, so it would move it by 1 day to the 1st. But the 1st is also a public holiday, so it should move it again to the 2nd. But the beta does not do the second move.

**Comment by bruxy70** [comment]
This is fixed in the latest beta. Please check it out. If that works, I will release it. Thanks!

**Comment by danielbrunt57** [comment]
I may have found my problem but not 100% sure. I added the Google Calendar integration and I think Dec 28 was being seen as a CA/Nunavut holiday?  I removed CA from the country holidays and left BC under Province.  I am hoping province: BC with country: null will work but will have to wait for the next occurrence of a BC holiday on a Monday which I think is Family Day in February?  Recycling now shows as Dec 31...
![image](https://user-images.githubusercontent.com/49846893/103178153-2cfa4d80-4835-11eb-80ea-e05097fff655.png)

I will load the new beta, revert my changes and test...

**Comment by bruxy70** [comment]
If you have the latest beta, you can also see the list of public holidays as the sensor attribute (e.g. in the developer tools).

**Comment by danielbrunt57** [comment]
Great, thanks!  That helps.   It lists Dec 28 as Boxing Day (observed).  For now I've excluded Boxing Day as the City of Richmond only bumps the holiday day-off-in-lieu if it is on a Sunday so this year this coming week is a normal work week for them.
![image](https://user-images.githubusercontent.com/49846893/103179281-44d6cf00-483f-11eb-80f8-a0a0c5ff3162.png)
Next year, Monday is a stat-day-off-in-lieu as Boxing day is Sunday...
![image](https://user-images.githubusercontent.com/49846893/103179354-fbd34a80-483f-11eb-85bd-62a4811625ee.png)
