### ISSUE TITLE
GUI configuration does not allow multiple dates for annual

### ISSUE THREAD

**Issue by Trefex** [bruxy70/Garbage-Collection#229]
As per the doc, it should be possible to add manually additional "include" days for the annual frequency.

However this is not possible via the integration GUI as it only allows to set a single day.

Would be great to be able to add additional dates, for non-periodic pick-ups, eg old clothes.

**Comment by bruxy70** [comment]
You are right. You can configure that in YAML, but I did not make this option available for yearly frequency.  It grew quite complex with all the options. Will fix it in the next release.
