### ISSUE TITLE
Feature request : Customizable date format and time setting for collect

### ISSUE THREAD

**Issue by olijouve** [bruxy70/Garbage-Collection#23]
Hello,

I think this 2 missing features could level up your integration.

- Would be nice if we could choose our own format for dates in a strftime syntax ("%d/%m") and also custom labels for today, tomorrow. It would allow us to deal with internationalization by setting our proper translation.

- Adding an optional time/hour of collect parameter would allow to know if the event is already passed or is to come.

**Comment by bruxy70** [comment]
Do you mean time format for the status, or for configuration? Initially, I only made the attribute next_date, so that people can format the date whatever they want, and the status was numeric, and you could easily render that to today/tomorrow. But then somebody asked to render it as text. HA does not have system-wide date/time setting, so I went for ISO standard format. I can add formatting option, but I really do not want to overcomplicate it.

**Comment by olijouve** [comment]
What I mean is about this text format in card : "on 22-Oct-2019, in 2 days", so i think it's time format for status.
I my case I use an horizontal card with 5 collect items and the text is shrinked as there not enough space to display it entirely.
All my UI is in french and those dates are fixed in english "on date, in n days", with new optional settings in strftime and string format syntax every one could choose how they want to display it.

For example:
garbage_collection:
  verbose_format:
    date = "le %d/%m"                                 => strftime
    remaining_days=", dans %d jour(s)"      => string formatting
    today = "aujourd'hui"
    tomorrow="demain"
  sensors:
    - name: "Poubelle"
       ...
    - name: "Recyclage"
      ...

or for more minimalist display:
garbage_collection:
  verbose_format:
    date = "%d/%m"  
    remaining_days=""                                 => empty string
    today = "aujourd'hui"
    tomorrow="demain"
sensors:
  ...

In this example you concatenate the two strings without caring about coma, prefix or parenthesis as it can be done in the format string and apply translation for Today and Tomorrow strings.

I think it would allow more flexibility for verbose_state usage if users choose to use this optional parameters. Could be a simple way to deal with internationalization to fit every user custom wish.

**Comment by bruxy70** [comment]
Understood, but format for remaining days would have to change based on the number. Like in czech, the plular form of "day" is different for numbers below and above 5 (and different for 1, but this is not an issue here). And if I want to make it to supportvlanguages in general, I'll have to implement some rules like this: https://unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html
So the config would be much more complicated than you suggest..

**Comment by bruxy70** [comment]
I am also thinking, if HA has a sensor with unit of measurement in days, would not it create a proper plural based on UI language setting? The format should be a parameter of language, not hard coded in a sensor....

**Comment by olijouve** [comment]
Now I understand better the complexity you were talking about, but wanting to manage plurals is like wanting to reach perfection, don't you think ?
About plural rules, i think babel python internationalization module already implements it :
http://babel.pocoo.org/en/latest/api/plural.html.
But indeed, plurals would make config more complicated...

So in your opinion, would the solution be rather on the side of custom card fitting my case by using next_date and days attributes ?

Anyway thanks for your time for this nice integration you offer to us.
And i like your last version, it's more proper way to configure sensors.

**Comment by bruxy70** [comment]
Yeah, and there is next version ready in the development branch, adding grouping of sensors ..:)
I am also thinking if I can somehow address this issue, but if I do that, I'd like to do it right. Also to avoid breaking changes in the future. And the config is already quite bloated, so I hesitate a bit to add too many new parameters.

I was checking on discord - there is support for localization (so today/tomorrow can be done this way). But not date format. So I might set the languages in localization, and only address the date format somehow....The language is set on UI - for example I have it in EN, my wife in CZ and my kids in FR. So if I do that, it would be nice if it is clean. Call it perfection if you think :).

**Comment by bruxy70** [comment]
Arguably, this belongs to the front end - if I do it on back end, wrong config will break HA (so it might not start). But anyhow let's try it, I will add a parameters to define the verbose format and date format, with defaults:
date_format: "%d-%b-%y"
verbose_format: "on {date}, in {days} days}"
The localisation of "today" and "tomorrow" is done by front end localisation - already implemented on the dev branch, so once released, it will be included.
Will be sailing next week, so I will jump to it when I get back.

**Comment by olijouve** [comment]
Hi,
date_format: "%d-%b-%y"
verbose_format: "on {date}, in {days} days}"

Seems perfect to me, thank you !
