### ISSUE TITLE
Version number jump?

### ISSUE THREAD

**Issue by mattlamb99** [bruxy70/Garbage-Collection#231]
Just a quick question about version number jump.
Did this go from 3.12 to 6.12?

```
Installed version: 3.11

Available version: 6.13
```

I haven't installed this update yet because it seemed wrong

Thanks!

**Comment by bruxy70** [comment]
Yes, it was not intended, it slipped through during beta testing. Damage done I guess, no point going back to 3.13 now, it would be even more confusing I suppose. I might do something like 2021.1 in the next release to get out of the jail :)

**Comment by mattlamb99** [comment]
Ah ok.  Thanks for the explanation!
