### ISSUE TITLE
Danish Translation

### ISSUE THREAD

**Issue by mpejstrup** [bruxy70/Garbage-Collection#234]
Hi

I also would like to contribute with a translation:
{
    "state": {
        "garbage_collection__schedule": {
            "today": "i dag",
            "tomorrow": "i morgen"
        }
    }
}

I have tried to fix it myself without luck. I can't get it to work. Rename the file to sensor.dk.json

Have restartet
Have done a Shift+F5
Have done a full cache refresh

**Comment by bruxy70** [comment]
Thanks. I added that to the translations. It will be included in the next release.
For your question - this translates the sensor state if you use verbose state.
If you use the custom garbage collection card, then this one uses a separate translation for some reason, so that will not work for that.

**Comment by mpejstrup** [comment]
Cool, thanks
I do use verbose state and only the sensor entity....
![2021-01-05_16h54_59](https://user-images.githubusercontent.com/55014016/103667879-c1bc2400-4f76-11eb-8c55-4a04a6ef8000.png)
              <ha-icon icon="mdi:recycle"></ha-icon> Genbrug afhentes {{ states('sensor.genbrug') }}<br>
              <ha-icon icon="mdi:trash-can-outline"></ha-icon> Affald afhentes {{ states('sensor.affald') }}
              <font color='#6a7377'>
![2021-01-05_16h55_28](https://user-images.githubusercontent.com/55014016/103667930-d3053080-4f76-11eb-8a3d-83eae57d8cdc.png)

**Comment by bruxy70** [comment]
I think the Jinja2 templates do not do translations. I think it kind of makes sense. The language is set in the user properties, not system properties. And the Jinja2 template is made for automations, that work on the back end, regardless of who is currently logged in the front end, or even if nobody is logged in. And you do not want your automations to stop working when you change your language settings. Or if you have multiple users with different language settings, what would the automation do?
You can typically tell if the translation is used by the first capital letter (even in English). The actual state should be with first letter in lower case. And the English translation normally capitalize the first letter.
So, if you press letter E, type the entity name (sensor.genbrug) and click on the sensor to get more info, it should display the state in Danish.
Or, even better - if you go to the Developer Tools, States and filter for the sensor, it should display the actual state (in English with lower case). But when you click on the (i) icon to show more info, it should display the translated entity.
So, to display the translated state, use a standard lovelace card.

**Comment by mpejstrup** [comment]
Hi again

Thanks for the explanation. And I see you already made a new update :)
But I can't get the sensor to translate still?
![2021-01-06_10h44_44](https://user-images.githubusercontent.com/55014016/103755038-77d24d00-500d-11eb-8492-e6a4f873a401.png)
![2021-01-06_10h44_38](https://user-images.githubusercontent.com/55014016/103755042-7a34a700-500d-11eb-9b8b-3dedf351a4bb.png)

Another question: When I only want to put in specific dates, which "frequency" should i use?
![2021-01-06_11h19_32](https://user-images.githubusercontent.com/55014016/103757430-0e543d80-5011-11eb-9507-27ad3bf630f1.png)

Lastly: Can I choose to have it display 0 and 1 instead of today and tomorrow?

**Comment by bruxy70** [comment]
Interesting. I have seen that before, and refreshing or clearing browser cache helped.
If you want specific dates, use annual frequency to add one date, and then add the other dates through include dates. Or perhaps a standard google calendar integration might be a better fit for that as it is easier to add such events.
If you do not use Verbose state, the state will be 0 for today, 1 for tomorrow and 2 for other cases. Or you can always create a template sensor based on the garbage sensor integration attributes (e.g. number of days).

**Comment by mpejstrup** [comment]
Thanks! That worked..
I'm not that good in templating, how would a template sensor look like, if it should look after 0 and name it "i dag"?
Thanks in advance and thanks for helping so far!

**Comment by bruxy70** [comment]
Simple. Do something like:
```yaml
sensor:
  - platform: template
    sensors:
      genbrug_verbose:
        friendly_name: "Something friendly"
        value_template: >-
          {% if states('sensor.genbrug') == '0' %}
            i dag
          {% else %}
            {{ states('sensor.genbrug') }}
          {% endif %}
```
I suggest testing the template in the Developer Tool / Template. Just copy and paste it there (just the value template part) and see what it does.

**Comment by mpejstrup** [comment]
Perfect! It works!

Thanks man

**Comment by mpejstrup** [comment]
Hi 
I just stay in this tread as I have encountered an issue with the config we discussed.
As you can see my next date is 3rd of Feb. and it says 2 days?
We have configured it as annually
![Uploading 2021-01-13_08h21_47.png…]()

**Comment by bruxy70** [comment]
I do not see the picture. If you look at the entities attributes `next_date` and `days`. Does it really say the next date is Feb 3 and days is 2? Or are you referring to the entity state? The entity state is not the number of days. It only has 3 states - 0 for today, 1 for tomorrow and 3 for everything else (this allows the use of state images in picture entity cards). For the number of days there is the `days` attribute.

**Comment by mpejstrup** [comment]
Does is work now?
![2021-01-13_08h21_47](https://user-images.githubusercontent.com/55014016/104423021-d18ec600-557d-11eb-9427-3ce9a827e1ae.png)

**Comment by mpejstrup** [comment]
Should it then not be 3?

**Comment by bruxy70** [comment]
Sorry typo. It has 3 states: 0, 1 and 2. 0 for today, 1 for tomorrow, 2 for everything else. I see that the `days` attribute correctly states `21`.

**Comment by bruxy70** [comment]
So if you want your template to show this, you need to change it to:
```yaml
sensor:
  - platform: template
    sensors:
      genbrug_verbose:
        friendly_name: "Something friendly"
        value_template: >-
          {% if states('sensor.genbrug') == '0' %}
            i dag
          {% else %}
            {{ state_attr('sensor.genbrug','daye') }}
          {% endif %}
```

**Comment by mpejstrup** [comment]
Works (y)
