### ISSUE TITLE
how to change config via integration?

### ISSUE THREAD

**Issue by jactora** [bruxy70/Garbage-Collection#237]
i have thi garbage installed via HACS
i have the setup done via integration 
for green bin and brown bin
until end of 2020, the bin was fine.
now in 2021, looks like bin skipped or changed dates.
the green bin is taking brown bin schedule and vice versa
how can i fix this?

**Comment by bruxy70** [comment]
I do not know what configuration you use, but I suppose you use even/odd weeks, or every-n-weeks.
I'd start by reading the documentation: https://github.com/bruxy70/Garbage-Collection#garbage-collection, the same thing further explained here: https://github.com/bruxy70/Garbage-Collection#parameters-for-collection-every-n-weeks
Then you need to update the configuration and change the frequency (either to use every-n-days or change the frequency from even to odd and vice versa. You can do that from Configuration/Integration - click on each integration, then on configure and there you can change the configuration dynamically, the change should be applied without the need to restart.

**Comment by jactora** [comment]
thanks for your help. got it sorted. it had reset in new year. hence it went off.
