### ISSUE TITLE
Request - Ability to Import Calendar

### ISSUE THREAD

**Issue by wraith1385** [bruxy70/Garbage-Collection#239]
My trash and recycling is stupidly complicated in that after a holiday they both move by a day, however while my recycling moves back to the usual day, my trash continues on the new day going forward.  

The city provides a calendar for trash pickup and I was wondering if we could have a way to import that for the sensor entities to use.

**Comment by bruxy70** [comment]
For this, I suggest using Google Calendar integration. It gives you ultimate flexibility to import lists of dates, manage individual dates or make recurrent events. The garbage collection was really made for simple schedules that follow a simple rule. Gradually, I added a number of exceptions, that make it more complicated, defeating the initial idea - and I think it went too far already - I do not plan to continue in this direction.

**Comment by bruxy70** [comment]
Will be made possible by #287
