### ISSUE TITLE
"Expire after" does not work for groups

### ISSUE THREAD

**Issue by Kurisutian** [bruxy70/Garbage-Collection#244]
**Describe the bug**
I created a group containing 2 sensors. This group has a Expire after time set but while non-group sensors will disappear at the time set, the group remains visible, ignoring the time to expire. 

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : Config Flow

**Version**

Integration version: 3.15

Home Assistant version: 2021.1.4

**Comment by bruxy70** [comment]
This should be fixed in 3.16-beta
