### ISSUE TITLE
name_template  showing as -

### ISSUE THREAD

**Issue by ionuttimofte53** [bruxy70/Garbage-Collection#245]
hello, thanks for the add-on, really what i was looking for. 
i have a problem with the card templater, using the same one. this is my config:

type: 'custom:card-templater'
card:
  type: picture-entity
  name_template: '{{ states.sensor.gft.attributes.days }} days'
  show_name: true
  show_state: true
  entity: sensor.gft
  state_image:
    '0': /local/containers/bio_today.png
    '1': /local/containers/bio_tomorrow.png
    '2': /local/containers/bio_off.png
  entities:
    - sensor.gft
the problem is that the name on the card is not displayed, just - 
https://imgur.com/a/dcPB8Ql 

see anything not in order in the caarad? its made in UI. name_template gives a correct name 6 days as an example, when tested in templates.

**Comment by bruxy70** [comment]
DId you try the expression `states.sensor.gft.attributes.days` in developer tools? I prefer using state_attr('entity_id','attribute_name')

**Comment by ionuttimofte53** [comment]
yes, i mentioned that. gives back days left. i went a step further, created a sensor.gft_days, wich gives me days left until pickup. that one also works in template testing. same result..... i think i copy pasted your code from the video or here, it was like this.

**Comment by bruxy70** [comment]
Rikgt, sorry, overlooked that. I am not really an expert in card-templater, perhaps you can try there. But I use this personally and it works fine 
![image](https://user-images.githubusercontent.com/44951610/105606596-b2bcda80-5d9a-11eb-89f2-817e2f6a9ed7.png)
![image](https://user-images.githubusercontent.com/44951610/105606606-bd776f80-5d9a-11eb-8284-1ac29881ce0c.png)
