### ISSUE TITLE
Holiday entry in flow when holiday contains comma and asterisk?

### ISSUE THREAD

**Issue by KairuByte** [bruxy70/Garbage-Collection#246]
I'm trying to figure out how to pop holidays with commas and asterisks? The docs say to surround the values and comma delimit, but that doesn't work at all for any holiday.

Next I tried single quotes and escaping the asterisk, but on submit the single quotes are removed.

Next I tried escaping the comma, but still not working.

So I'm out of ideas. How do I pop `Washington's Birthday, Susan B. Anthony Day` from the holiday list?

**Comment by bruxy70** [comment]
Sorry, can't replicate and test. Not sure what is your configuration. I have tried to configure it for US, but it does not show `Susan B. Anthony day`. 
![image](https://user-images.githubusercontent.com/44951610/106354775-7c301400-62f4-11eb-9346-c689b928cf38.png)

**Comment by KairuByte** [comment]
My instance just died on me, it's what I get for using cheap decades old SD cards. When the new card comes in, I'll see if I'm still running into the issue and report back. IIRC both holidays were on the same day, and I had simply selected US with no other holiday inputs.

**Comment by bruxy70** [comment]
Ok. I am passing the names to the `holidays` package as-is, there is no logic checking whether the holidays exist or not. So I'd just make sure you exclude something that actually exists. The list of identified holidays is in the entitie's `holidays` attribute.

**Comment by KairuByte** [comment]
Oddly, Washington's Birthday is now the only holiday being reported on that day. Not sure where Susan B. Anthony Day went but this is no longer an issue.
