### ISSUE TITLE
How to get to this: https://github.com/bruxy70/Garbage-Collection#with-images-picture-entity

### ISSUE THREAD

**Issue by peterc2609** [bruxy70/Garbage-Collection#247]
Hi there,

I can't work out how to get to this point with the multiple bins?

If I wanted 3 seperate bins, would I need 3 seperate configs?

Also, any way to just show the next bin to be collected?

i.e. "Recycling Bin this week" and not show any other bins till next week when its 'General Waste this week'

**Comment by bruxy70** [comment]
Yes, these are 5 separate entities - each with its own config.
You can use a garbage_collection integration with group frequency to combine multiple entities, it would pick the earliest date, but it will not show which of the bins that is. You can make own template sensor to do that, or do that with templating the Lovelace interface. It is possible, but quite a high level of customization - I generally try to stay away from these.
