### ISSUE TITLE
Format to enter list of exclude dates in the new Integration

### ISSUE THREAD

**Issue by ppmt** [bruxy70/Garbage-Collection#25]
Call me stupid but I can not work out how to enter a list of dates with the new integration method.

If I enter one date it works fine but can't work how to have more than one

Whatever I try I get 
Invalid date format!

**Comment by bruxy70** [comment]
2019-10-22,2019-10-23

**Comment by ppmt** [comment]
hum...how embarrassing. I thought I had tried that way but obviously not!

Thank you
