### ISSUE TITLE
Configuration none YAML stuggling to see how to setup my Days 

### ISSUE THREAD

**Issue by thorrrr** [bruxy70/Garbage-Collection#250]
HI quick query we have our bins emptied every Wed black bin then Wed after week after brown bin this is every Wed. 

But we have garden waste Mon every 3 weeks From March to Nov is this integration able to do this?

**Comment by bruxy70** [comment]
Yes.

**Comment by blueflame66** [comment]
Hello on a related question, I am assuming for different schedules you simply need multiple sensors.   I know the YAML configuration is being depreciated, so I want to follow the configuration flow.  After installing the integration, it creates one sensor.  The configuration flow does a good job in configuration of that sensor, but I cannot figure out how to get more sensors created using the configuration flow only...

**Comment by bruxy70** [comment]
Just add another Garbage Collection Integration. It will add it and group them....

**Comment by blueflame66** [comment]
Sorry I am still learning this.   If I try and reinstall, it simply overwrites the last install.  How do I get this to install *another* integration for Garbage Collection

**Comment by bruxy70** [comment]
- go to Configuration / Integrations
- hit the + ADD INTEGRATION
- select Garbage Collection

(the Garbage Collection has to be installed before that, e.g. through HACS)
