### ISSUE TITLE
Handle even days

### ISSUE THREAD

**Issue by fabioAnM** [bruxy70/Garbage-Collection#251]
Great job and good documentations but I can't find how to solve my case: garbage collection on wednesday but only on even days :-(
Can someone please help?
Tanks a lot

**Comment by bruxy70** [comment]
By even days, you mean when the date day is even? Like Feb 10, 12, 14, 16? I do not think that this integration does that.
Or did you mean even weeks? Like week number 6, 8, 10? For that just use the even weeks frequency, or every 14 days.

**Comment by fabioAnM** [comment]
Sorry for a not detailed description.
Unlucky the case is for even date like Feb 10, 12,   but I was prepared for a negative answer. 
Maybe it will come in a new release... ;-)
Thanks for your quick replay.

**Comment by fabioAnM** [comment]
SOLVED, using a workaround.
I report my job just in case someone is in need.

What a I was looking for was a way to have a reminder for the washing street days, that occur on wednesday but only on odd days.

I have add a new sensor in configuration.yaml: it check for a wednesday (date +%u return the day of week, 1 for monday to 7 for sunday) on an odd day of month ((date +%d) % 2) : 

sensor:
  - platform: command_line
    name: "Washing day"
    command: 'date +%u | grep "3" > /dev/null && (let a=($(date +%d)%2); echo $a | grep "1" > /dev/null && echo "wash" || echo "no wash") || echo "no wash"'



and a new automation that check the day and eventually send a message

alias: Street cleaning day
trigger:
  platform: time
  at: '00:00:01'


condition:
  - condition: state
    entity_id: sensor.washing_day
    state: "wash"


action:
  - service: persistent_notification.create
    data:
      title: "Street cleaning day"
      message: "Today is {{ now().strftime('%A %d %Y') }}, mercoledi dispari!"

  - service: notify.Telegram
    data:
      title: "Street cleaning day"
      message: "Today is {{ now().strftime('%A %d %Y') }}, mercoledi dispari!"


I've tried to format the code but results are poor :-(

**Comment by bruxy70** [comment]
Will be made possible by #287
