### ISSUE TITLE
Struggling with setting up a week based scheme

### ISSUE THREAD

**Issue by LinusT** [bruxy70/Garbage-Collection#256]
Hoping for some assistance on how to set this up, or where to inject an acceptable piece of code to fix it if needed.

My need is to setup a schedule as follows.
1) Every other Thursday
2) Between Week 17 and Week 47 every year  (Starting on Week 17)
3) Observing holidays as in moving to the next working day post a holiday

Can it be done? / TIA

**Comment by bruxy70** [comment]
Looks close to a standard `every-n-days` frequency, with a `period` 14 and a first date some date on Thursday. The start week and end week -  this is currently done month, not week. So if there are some issues at the edges, that would have to be tweaked manually through exclude dates. The holidays would work out of the box, moving it to a next day (Friday). I can see a possible issue that when there is a public holiday on Friday as well, it would tend to move it by another day - to Saturday, not Monday.

**Comment by LinusT** [comment]
Thanks bruxy70 that's about as far as I got. 
I can make a list of Thursday in April an November that are on or before week 16 but still in April and week 48+ but still in November for the next few years and leave it at that. (Where do I input that list in the UI though?)

...but the ex-programmer in me cringes.
