### ISSUE TITLE
Icon state color

### ISSUE THREAD

**Issue by jp-dorion** [bruxy70/Garbage-Collection#257]
Hi, got a small question for you guys

I'm pretty new with HA, I checked the box to color the icon depending on state, but nothing happens when the state changes, I'd like to set the state value to color itself when it's "today"

Do I have to modify it in lovelace directly, or in the costumization.yaml? 

Thanks for the help

**Comment by bruxy70** [comment]
Hi. I think that out of the box, HA only colorizes binary sensors (that turn on/off). And this one is not that.
So you have to either tweak it in Lovelace (I use a picture entity card for that, or you can play with the styles). Or use the custom garbage collection card mentioned in the readme.
