### ISSUE TITLE
Monthly schedule - nth day of month

### ISSUE THREAD

**Issue by rob51i03** [bruxy70/Garbage-Collection#259]
The README.md states it is possible to set up a monthly schedule on the `nth day of each month`, but it is not shown how this is done, and it does not appear to be possible using the Home Assistant Config Flow interface. For example, if the schedule must occur on Jan 1st, Feb 1st, Mar 1st etc how is this configured in Home Assistant?

[Note it is clear how to configure it if the requirement is for the "first Monday of each month". But how to do it for the "first calendar day of each month"?]

**Comment by bruxy70** [comment]
Ian. Sorry for the confusion, I have corrected the README. You can configure it for nth weekday of the month (or the weekday on nth week), but not for nth day. The whole integration has evolved around a garbage collection on a given day of the week, with a gradually increasing recurrence complexity. But it does not support what you ask for. I guess it can be done as a simple date template sensor or integration with Google calandar.

**Comment by bruxy70** [comment]
Will be made possible by #287
