### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'`

### ISSUE THREAD

**Issue by Spankythemusical** [bruxy70/Garbage-Collection#26]
HA Version: 0.100.2

Garbage Collection Version: v2.0

This has been working perfectly since release.  Updated and now all it shows on my Lovelace frontend is "Error!", and there are no sensors listed in the Dev States Screen.  This is the error shown in the log.

> Log Details (ERROR)
Tue Oct 22 2019 09:43:37 GMT+0100 (British Summer Time)
Error while setting up platform garbage_collection
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/garbage_collection/sensor.py", line 47, in async_setup_platform
    async_add_entities([GarbageCollection(hass, discovery_info)], True)
  File "/home/homeassistant/.homeassistant/custom_components/garbage_collection/sensor.py", line 89, in __init__
    self.__name = config.get(CONF_NAME)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by bruxy70** [comment]
It is configured through YAML, right? Please share the config. Thanks!

**Comment by Spankythemusical** [comment]
This is the config.  It has not been changed with the update.


`- platform: garbage_collection
  name: Bin Green
  frequency: "odd-weeks"
  collection_days:
  - thu
- platform: garbage_collection
  name: Bin Blue/Brown
  frequency: "even-weeks"
  collection_days:
  - thu
`

**Comment by bruxy70** [comment]
Please review the [release notes](https://github.com/bruxy70/Garbage-Collection/releases). 2.0 was a breaking change, you'll need to update the config:
```
garbage_collection:
  sensors:
  - name: Bin Green
    frequency: "odd-weeks"
    collection_days:
    - thu
  - name: Bin Blue/Brown
    frequency: "even-weeks"
    collection_days:
    - thu
```

**Comment by Spankythemusical** [comment]
I guess reading things would help.  Apologies for wasting your time on this.  I'll go sit in the corner of shame.  Thanks!
