### ISSUE TITLE
Homekit

### ISSUE THREAD

**Issue by smeg1** [bruxy70/Garbage-Collection#264]
**Is your feature request related to a problem? Please describe.**
not a  problem working great in HA, but would like to have it also in HomeKit

**Describe the solution you'd like**
added sensors to HomeKit to include but they are not seen in HomeKit

**Describe alternatives you've considered**
not sure what else I can try to get them into HomeKit maybe someone has it working

**Additional context**
thanks for all the great work on this been using for a long time and its a great help on a tablet in the kitchen everyone can see it.

**Comment by bruxy70** [comment]
I am sorry, I do not know anything about HomeKit Home Assistant integration, I do not use Apple. But if this is similar to Google Assistant, they define a set of devices they work with - mostly actuators to control lights, locks etc. The NabuCasa integration tries to map different entities to these devices.  Unlike Home Assistant, they are not an open platform where you can easily add custom devices. So even the support for things like temperature sensors is had to do. But perhaps Apple does a better job than Google. I'd check with the NabuCasa guys that develop the connector - I suppose they'd be on Discord.

**Comment by smeg1** [comment]
thanks for reply it is possible to add non apple certified devices to HomeKit which is what home assistant HomeKit add-on does as I have around 60 non certified devices, just trying to get garbage collection also will keep trying options many thanks
