### ISSUE TITLE
Calling garbage_collection.collect_garbage on annual frequency entities doesn't update all relevant attributes

### ISSUE THREAD

**Issue by rob51i03** [bruxy70/Garbage-Collection#266]
Calling garbage_collection.collect_garbage on annual frequency entities updates the **last_collection** attribute but does not update the **days** attribute nor the **next_date**:

```
next_date: '2021-05-01T00:00:00-04:00'
days: 0
last_collection: '2021-05-01T16:46:06.358185-04:00'
last_updated: '2021-05-01T00:00:53.436461-04:00'
holidays: ''
friendly_name: Molly Birthday
icon: 'mdi:cake'
device_class: garbage_collection__schedule
```

**Comment by rob51i03** [comment]
Still an issue! Not urgent, but it would be good to have a fix :)

**Comment by bruxy70** [comment]
I set up an annual frequency for April 1st, and I do not see any issue.
And since you did not include any configuration, I cannot replicate your error.
![image](https://user-images.githubusercontent.com/44951610/120510944-354d4a80-c3ca-11eb-8171-ea66bfdbfb5e.png)

**Comment by rob51i03** [comment]
Thanks for responding. Configuration as follows:
HA 2021.6.1
HACS 1.12.4
Garbage Collection 3.1.8

Steps to reproduce the problem:
1. In HA, create annual garbage collection event for current date. 
2. Go to Developer Tools > States and verify the states of the created entity, e.g.:
`
next_date: '2021-06-04T00:00:00-04:00'
days: 0
last_collection: '2021-06-04T18:51:10.027946-04:00'
last_updated: '2021-06-04T18:54:33.761580-04:00'
holidays: ''
friendly_name: Canada Day
icon: mdi:delete-restore
device_class: garbage_collection__schedule
`
3. Go to Developer Tools > Services, select "Garbage Collection: collect_garbage" service
4. Select newly created entity.
5. Click "Call Service"
6. Go to Developer Tools > States and verify the states of the dismissed entity: 
`
next_date: '2021-06-04T00:00:00-04:00'
days: 0
last_collection: '2021-06-04T18:56:27.729270-04:00'
last_updated: '2021-06-04T18:54:33.761580-04:00'
holidays: ''
friendly_name: Canada Day
icon: mdi:delete-restore
device_class: garbage_collection__schedule
`
Last collection has changed to the date and time the service was called. All other entity values remain unchanged.
Please let me know if you need any further info. Thanks!

**Comment by bruxy70** [comment]
Ok, that's something I can work with. Will check this week. Thanks.

**Comment by bruxy70** [comment]
Still trying to figure out why it does that. For some reason, it is forgetting the last collection date during the re-calculation. Not sure why. I guess something to do with the sequence in which HA updates the sensor and restores the attributes....

**Comment by bruxy70** [comment]
I think it should be fixed

**Comment by rob51i03** [comment]
Tested and confirmed fixed. Thank you so much for attending to this.
