### ISSUE TITLE
Home Assistant 100.1 missing text when using integration from frontend

### ISSUE THREAD

**Issue by Kranzy** [bruxy70/Garbage-Collection#27]
When adding the component through the integrations page there is no text showing.

Refer screenshots attached.

![image](https://user-images.githubusercontent.com/5820116/67348787-64ae9b00-f589-11e9-897f-64b2dc868074.png)
![image](https://user-images.githubusercontent.com/5820116/67348793-69734f00-f589-11e9-88af-cd0e3f1e5f41.png)
![image](https://user-images.githubusercontent.com/5820116/67348797-6d06d600-f589-11e9-8c78-0d9ed4677635.png)
![image](https://user-images.githubusercontent.com/5820116/67348806-709a5d00-f589-11e9-8726-5956af1c1318.png)

I was able to successfully add my sensors using the readme to know what options are where.

**Comment by bruxy70** [comment]
What version do you use? Is it a release or development branch?
What language do you use?
Thanks

**Comment by Kranzy** [comment]
v2.0 release version. Language is English.

I also spun up a dev server using 100.3 (release) and installed using HACS (v2.0 release) again in English with the same issue.

**Comment by bruxy70** [comment]
That is weird. It looks like it did not load the translations. I did have an issue last night, where I had an extra comma in the translation file, I did fix that this morning. But that was on the dev branch, the release is fine - I am testing on 2 systems, upgraded to the same HA version, it works. Can you please try to Reinstall the integration and restart? Thanks!

**Comment by Kranzy** [comment]
@bruxy70 I uninstalled and re-installed and its working as expected now.

This was on my dev environment HA 100.3. I am not using HACS on my live system yet but will leave it for the moment as Ill be replacing it shortly and the integration is setup and working.
