### ISSUE TITLE
Invalid date Thursday/4th week of month

### ISSUE THREAD

**Issue by tj57** [bruxy70/Garbage-Collection#271]
Scenario
- Current month is May 2021, first month day is Saturday
- Today is 22.05.2021
- Add integration:
 frequency: monthly
 select day: Thursday and select Order of week in a month instead of order of weekday
 select 4th week of month
 
I got sensor: 
next_date: '2021-06-24T00:00:00+02:00'
days: 33

It should be 27.05.2021

Integration version: 
3.18
Home Assistant version: 
2021.5.4

**Comment by bruxy70** [comment]
The sensor state is correct. Check your configuration.

**Comment by tj57** [comment]
Ok, my mistake, you can close this ticket.
