### ISSUE TITLE
Specific Time for state change

### ISSUE THREAD

**Issue by heffneil** [bruxy70/Garbage-Collection#275]
Perhaps I missed it but I would like to schedule the sensor to change at a specific time: 6 PM in my case.  Is that something that can be accomplished?  Currently, I get alerts from this sensor at midnight which is way too early or late depending on if it was the day before or the day of.

**Comment by bruxy70** [comment]
You can set up an automation triggered at 6pm, with the condition on garbage collection sensor state...
