### ISSUE TITLE
Date formatter does not use locale 

### ISSUE THREAD

**Issue by adamzimnyy** [bruxy70/Garbage-Collection#279]
Posting as a question, because I don't know if it's a bug or Home Assistants fault or something else.

`%A` should display day of week in user's locale, but it doesn't. It's in English. My browser language is polish, so is Home Assistant's language.

**Comment by bruxy70** [comment]
There is unfortunately nothing I can do about that. The localisation is done on front-end, not in the integration (the integration works in back-end, not specific to the user that is signed in, that also has the language defined). So I think this is a Home Assistant limitation.
