### ISSUE TITLE
Configuring holidays is difficult because I don't know what they all are

### ISSUE THREAD

**Issue by cgallred** [bruxy70/Garbage-Collection#281]
**Is your feature request related to a problem? Please describe.**

The integration requires that I enter a list of holidays to exclude. The problem is that I don't know what holidays might be on its list as they are not shown anywhere in the config UI flow.

**Describe the solution you'd like**

My waste collection company (in Washington state, USA) alters the collection schedule for only three holidays: New Year's Day, Thanksgiving, and Christmas. I would like to have the option to enter a list of holidays to _include_ instead of a the list to _exclude_. The exclusion list is longer and, since the list of known holidays is not visible, involves guesswork.

**Describe alternatives you've considered**

An alternative would be for the config flow to show the list of holidays that will be included so that I know the names of the ones to exclude.

**Comment by bruxy70** [comment]
The configuration is limited by what the Home Assistant Config Flow allows (if it did have a list with checkboxes to select the options, I could have used that, but they don't.  And by what is available in the holidays API (https://pypi.org/project/holidays/). They have a call for `pop`, but not the inverse call.
But you can do one of two things - when you set-up the integration, it creates a sensor that has the list of the holidays as an attribute, so you can check the names there and add it to the configuration. Or, if the holidays are always on the same date, you can use the exclude date feature, and just enter the dates.

**Comment by cgallred** [comment]
Thanks for the quick response!

I did end up looking at the sensor after setting things up and modified the configuration to omit all the holidays my waste collection company doesn't observe.

It looks like the holidays API does allow you to retrieve the list of holidays as strings:
```py
>>> for date, name in sorted(holidays.US(state='CA', years=2014).items()):
>>>     print(date, name)
2014-01-01 New Year's Day
2014-01-20 Martin Luther King Jr. Day
2014-02-15 Susan B. Anthony Day
2014-02-17 Washington's Birthday
2014-03-31 César Chávez Day
2014-05-26 Memorial Day
2014-07-04 Independence Day
2014-09-01 Labor Day
2014-10-13 Columbus Day
2014-11-11 Veterans Day
2014-11-27 Thanksgiving
2014-12-25 Christmas Day
```
Perhaps in the config screen you could just print the list of holidays that will be used. Then the user could at least copy/paste the ones that don't affect the collection schedule. It would help with the discoverability problem.

**Comment by bruxy70** [comment]
I thought about that too, but that would mean adding one more step to the configuration. And I think the configuration is already confusing, has too many steps, asks to submit each step, without saying that there are further steps, and does not allow moving back. So my primary goal is not to inflate it any further right now. I was hoping that the config flow will improve over the time as everybody moves from yaml, but I am not sure they will. I think the focus is on IoT devices - I think they generally consider a 'template' integration like mine kind of useless (got the impression when speaking to Ballob few months back). And the device configuration is generally much simpler.

**Comment by bruxy70** [comment]
This functionality will be changed in #287
