### ISSUE TITLE
How do you skip or dismiss the event if it fall on a public holiday?

### ISSUE THREAD

**Issue by francois-dotnet** [bruxy70/Garbage-Collection#282]
**I would like my scheduled event to be skipped rather than moved if it falls on a public holiday, how do I do this?**

It seems to be escaping me how to configure the sensor to skip (or omit if you will) the scheduled event if it falls on a public holiday. The next even should simply be the next scheduled event.

I am using the Integration UI to configure the add on.

Thanks

**Comment by bruxy70** [comment]
Will be made possible by #287
