### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by bkr1969** [bruxy70/Garbage-Collection#283]
**Describe the bug**

This integration simply does not work for me.  I installed via HACS and restarted.  It is in my list of integration under HACS but does not show up when trying to configure a new integration.  What am I missing?

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : Config Flow

```yaml

```

**Error log/debug information**

```txt

```

**Screenshots**

**Version**

Integration version: 

Home Assistant version: 2021.7.4

**Comment by bruxy70** [comment]
Not aute. It should show up. And it does not even show errors in the logs. Weird

**Comment by bkr1969** [comment]
The only thing in the logs is the standard warning that I'm "using a custom integration that hasn't been tested..."  The folder is there  under custom components, but I cannot get it to show up at all in the UI.  Do I need to do anything in the config file?

**Comment by bruxy70** [comment]
No configuration is required, it should be added to the integrations. I have verified that and it works here, so I can't replicate that, and if there is no error it is kind of hard for me to fix it. Sorry.
![image](https://user-images.githubusercontent.com/44951610/128768566-6d7fa057-9b77-4ad4-b261-49645f98ede3.png)

**Comment by bkr1969** [comment]
OK, that's weird.  If I just click on the "Add Integration" at the bottom corner, it doesn't show, but if I search integrations and click the add that comes up it works.  Super!
