### ISSUE TITLE
Holiday shift

### ISSUE THREAD

**Issue by bkr1969** [bruxy70/Garbage-Collection#286]
This is a terrific integration! it would be helpful to have some way of moving the pickup day based on the normal day and when the holiday falls, i.e:
My normal pickup day is Tuesday.  After a Monday or Tuesday holiday, the shift works fine, but if the holiday is Wed - Fri, I need to shift the following week's pickup day to Wednesday. Seems a bit of a programatic headache though.
Perhaps something like (forgive me, this is pseudo code):
if holiday is before pickup day in a week, move this week pickup day +1, if holiday is after pickup day in a week, move next week pickup day +1

So if the days of the week are assigned 1-7 (adjust for 0-6 if necessary), if 7 - pickup day > pickup day, new pickup day = pickup day + 1, otherwise pickup day += 8 

Without seeing the actual code, this is the best I can do.  :-)

**Comment by bruxy70** [comment]
I have to find another way to do that. There situation with holidays handling already got out of the hand a bit, it is quite unstable and there are some bugs I am not able to easily fix. And the configuration is quite complicated and confusing already. So I am not adding more exceptions to the holidays. You can either do that manually, or use a template sensor to do that. And I will keep thinking how to do the whole think differently - maybe generating the calendar up front and allow to modify that with some scripting....

**Comment by bkr1969** [comment]
I completely understand

**Comment by bruxy70** [comment]
Will be made possible by #287
