### ISSUE TITLE
Date GMT?

### ISSUE THREAD

**Issue by lockyt** [bruxy70/Garbage-Collection#29]
Hi bruxy70,

Thanks for the hard work on your garbage collection integration.  Just what I have been looking for. However I seem to be have a problem with it.  I installed it one evening last week and all seemed well with my normal bin and green waste being due on Friday.

However, when Friday morning came both bins said they were still 1 day away.  When the next morning came (today), they said they were 0 days away.  It seems the date is not lined up correctly.  Also, I calculated based on when it ticked over each day that it's 11 hours out.  I am in Australia and we are GMT + 11 here..  which makes me think perhaps it is calculating on GMT time not local time?

This is what the garbage collection is displaying:

<img width="493" alt="Screen Shot 2019-10-26 at 8 31 42 am" src="https://user-images.githubusercontent.com/45985740/67606272-7cc22c80-f7cc-11e9-8318-2480c0815b19.png">

This is what my HA is says is the current date and time:

<img width="366" alt="Screen Shot 2019-10-26 at 8 31 10 am" src="https://user-images.githubusercontent.com/45985740/67606217-556b5f80-f7cc-11e9-9574-c8974ccc2084.png">

Bin history and current status:

<img width="364" alt="Screen Shot 2019-10-26 at 8 54 29 am" src="https://user-images.githubusercontent.com/45985740/67606818-44235280-f7ce-11e9-8cfd-9497259a0b7f.png">

where you can see next date is in the past and that it changed at 11am.

Any help would be appreciated

**Comment by bruxy70** [comment]
Hi. Thanks for reporting that. I am out till the end of next week, will look at that when I get back.

**Comment by lockyt** [comment]
Yep no worries.  Talk then.

**Comment by bruxy70** [comment]
Would you like to download the development branch, copy it over the garbage_collection custom component and let me know if it works. I have changed the way it works with the dates, it should resolve it. If not, I will test it when I come back next week.

**Comment by lockyt** [comment]
Ok no worries will give it a go

**Comment by lockyt** [comment]
Hi @bruxy70 - I think I applied the development branch correctly but seems to have the same problem.  I cleared the browser cache and also tried adding a version on the end of the Garbage Collection .js reference (.js?v1) in the raw config view in Lovelace (not expecting it to work as that card appears separate from your integration - just to be sure).

I installed my version via HACS integration.  Do I need to delete and re-add the bins in HACS?

Was there anything I needed to do when re-installing it?

Thanks mate.

**Comment by lockyt** [comment]
I just tried adding another bin from the start in HACS as a test - same problem it seems.  Perhaps I applied the dev branch wrong being HACS instead of manually?  I presume the HACS install is just the same install in an automated front end?

I copied all the files in the dev branch to custom_components/garbage_collection/ including the hidden files/directory.

Thanks.

**Comment by bruxy70** [comment]
Ok, I will change my time zone to one in AU and test it. How to replicate it exactly? Does it happen in the morning, afternoon or whole day? Is it when the collection day is yesterday, today or tomorrow? Thanks

**Comment by lockyt** [comment]
Ok coolies.  Thanks for looking into this for me.

My bin day is Friday and when I look at it before 11am on Saturday, it still shows the bin at 0 days instead of the next bin of 6 days away.

I am Canberra time (same as Sydney/NSW time) which is GMT+11 at the moment (11 hours out) so if you look at the last image I posted above and go to the same and hover over, it should show you whether it changed at 11am or midnight like it should.  That is probably the easier way of looking at the issue.

Let me know if you need any more explanation.

Thanks!

**Comment by bruxy70** [comment]
I did not manage to change my timezone somehow (did change the timezone and location, but the time did not update). Anyhow. I have tried a different approach, I am now adding the timezone to all the attributes - previously it was using localtime. It is in release 2.2 - let me know if it works.

**Comment by bruxy70** [comment]
@lockyt , is it working now?

**Comment by lockyt** [comment]
@bruxy70 sorry but I don't think so.  I have been meaning to double check my configuration in  case I was doing something dumb before writing back but unfortunately haven't had the chance.  Will try double check tomorrow however

**Comment by lockyt** [comment]
hey @bruxy70 - checked again and it is still changing at 11am each day instead of midnight..

**Comment by bruxy70** [comment]
Right. @lockyt pushed a change, that is supposed to fix it. Would you like to download the development branch again and confirm it works? Thanks for your help!

**Comment by lockyt** [comment]
hey @bruxy70 - yep will give it a try but my HA has totally shat itself yesterday - can't get it to boot at all!  Not config, something more significant I think.  Something to do with HACS I think.

When I get it working again, I'll give it a go.

**Comment by lockyt** [comment]
Woohoo!  Looks like it's fixed.  I will double check near bin day (Friday my time) but it looks like everything is working as it should.

Let me know once you put it in hacs and I will update to the official version.

Thanks @bruxy70!

**Comment by bruxy70** [comment]
Fixed in the release 2.4. 
Thanks for you help and patience.
