### ISSUE TITLE
Icons have disappeared after 2021-11-Beta trial

### ISSUE THREAD

**Issue by grantclem** [bruxy70/Garbage-Collection#294]
**Describe the bug**

During the beta testing I have noticed the icons have disappeared from the UI. Nothing in the logs. Icons are still in available in HA.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

Config flow

![image](https://user-images.githubusercontent.com/30598978/139605798-233de3d1-faba-4806-b9c5-5952400ee803.png)

```yaml

```

**Error log/debug information**

```txt

```

**Screenshots**

![image](https://user-images.githubusercontent.com/30598978/139605911-7047f6e8-48dc-45d7-a169-c689dd459442.png)

**Version**

Integration version: 3.20

Home Assistant version:  2021.11.0b2

**Comment by bruxy70** [comment]
The integration has nothing to do with Icons. All it does is, it sets the state of the sensor. Then, you choose the card you want to show on your dashboard and that might display the value or picture or icons based on the sensor state. I do not know what card you used, but I'd check there.
If there is a problem with the state, let me know. The state should be 0, 1 or 2.

**Comment by grantclem** [comment]
Hi, thanks for the reply, this is what I have and has been working perfectly for quite some time. Will look into it more. Release is due this week, so it will be interesting if there are others with the same problem. Thanks

![image](https://user-images.githubusercontent.com/30598978/139633734-2f4a8c24-44bd-45ff-a301-b290c7a118ba.png)

![image](https://user-images.githubusercontent.com/30598978/139633800-12ffc4dd-5057-421d-a6f0-9b56f9fd5471.png)

**Comment by bruxy70** [comment]
Ok, I'd open the issue with amaximus https://github.com/amaximus/garbage-collection-card

**Comment by grantclem** [comment]
Thanks will do.
