### ISSUE TITLE
User input malformed

### ISSUE THREAD

**Issue by giantoo** [bruxy70/Garbage-Collection#296]
Hello,
After HA update, since 2021.11.3 (or maybe earlier), when I try modify Garbage Collection integration, I can't save it, because of the "User input malformed".  I know, that in another integration (HomeKit) people have same problem (https://community.home-assistant.io/t/homekit-error-user-input-malformed/353390/2). 
What's wrong? 
![bio](https://user-images.githubusercontent.com/16885189/142214286-2543452d-fe88-4ed6-b60a-7cc134f62d09.PNG)

Have a good day!

**Comment by bruxy70** [comment]
I did test the integration on version core-2021.11.4 and it works fine, no such error. I checked existing integrations and created new one - both worked.
