### ISSUE TITLE
How to clear saved collection for testing purposes?

### ISSUE THREAD

**Issue by NickM-27** [bruxy70/Garbage-Collection#298]
I have a sensor on the trashcan that, when vibration is detected, will automatically mark the trash as collected. I just set this up so I am still trying to fine-tune the behavior. This morning it ran at 3 am so I adjusted the automation and then deleted and recreated the garbage collection schedule. 

For some reason though, now it keeps being "collected" after a minute. I checked the logbook and no automations are being run and just shows it going from "today" to "in 7 days". Is there some caching that it does to automatically be collected since it was collected today already, even though I recreated the integration?

**Comment by NickM-27** [comment]
Okay when I check the state it shows collection as still being 3 this morning so it probably is that. Is there any way to clear that out?

**Comment by bruxy70** [comment]
You can call the service `garbage_collection.collect_garbage`, and it will consider it collected and go for the next scheduled collection. If you re-create the integration, it will re-calculate it and set it for today's date.
It uses the last collected attribute to determine if it was collected today already. There is no service to "uncollect" it once it has been collected I am afraid.

**Comment by NickM-27** [comment]
@bruxy70 thanks for the explanation. In that case I'll probably just create a separate bogus one to use for testing and delete it when I'm done.
