### ISSUE TITLE
changing Date Format

### ISSUE THREAD

**Issue by smith844** [bruxy70/Garbage-Collection#3]
Good evening, 
first of all thanks for your hard work, it saves me using scrape to get the information from a web page, as its a little more stable.

I am in the UK and trying to change the format of the output to day month year and thought I would be able to use a template such as:
"{{ as_timestamp(state_attr('sensor.waste', 'next_date')) | timestamp_custom('%a %d %b') }}"
or 
"{{ as_timestamp(states.sensor.waste.attributes.next_date) | timestamp_custom('%a %d %b')}}"
but when i run it all I get is 'none'
I am running right on the edge of my knowledge but wanted to check that the attribute output is a 'date' (timestamp) as I have used various template variations but am unable to extract the date to allow me to use it.

Thanks

**Comment by bruxy70** [comment]
Hi, Good to hear it is helpful. I did try to render it in the system locale format - did not realize it uses the Home Assistant OS locale setting, which might be hard to change. So will change it to date/time format so your template should work. Change is done, let me test it before I the release.

**Comment by bruxy70** [comment]
Changed in the release 1.5. This is a breaking change - the type attribute type changed from text to datetime - so if you want to display just the date, use template.

Closing the issue

**Comment by NielsFeenstra** [comment]
Thanks for the fast updates.

It was possible to change the date time with strptime.
{{ strptime(states.sensor.wasteattributes.next_date, "%m/%d/%y").timestamp() | timestamp_custom('%a %d %b') }}

But the new method is way easier.
