### ISSUE TITLE
New beta versio 3.21 with error

### ISSUE THREAD

**Issue by Marmoulak** [bruxy70/Garbage-Collection#300]
Hi
After installing the new version I get this Integration error: garbage_collection - Integration 'garbage_collection' not found. 
It worked perfectly. but now is not.

I have to uncomment this:
` garbage_collection:
   sensors:
     - name: Garbage 1  Every 2 weeks on Thursday, starting on 2th week each year
       frequency: "odd-weeks"
       frequency: "weekly"
       collection_days: "thu"
       include_dates:
         - "2021-07-22"
         - "2021-08-05"
         - "2021-08-19"
         - "2021-09-02"
         - "2021-09-16"
       last_month: "sep"
       period: 1
       first_week: 1`

Regard

**Comment by riddler2608** [comment]
Yes im having the same issue aswell.

**Comment by bruxy70** [comment]
This should be fixed. HA did not like the version number anymore, it works again.
