### ISSUE TITLE
move settings to new installation

### ISSUE THREAD

**Issue by SuperSpe** [bruxy70/Garbage-Collection#303]
Hi, how to move the setting to a fresh new installation?

my old hassio had a problem and wont boot but I have access to all the partition, I have restored few things....where I can find the settings of garbage collection?
thanks

**Comment by bruxy70** [comment]
If you configured that in YAML, you can just copy&paste this file. If this is done through config-flow, I think the only way is backup&restore, but that restores the whole config I am afraid. HA does not have a feature to export&import individual integrations I am afraid. 
Technically, it is stored in the .storage folder, in multiple files. but that is not meant to be edited, you could easily break the HA. This is why it is hidden.

**Comment by SuperSpe** [comment]
sad...I cannot backup because hassio wont boot and I don't have a recent backup...
