### ISSUE TITLE
Add year when used as birthday

### ISSUE THREAD

**Issue by Jese44** [bruxy70/Garbage-Collection#304]
Heu, great integration! I use it ro birthdays and other annuak holidays, i was wondering could it be possible to add year -field there, so integration would also return ones age?

**Comment by bruxy70** [comment]
Hi. What I struggle with is, that the configuration is already too complicated, so the goal is to simplify it, not to add more options. I think going forward I will even make some options obsolete and move the marginal scenarios to automation.
The integration purpose is to calculate patterns for garbage collection, that is often a bit more complicated than a fixed day in a year. I guess the day counter is the reason why people use it for birthdays, but there are other an easier ways to do that through templates (as simple as `{{ now().year - 2000 }}` for somebody born in 2000).

So I suggest calculating the age by a template as well.
