### ISSUE TITLE
Template variable error

### ISSUE THREAD

**Issue by tamimology** [bruxy70/Garbage-Collection#306]
**Describe the bug**
it is not really a bug, but an error that appears in the log every time I restart HA

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

YAML
  sensors:
  - name: "General Waste" # Each week on Sunday
    frequency: "weekly"
    collection_days: sun
    move_country_holidays: AU
    state: AU
    prov: VIC
  - name: "Recyclable Waste" # Every fortnight on Sunsday
    frequency: "every-n-weeks"
    collection_days: "sun"
    period: 2
    first_week: 1
    move_country_holidays: AU
    state: AU
    prov: VIC
  - name: "Garden Waste" # Every other fortnight on Sunsday
    frequency: "every-n-weeks"
    collection_days: "sun"
    period: 2
    first_week: 2
    move_country_holidays: AU
    state: AU
    prov: VIC

**Error log/debug information**

Logger: homeassistant.helpers.template
Source: helpers/template.py:1791
First occurred: 17:04:10 (585 occurrences)
Last logged: 17:04:18

Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.general_waste.attributes.days }} days'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.garden_waste.attributes.days }} days'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.recyclable_waste.attributes.days }} days'

**Screenshots**

**Version**

Integration version: 3.21

Home Assistant version: 2021.12.3 (docker)

**Comment by bruxy70** [comment]
Use the template `{{ state_attr('sensor.general_waste','days') }} days` etc instead.
see https://www.home-assistant.io/docs/configuration/templating/#states
