### ISSUE TITLE
Ad-hoc collection date?

### ISSUE THREAD

**Issue by craggus2000** [bruxy70/Garbage-Collection#307]
Here in the UK our collections are sometimes changed due to bank holidays, but not always by a set number of days. Is it possible to alter a particular collection date, or add in a single collection date?
Thanks

**Comment by bruxy70** [comment]
Yes, there is an option to exclude and include individual dates.

**Comment by craggus2000** [comment]
How do I do this please?

**Comment by bruxy70** [comment]
I'd start reading the documentation. Once you have that, just configure `include_dates` and/or `exclude_dates` (described here): https://github.com/bruxy70/Garbage-Collection#parameters-for-all-frequencies-except-annual-and-group. 

If you use the configuration GUI, just add the dates there.
