### ISSUE TITLE
"holiday_in_week_move" Question

### ISSUE THREAD

**Issue by vmcosco** [bruxy70/Garbage-Collection#308]
My garbage collection is every Thursday (easy enough).  If a holiday falls on a Monday, Tuesday, Wednesday or Thursday, my collection moves to Friday.  If the the holiday falls on Friday, Saturday or Sunday, it stays on Thursday.  

So my question is, how does the "in week move" work in my situation if a holiday falls on Fri, Sat or Sun?

**Comment by vmcosco** [comment]
Great.  Before or ON the scheduled date, I assume? I assume a Sunday holiday would cause an issue?  Is Sunday considered the start or end of the week or not considered since it is a weekend?

**Comment by bruxy70** [comment]
Yes, before or on of course. I think it uses Monday as a start of the week, at least here - it works with weekday numbers that start from Monday I think.
