### ISSUE TITLE
v2.1 Config Flow broken

### ISSUE THREAD

**Issue by michalszymura** [bruxy70/Garbage-Collection#31]
Version 2.1 breaks config flow integration
it doesn't create any entities
manual config in yaml works fine
Version 2.0 works fine

**Comment by bruxy70** [comment]
Does it give any error message? What HA version do you have? What parameters did you configure?
It works over here, I am trying to replicate that.
Thanks.
V

**Comment by michalszymura** [comment]
ON 2.1
no errors at all
HA: 0.101.2
i try by setting just a random name, weekly,  with one day selected
it just says:
Success!
Created config for xyz.
but no entity created

I can confirm that version 2.2 fixes the problem

**Comment by elRadix** [comment]
using v2.2 still getting an error using the config flow

Error setting up entry Blauwe zak for garbage_collection
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 190, in async_setup
    hass, self
  File "/home/homeassistant/.homeassistant/custom_components/garbage_collection/__init__.py", line 75, in async_setup_entry
    CC_STARTUP_VERSION.format(name=DOMAIN, version=VERSION, issue_link=ISSUE_URL)
NameError: name 'CC_STARTUP_VERSION' is not defined

**Comment by bruxy70** [comment]
Ok, this is good information, but I am really not sure why. The CC_STARTUP_VERSION is imported on `__init__.py` line 14 from integrationhelper.const, and the integrationhelper is included in the manifest.json requirements. So there should not be such error. How did you install the integration? If you did that manually, did you copy all the files?

**Comment by elRadix** [comment]
@bruxy70 just through HACS directly

**Comment by bruxy70** [comment]
That's weird. And you have restarted HA after the update I suppose.
Can you please check for me, if the file `config/custom_components/garbage_collection/manifest.json` contains   
```
"requirements": [
    "datetime",
    "integrationhelper",
    "typing",
    "uuid", 
    "voluptuous"
  ],
```
and `__init.py__`
`from integrationhelper.const import CC_STARTUP_VERSION` on line 14?
If not, try to re-install from HACS and restart HA?
