### ISSUE TITLE
Config UI: When reconfiguring, you have to re-edit fields that had entries added to them

### ISSUE THREAD

**Issue by danielbrunt57** [bruxy70/Garbage-Collection#311]
There's a bug in the config UI; you have to re-edit each field that had entries in them from before...

![image](https://user-images.githubusercontent.com/49846893/148466381-f81889af-ec95-496c-8e9e-b3b0170509cf.png)

**Comment by bruxy70** [comment]
4.0.3 should fix that?

**Comment by danielbrunt57** [comment]
Yes, installed and confirmed fixed. Thanks!
