### ISSUE TITLE
Slovenian translation

### ISSUE THREAD

**Issue by Protoncek** [bruxy70/Garbage-Collection#314]
Helo, guys!
Since i use this card with joy, i translated it to my local language.  Since i'm not skilled in github i don't know what to do to upload new files (two of them: sl.json and sensor.sl.json from translations folder), so some guidance would be nice. I can, say, send them to someone's email, too.

Thanks!

**Comment by bruxy70** [comment]
If you want to learn how to contribute to github (could be fun), then you can find some videos or blogs describing that. 
In a nutshell, you create a `fork` - that would basically make a snapshot of the project and make it your own repository.
Then you make the changes - typically you'd make a branch and you add or change the files and `commit` the changes.
And then you create a `pull request` to pull it back to the base repository. I'll be notified (similarly to how I got this question), I'll review that, confirm the merge and it will become part of the next release. And you'd be officially the contributor.

If this does not sound like fun, you can just upload them somewhere online (you can even create them as (GitHub Gists)[https://gist.github.com/] and send me the links, I will copy them over manually.

Thanks for your help.

**Comment by Protoncek** [comment]
Well, i did "something"... 
check out if it's ok...

**Comment by Protoncek** [comment]
I see that you already did the update...thanks!
in the meantime i wonder: are language files in folder www/community/garbage-collection-card now obsolete? I've had words "today" and "tomorrow" translated there, but i think that after last update they stopped working (that's why i digged into it and translated whole thing, not just those two words). I gues that you moved language files on new location with latest update, correct?

**Comment by bruxy70** [comment]
I do not think they are. The integration does not really deal with the front-end, so the translation is for the configuration. And in case you use verbose state for the today/tomorrow state.
But if you use the garbage collection card, that one has own localization for the front end and is maintained by @amaximus. And in such case I do not think you use the verbose state anyway.

**Comment by Protoncek** [comment]
Aha... i think that i "messed up" two different things: your integration and amaximus's custom card. Currently i don't use his card, but i rather use  "custom button card".  And i use verbose mode. 
Now it's all clear. Thanks!
