### ISSUE TITLE
Move On Holiday Blueprint holiday dates

### ISSUE THREAD

**Issue by aagrifo** [bruxy70/Garbage-Collection#324]
**Describe the bug**

When using the Move On Holiday blueprint (move_on_holiday.yaml) I get an error because the condition is attempting to compare a datetime to a string ( TypeError: 'in <string>' requires string as left operand, not datetime.datetime). It looks like this is because the holidays list has the names of the holidays next to the date in my configuration (e.g. _[2021-01-01: New Year's Day, 2021-05-31: Memorial Day, 2021-07-04: Independence Day, 2021-09-06: Labor Day]_). I'm not sure if the holidays list always outputs like this, but it does in my configuration.

I fixed this in my system by not converting the collection date to a date time (which may have other consequences but seems to have worked):
from: 
_value_template: '{%- set collection_date = as_datetime(trigger.event.data.collection_dates[repeat.index-1])%} {{ collection_date in state_attr(holiday_entity,''holidays'') }}'_ 
to: 
_value_template: '{%- set collection_date = trigger.event.data.collection_dates[repeat.index-1]%} {{ collection_date in state_attr(holiday_entity,''holidays'') }}'_ 

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? :  Config Flow

**Version**

Integration version: 4.3 (Holidays is 1.1)

Home Assistant version: 2021.12.10

**Comment by bruxy70** [comment]
You are right. Thanks! I fixed the blueprint. Well done-
