### ISSUE TITLE
Two weekly bin pickup - a holiday in each week leads to the pickup date moving twice. 

### ISSUE THREAD

**Issue by shadsnz** [bruxy70/Garbage-Collection#326]
Hi Folks,

How can I configure or change the "Move forward when Holiday in the week" blueprint automation so that it only moves the next date based on holiday(s) in the **preceding** week period (rather than two week period). 

My pickup is normally every two weeks on a Tuesday.  The next pickup date currently shows Thu 10th Feb instead of Wed 9th Feb.  I suspect this is due to there being a holidays in each of the two weeks prior (the first being Mon 31st Jan and the second being Mon 7th Feb).

Thanks

**Comment by bruxy70** [comment]
The blueprint should only look in the current week, not two weeks before. So if a collection is on Wednesday, it will check if a holiday is any time from Monday to Wednesday and if yes, it will move the collection to Thursday. Are you saying that it does not work that way? Or that you need it to work differently? I'd either fix it, or help you to come with own custom automation (or create a new blueprint...)

**Comment by shadsnz** [comment]
Thanks for replying.  Yes, I'm saying that it didn't seem to work that way.  Given it's supposed to work that way and its very rare to have two public holidays within a two week interval, I've just deleted the garbage collection integration that's not working and set it up again from scratch.  Thank you for the offer of help too.

**Comment by bruxy70** [comment]
@shadsnz , would you like to check #330? Is that what you had in mind? I just made another flavor of the blueprint. Does that do what you meant?

**Comment by shadsnz** [comment]
Thanks @bruxy70.  It's looking good now.  But I suspect it was my configuration as I may have had the provential holidays setting wrong on the collection that wasn't working . I'm very grateful for your efforts with this functionality - it's really effective and useful.  Thanks agian.
