### ISSUE TITLE
Cannot setup integration

### ISSUE THREAD

**Issue by tangix** [bruxy70/Garbage-Collection#327]
**Describe the bug**

Installed version 4.3 in HA 2021.12.10 using HACS. 
Restarted Home Assistant.
After restart, I still cannot cannot add Garbage Collection to the Integrations, it's not listed there.
After restart I get an error in the logs, see below.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 
No

```yaml

```

**Error log/debug information**

```txt
2022-02-01 14:47:22 INFO (MainThread) [homeassistant.setup] Setting up garbage_collection
2022-02-01 14:47:22 INFO (MainThread) [homeassistant.setup] Setup of domain garbage_collection took 0.0 seconds
2022-02-01 14:47:22 ERROR (MainThread) [homeassistant.setup] Setup failed for garbage_collection: Integration failed to initialize.
```

**Screenshots**

**Version**

Integration version: 4.3

Home Assistant version: 2021.12.10

**Comment by bruxy70** [comment]
I have just removed all configuration removed the integration and installed it again, but I do not get the error.
And when you go to Configuration / Devices & Services, you do not see the integration there, correct?

**Comment by tangix** [comment]
> And when you go to Configuration / Devices & Services, you do not see the integration there, correct?
Correct - I don't see it.

**Comment by bruxy70** [comment]
And you configured logs for `custom_components.garbage_collection: debug` - but it did not show anything?
I am struggling with where to start troubleshooting this :(

**Comment by tangix** [comment]
> And you configured logs for `custom_components.garbage_collection: debug` - but it did not show anything? I am struggling with where to start troubleshooting this :(

Did a complete reboot and now it works... 🤷🏻‍♂️ 
Thanks!
