### ISSUE TITLE
Blueprint Script for Triggering Offset of a collection

### ISSUE THREAD

**Issue by stboch** [bruxy70/Garbage-Collection#328]
I wrote a blueprint for the creation of scripts that will allow you to progamatically advance a collection in week by an offset. This solves my old use case example where bad weather will shift all collections by one day for the week. 

[garbage_collection_slide_in_week.yaml](https://gist.github.com/stboch/c93befde7a8699f90b8180e60283be40)

**Comment by bruxy70** [comment]
Thanks a lot. I have included that in the README. For some reason, the import does not load the preview. It shows the URL correctly, but then it shows it empty. Does it do the same for you?

**Comment by stboch** [comment]
I updated the script apparently it handles the github stuff so just use https://gist.github.com/stboch/c93befde7a8699f90b8180e60283be40 in the import button.

**Comment by bruxy70** [comment]
Link updated. Thanks for the contribution
