### ISSUE TITLE
No start date for every-n-days configuration?

### ISSUE THREAD

**Issue by juhanjuku** [bruxy70/Garbage-Collection#329]
**Describe the bug**
There is no place to input start day when every-n-days is choosen on new configuration page

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

This is for new Config Flow (GUI)

```yaml

```

**Error log/debug information**

```txt

```

**Screenshots**
![image](https://user-images.githubusercontent.com/12792066/152145645-9d562acf-6656-40fe-a161-117593b69bb9.png)

**Version**

Integration version: latest
4.3.1
Home Assistant version: latest
core-2021.12.10
supervisor-2022.01.1
Home Assistant OS 7.2

**Comment by bruxy70** [comment]
Not even on the second page?

**Comment by juhanjuku** [comment]
Sorry, my mistake. 
I didn't pushed SUBMIT because I did not changed anything and obviously had no glue about second page.
