### ISSUE TITLE
Blueprint - currently can move the collection just by one day, even if there's one or more holidays in a week

### ISSUE THREAD

**Issue by Dinth** [bruxy70/Garbage-Collection#330]
**Is your feature request related to a problem? Please describe.**
Currently the blueprint it doesnt work well for weeks with more than one holidays, ie it moves the garbage collection by a day while it should move by two days on that week and a day on the next week

**Additional context**

![Screenshot from 2022-02-04 18-43-15](https://user-images.githubusercontent.com/313674/152585160-a0e8997f-187a-4b01-b56d-a7df6e029154.png)
Normally my rubbish is collected every Wednesday, but on this week i had first collection on Friday (due to 2 christmas bank holidays), the second collection also on Friday (due to New Year), the third one on Thursday (things are slowly getting back to normal) and only fourth collection back to the normal collection day that is Wednesday.

**Comment by bruxy70** [comment]
Ok. I'd probably leave the blueprint as-is (since this is how they designed that when this was part of the package, so I assume this is how it works in these countries). But let's create another version of it that would move it by a day for each holiday.

**Would you like to give it a go and send your contribution, or you want me to create one?**

This is all weird to me - In CZ, they do collect the garbage regardless of the public holiday. If it is Wednesday, they collect it on Wednesday even if that was a Boxing day (or if it was earlier that week). So I have no idea how that is supposed to work in where you come from, and I am just trying to do what I am asked to do 😀

**Comment by Dinth** [comment]
To be honest if that's a desired behavior, it feels awkward to ask you for a new blueprint, but yesterday i had a look into the old blueprint to see if i can modify it and im struggling to even understand all that logic

**Comment by bruxy70** [comment]
No biggie, I'll add it - it is not that difficult. Instead of checking if there is a holiday in the week, it will count them and add that to the offset :)

**Comment by Dinth** [comment]
Dekuji! :)

**Comment by bruxy70** [comment]
I made a new blueprint - check it on [README](https://github.com/bruxy70/Garbage-Collection/blob/master/README.md#public-holidays)
Can you test it and confirm it works the way you intended?

If it feels backward to ask me to do the blueprint for you, you can always 
[![Buy me a coffee](https://img.shields.io/static/v1.svg?label=Buy%20me%20a%20coffee&message=🥨&color=black&logo=buy%20me%20a%20coffee&logoColor=white&labelColor=6f4e37)](https://www.buymeacoffee.com/3nXx0bJDP)

😀

**Comment by Dinth** [comment]
Thanks. I have tested the new blue print. It seems a bit better, but doesnt "carry over" days to next week
![Screenshot from 2022-02-05 11-31-46](https://user-images.githubusercontent.com/313674/152640347-6b5f1ec4-08b1-4dfc-b365-b70f5db21377.png)

**Comment by bruxy70** [comment]
What does it mean "carry over to next week"? Can you explain the whole rule, how is that supposed to work?
Right now, it works in such a way that:
- it counts the number of public holidays before the collection date, in the collection week (starting on Monday), and offsets the collection date by that number
- if the new collection date falls on a public holiday, it will keep moving forward until it finds the day that is not a public holiday (it only registers public holidays, it does not take the weekend as a public holiday)

If it is supposed to work differently, let me know and I will change it :)

**Comment by Dinth** [comment]
Hey. Yep maybe i havent explained that properly in the first place. 
So lets assume that rubbish men are doing one area of the town on each weekday excluding public holidays. 
But then, they can only catch up on one (backlogged) area per week, so if my collection is delayed by two days on a given week, then on a next week it's going to be one day delay (unless there is another public holiday on that week) and only in the second week things are getting back to normal.

PS. I kind of envy that you've get your collection on any day regardless of public holidays without all that hassle :)

**Comment by bruxy70** [comment]
That would not be easy right now. I could use a script variable to store the carry-over value between the iteration, but right now, the script variables are local to the template. So if it stores the value in one iteration, it will not be visible in the next one.
I think there is the intention to improve that, so once this is done, I'll get back to this - hopefully before next Christmas when this will be relevant I guess. I'll put that in the parking lot.

**Comment by bruxy70** [comment]
Got an idea, might be able to do it.
But three quick questions: 
1. if there are public holidays after the day of collection, would that trigger the carry-over? For example, if the collection is on Wednesday, and Thursday and Friday were public holidays (and no public holidays in the following week), would the collection the following week be offset?
2. If the collection was every other week, would that carry-over from the week before (when there was no collection), or from the previous collection week? 
3. What do you think is the reasonable maximum number of consecutive carry-overs? Would that be safe to only check the holiday on the current week and week before? Of two previous weeks? In the other words, are there ever more than two public holidays in a week, or two holidays in a week followed by another week with a public holiday? And if yes, I suppose checking two weeks should do, right?

What I am thinking is, I will not carry the day over between the iterations, but I will always check the current and previous week (depending on the second answer).

**Comment by bruxy70** [comment]
Check it out https://github.com/bruxy70/Garbage-Collection/blob/development/README.md#public-holidays. It is the 4th flavor. Once you download it, you need to remove the old automation, create the new one, and then go to the Garbage Collection Integration entity configuration and click-through (to trigger the update).

**Comment by Dinth** [comment]
Hey. Sorry for the lack of response, had a very busy week. Will test it as soon as i can!
