### ISSUE TITLE
Where is "collection_days" in configuration UI ?

### ISSUE THREAD

**Issue by mikyjazz** [bruxy70/Garbage-Collection#331]
**Describe the bug**

I removed configuration from configuration.yaml but there is not entry for "collection_days" in GUI configuration

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

GUI

```yaml

```

**Error log/debug information**

```txt

```

**Screenshots**

**Version**

Integration version: 

Home Assistant version:

**Comment by bruxy70** [comment]
In step 2
