### ISSUE TITLE
Set to repeating on first and third Wednesday of the month, but seems to also repeat on 5th Wednesday

### ISSUE THREAD

**Issue by dimatx** [bruxy70/Garbage-Collection#332]
Not sure I'm not configuring correctly, but I have the config set to 1st and 3rd Wednesday, but the calendar also shows it repeating on the 5th Wednesday for a month that has 5 Wednesdays

![image](https://user-images.githubusercontent.com/24803941/152655231-367fe3f7-6d5b-4718-a07b-c6079120273b.png)

![image](https://user-images.githubusercontent.com/24803941/152655261-48b46e2e-3857-4300-8013-6e7be324b87d.png)

![image](https://user-images.githubusercontent.com/24803941/152655215-a892d4c0-0d83-4310-b522-49d9554cf83b.png)

**Comment by bruxy70** [comment]
You have configured it not to register the 1st and 3rd Wednesday of the month, but the Wednesday on 1st and 3rd week. So it does what you configured. The 3rd collection is because it is the first week of the following month.

**Comment by dimatx** [comment]
Thanks for the guidance, @bruxy70. Got it working.
