### ISSUE TITLE
UndefinedError: 'dict object' has no attribute 'event'

### ISSUE THREAD

**Issue by kwithus** [bruxy70/Garbage-Collection#336]
**Describe the bug**

i set up the include/exclude automation, using the blueprint, which is quite simple, however when the automation runs it stops with the error code

Stopped because an error was encountered at 8. Februar 2022, 10:38:38 (runtime: 0.02 seconds)

Error rendering data template: UndefinedError: 'dict object' has no attribute 'event'

**Configuration**

```json

id: '[1643477245214](tel:1643477245214)'
alias: Include and exclude dates gelber Sack
description: ''
use_blueprint:
  path: bruxy70/include_exclude.yaml
  input:
    exclude: |-
      '2022-04-19'
      '2022-10-04'
      '2022-11-01'
      '2022-12-27'
    include: |-
      '2022-04-20'
      '2022-10-05'
      '2022-11-02'
      '2022-12-28'
    garbage_collection_entity: sensor.papier_gelbesack

mode: parallel
trigger:
  - platform: event
    event_type: garbage_collection_loaded
    event_data:
      entity_id: sensor.papier_gelbesack
action:
  - variables:
      exclude: |-
        '2022-04-19'
        '2022-10-04'
        '2022-11-01'
        '2022-12-27'
      include: |-
        '2022-04-20'
        '2022-10-05'
        '2022-11-02'
        '2022-12-28'
  - repeat:
      count: |-
        {{ exclude.split('
        ') | count }}
      sequence:
        - service: garbage_collection.remove_date
          data:
            entity_id: '{{ trigger.event.data.entity_id }}'
            date: |-
              {{ exclude.split('
              ')[repeat.index-1] }}
  - repeat:
      count: |-
        {{ include.split('
        ') | count }}
      sequence:
        - service: garbage_collection.add_date
          data:
            entity_id: '{{ trigger.event.data.entity_id }}'
            date: |-
              {{ include.split('
              ')[repeat.index-1] }}
  - service: garbage_collection.update_state
    data:
      entity_id: '{{ trigger.event.data.entity_id }}'
id: '[1643477245214](tel:1643477245214)'
alias: Include and exclude dates gelber Sack
description: ''

```

**Error log/debug information**

```txt
Stopped because an error was encountered at 8. Februar 2022, 10:38:38 (runtime: 0.02 seconds)

Error rendering data template: UndefinedError: 'dict object' has no attribute 'event'
```

**Screenshots**

**Comment by bruxy70** [comment]
And the automation is triggered by the update event from the garbage_collection entity, that is configured for manual update, corect?
I actually use this blueprint myself and it works flawlessly. You can remove the quotes around the date BTW. It was a workaround that was needed earlier.
```yaml
alias: Bioodpad - Include and exclude dates
description: ''
use_blueprint:
  path: bruxy70/include_exclude.yaml
  input:
    garbage_collection_entity: sensor.bioodpad
    include: |-
      2022-01-20
      2022-02-17
      2022-11-24
      2022-12-22
    exclude: '2022-03-03'
```

**Comment by kwithus** [comment]
Ok, if I understand correctly, I don’t have to manually start the automation, actually trying to do this will result in this error. The automation is only triggered by the integration (once a day or on restart?) is that correct?

**Comment by bruxy70** [comment]
This is correct. The automation is triggered by the event generated by the entity update. 
The event includes some event data that are needed for this to work, so if you run the automation manually, the event data will be missing.
Yes, it is done once a day, or on restart. Or if you want to trigger it manually, you can click through the garbage collection entity configuration, it will trigger the update once the configuration is finished.
