### ISSUE TITLE
Custom element doesn't exist: garbage-collection-card

### ISSUE THREAD

**Issue by dunners67** [bruxy70/Garbage-Collection#34]
Hi,
I had your garbage collection working and after upgrading chrome now get this error, but also get it now in other browsers.

**Comment by bruxy70** [comment]
It mentions garbage collection **card**. Can you please check, if the respective sensor is missing (e.g. In developer tools, states), or if that's issue with the custim card? Thanks

**Comment by dunners67** [comment]
The sensors are there and they show the correct state and attributes

On 4/11/2019, at 9:24 PM, bruxy70 <notifications@github.com> wrote:

﻿

It mentions garbage collection card. Can you please check, if the respective sensor is missing (e.g. In developer tools, states), or if that's issue with the custim card? Thanks

**Comment by bruxy70** [comment]
Ok, please open the issue for the card then.
https://github.com/amaximus/garbage-collection-card/issues
