### ISSUE TITLE
Confused re new version

### ISSUE THREAD

**Issue by thorrrr** [bruxy70/Garbage-Collection#342]
### Write your question here

HI
I have just updated and read your well explained latest version, but i didn’t fully understand it sorry.
My is an extremely basic setup  Brown & Black Bin every two weeks but my Green waste is every 3 weeks but stops for several months over Xmas.
I had it running correctly but now i am getting a log error, but on the frontend, it still looks correct.
I don’t understand what i am supposed to do you mention 2 stages and 10 different blueprints seems more complicated than before :)
This error originated from a custom integration.

Logger: custom_components.garbage_collection
Source: custom_components/garbage_collection/__init__.py:324
Integration: Garbage Collection (documentation, issues)
First occurred: 16:48:34 (3 occurrences)
Last logged: 16:48:34

Removed data config {'offset': 21, 'holiday_in_week_move': False, 'holiday_move_offset': 1, 'observed': True, 'include_dates': ['2022-03-07']}. Please check the documentation how to configure the functionality.
Removed data config {'offset': 14, 'holiday_in_week_move': False, 'holiday_move_offset': -2, 'observed': True}. Please check the documentation how to configure the functionality.
Removed data config {'offset': 14, 'holiday_in_week_move': False, 'holiday_move_offset': 1, 'observed': True}. Please check the documentation how to configure the functionality.

Diagnotics see [here](https://1drv.ms/t/s!Ao6WCX2miTCJjNJrJpr3TzZWlrcGqA?e=bprDdQ)

**Comment by bruxy70** [comment]
The error is just a reminder that it removed the parameters, that were previously obsolete and now are removed.
Looking at them, I see 3 things.
- There is a partial configuration for moving schedule based on a country holidays, but you did not configure any country, so this is not used, right?
- You have 1 date you want to include manually. But that does not make any sense as you already have a regular collection on this date. I am not sure why you configured it, but to me it looks like it was redundant.
- I am a bit confused by your offset configuration. You have the collection set-up for every  21 days, starting on 2022-03-07. But then you ask to manually offset it by 21 days. That makes no sense. What the offst used to do was, it would calculate the schedule, and then apply a manual offset. So if you had it configured let's say for 1st wednesday each month, with offset -7 it would be last wednesday (the previous month). But in your case, having it with period 21 days and offseting it by 21 days makes no sense (except for the first date, which you then added manually).

So my conclusion is, that your configuration is fine and simple as you say. Previously, you had it over-complicated, proabably becase it was so complicated and confusing (which was the reasn for the chnage). Ok?

**Comment by thorrrr** [comment]
So, in my case I can leave it as it is?
I though i had to start importing 3 different blueprints to reconfigure it!
So on 7 March when green bin starts again its 3-week cycle do i have to get a new blueprint

**Comment by bruxy70** [comment]
Ok, so you need to have 2 entities, both with 14 days period, but one with a starting date a week later than the other. 
Alternatively, you can configure one for odd and one for even week number - but that is based on week numbers, so thsi might be an issue on new year, if the year has an odd number of weeks, and then it starts with week number 1, it would basically reset in January. So it might not be what you want.

For the 3rd one, just configure the first month and last month - that's a standard config on the second screen. I think you have that configured. And you need to configure it either every 21 days (3 weeks) starting from a chosen date. The challenge here is, that it will repeat evey 21 dats starting from the initial date, and it will just cut out the two months. So when you configure it to start on March 7 2022, for next year it will start in a multiply of 21 days from the March 7 - that will be March 20 I am afraid. This is how it always worked, I did not change a ting in this. So you'd have to adjust the config next year to start on March 6 next year. 

Or, you can now configure it for a weekly schedule, configure it for a manual update and then make an automation to drop the collections in the two weeks in between. So technically, it is now possible (was not before). But if thsi is not your thing, I'd leave it there.

**Comment by thorrrr** [comment]
HI 
I cannot work out where i get to step 2 ?
I set everyndays but it get an error if i hit submit!
Where is the area i set days or dates?
![image](https://user-images.githubusercontent.com/8170673/153050830-fab20d08-f6f6-4c5b-bca3-6f1c52c1f0c5.png)

**Comment by bruxy70** [comment]
After you submit. But it looks like you found a bug. Let me check....

**Comment by thorrrr** [comment]
Also another errror 


![image](https://user-images.githubusercontent.com/8170673/153055277-7537a48b-2b0c-40b2-808d-b07a543dfe2a.png)

**Comment by bruxy70** [comment]
That's interesting, I had this out for quite some time, but nobody found this. Anyhow, i just made a release fixing the first issue. I cannot replicate the other one, that one works fine for me.

**Comment by thorrrr** [comment]
Well at least it was found early :)
The one just did it 1 time but now looks ok

**Comment by thorrrr** [comment]
I have the new version but i think the day calcs are out.
My next collection is tomorrow so i expect to see 1 day 
My Brown Bin is next Wed i expect to see 8 days 
Under the old settings that was correct.
But now i have set it via the UI is shows Black Bin 0 Days which means today  & Brown Bin & Days which is next Tue

![image](https://user-images.githubusercontent.com/8170673/153082273-4f80c99c-d43b-47f9-ad5b-58ef8ac69d3f.png)



![image](https://user-images.githubusercontent.com/8170673/153082342-79e702d4-bef1-47a6-9eef-451d449e0234.png)

**Comment by bruxy70** [comment]
Feb 9 2021 was Tuesday. Today is Tuesday. So the collection should today, not tomorrow.

**Comment by thorrrr** [comment]
Sorry I didn't see the year default back to 2021

**Comment by thorrrr** [comment]
Now it is working pure genius very easy to use well done
