### ISSUE TITLE
Case of text in "Verbose state (text, instead of number)" mode

### ISSUE THREAD

**Issue by ChirpyTurnip** [bruxy70/Garbage-Collection#344]
### Write your question here

Hi,

Is it possible to get the verbose text state to be displayed in sentence case? That is, when it is  "in two days" or "tomorrow"  or "today" it displays "In two days", "Tomorrow", or "Today"?

It just looks a little weird in lower case. 

Other than that I really like the simplified approach - I think it is a good change and a huge improvement! :-)

CP.

**Comment by bruxy70** [comment]
Thanks.
That's probably an issue with the localization, let me check it.
The way it works all across HA is, the actual states are in lower case, but then they are displayed on the dashboard in the language you have selected for the user (including English). And this translation typically shows the state with first letter capital. If you check all the other sensors, this is how it works.
I thought it worked, but it apparently broke somewhere. Let me fix hat and include in the next release. Thanks.

**Comment by bruxy70** [comment]
Right, the translations did not work. Fixed on dev, will be in the next release.

**Comment by ChirpyTurnip** [comment]
Excellent! I did loop back to check a running browser instance that hasn't
refreshed since I update the integration and it was working in the old
version so that's good news!

:-)
