### ISSUE TITLE
Undo collect_garbage

### ISSUE THREAD

**Issue by rogatty** [bruxy70/Garbage-Collection#347]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Is your feature request related to a problem? Please describe.

Hi, would be nice to have a way to undo the collect_garbage service call after a misclick.

### Describe the solution you'd like

A service that one has to call manually or another way around, just to make it possible. 

Looking from a regular user perspective, it would be nice to keep the entry in UI and have an undo button, but that might require more changes in both backend and frontend (e.g. https://github.com/amaximus/garbage-collection-card), so I'm just putting the idea out there. A service is enough for me.

### Describe alternatives you've considered

I tried updating the entity state manually with `last_collection` in the past. It was restored in a matter of seconds. It's possible I don't understand how HA works and there is a way to make it work without any code changes.

### Additional context

I'm using v4.4.2 if it makes a difference.

**Comment by bruxy70** [comment]
Good suggestion. As a workaround, you can call the service `garbage_collection.collect_garbage` with the `last_collection` with a date sometimes in the past (could be yesterday, could be a year ago). It will recalculate the state. Would that work?

**Comment by rogatty** [comment]
I assumed there is no param to override the date based on docs: https://github.com/bruxy70/Garbage-Collection/#garbage_collectioncollect_garbage

But it works and totally makes sense! I don't think there is a need to change code but docs update would be nice 🙂

**Comment by bruxy70** [comment]
Ok. Will update the documentation. Thanks for the catch. If you call the service from the Developer Tools, it will show the parameter crrectly.
