### ISSUE TITLE
problem with annual dates

### ISSUE THREAD

**Issue by jsztram** [bruxy70/Garbage-Collection#349]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

there is a problem with adding a few annual dates in the setup for example 03/01, 04/02, 05/04. This configuration does not work. When I add one date (eg. 03/01) the configuration works fine.

### Configuration

.

### Debug logs

```text
.
```

**Comment by bruxy70** [comment]
That's correct, that's how it works. Annual means once per year, I think the motivation for that was, people wanted to track birthdays. And it did not count with having multiple birthdays per year :)
Overall, I take the annual frequency as a redundant feature to standard google calendar integration, that is much better in that. But I kept it in as there is apparently a significant group of people who use it. But I do not intend to create a google calendar from it :).
I understand this is a limitation, but I'd like to stay away from manually creating comma-separated lists in the configuration, this was quite fragile. So I got rid of all of those in the last release.

Ok, so the above is some background, but not very helpful, right? There are 2 ways you can approach it, if you want to use this integration for that (I'd still suggest looking at google calendar for recurring annual events)
1.  you can create multiple annual frequency entities and then make a group entity to bring them together.
2. you can create an annual (or blank) entity and add the rest through a manual update - there you can add additional dates in the automation.

**Comment by silver0007** [comment]
Is it possible to bring back this option? A lot of people was using annual as "custom list" as alternative options are just not user-friendly. Previously it was simple list in UI.
It's super rare that it's possible to set a schedule as "every n days" etc.

**Comment by nemezis336** [comment]
Hi, I agree with silver0007. This integration is important to me and helpful for the whole family, but figuring out the calendar plan and how to translate it into selected repetitions takes me a few nice hours, and manually entering the dates is only 30 minutes and the problem is over. It is unnecessarily so complicated.
30 minutes of work once a year. I would like that much.

**Comment by bruxy70** [comment]
I am not sure what you are talking about. @silver0007 first asked to bring back something that was never there.
And now you are asking for something that is available. If you have 30 minutes to enter then dates manually, then just do it.

**Comment by nemezis336** [comment]
Can you tell me which item allows me to enter dates manually? 

![obraz](https://user-images.githubusercontent.com/59469300/153728767-d72373aa-fc1b-4795-8ff0-5b468cf459ed.png)

**Comment by bruxy70** [comment]
https://github.com/bruxy70/Garbage-Collection#blueprints-for-manual-update, specifically the Include Blueprint

**Comment by silver0007** [comment]
"silver0007 first asked to bring back something that was never there".
@bruxy70, previously "annual" was expecting one date but it was also allowing to have comma delimited list of dates additionally to "the one annual date". It was option "include dates" or something like that. I was using it for months, so it was there :)
It was super simple way of having custom list. No need to install any blueprints and maintain additional configs. Just a list in integration cofig. Simple as that.
