### ISSUE TITLE
Error since updating to 2022.2.x

### ISSUE THREAD

**Issue by Kanga-Who** [bruxy70/Garbage-Collection#354]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

```
Restart Home Assistant: Error executing script. Error for call_service at pos 1: The system cannot restart because the configuration is not valid: Invalid config for [garbage_collection]: Not a list for dictionary value @ data['garbage_collection']['sensors'][0]['collection_days']. Got 'mon'. (See /config/configuration.yaml, line 115). 
```

### Configuration

```JSON
garbage_collection:
  sensors:
    - name: General Waste
      frequency: "weekly"
      collection_days: mon
    - name: Recycling
      frequency: "odd-weeks"
      collection_days: mon
    - name: Green Waste
      frequency: "even-weeks"
      collection_days: mon
```
```


### Debug logs

```shell
Unable to get debug logs as I can not restart HA with the integration enabled.
```

**Comment by bruxy70** [comment]
Can you please help me testing the fix? Can you take the `__init__.py` file from [here](https://github.com/bruxy70/Garbage-Collection/blob/master/custom_components/garbage_collection/__init__.py) ut it in the custom_components/garbage collection, restart and see if it helps. The collection days is supposed to be a list, not text, but it was a valid option before, so I am trying to support that in the migration script. Thanks!

**Comment by bruxy70** [comment]
Ok, can you try again pls? I apreciate your help, it will help others with importing the legacy config. Thanks!

**Comment by tiptap85** [comment]
> Ok, can you try again pls? I apreciate your help, it will help others with importing the legacy config. Thanks!

Same error...

**Comment by bruxy70** [comment]
Do not know. I have cleared all my config and configured yours, and it imported fine:
![image](https://user-images.githubusercontent.com/44951610/153716671-0b48bc4a-909c-4f0f-9233-87311075edf8.png)
I just made a release with the modified init file, so please upgrade and restart if it helps.
Did you check in the Integrations page if the devices are still missing?

**Comment by jgronowski** [comment]
@bruxy70 problem solved. The latest commit fix the issue.

**Comment by Kanga-Who** [comment]
I'm still getting the same problem on 4.4.5, can no restart HA. Is my config incorrect?

```
Restart Home Assistant: Error executing script. Error for call_service at pos 1: The system cannot restart because the configuration is not valid: Invalid config for [garbage_collection]: Not a list for dictionary value @ data['garbage_collection']['sensors'][0]['collection_days']. Got 'mon'. (See /config/configuration.yaml, line 115). 
```

**Comment by Kanga-Who** [comment]
> @Kanga-Who , I do not know what is your config, I do not know what do you mean by weird, and I do not know what add-on you re-installed.

My config was in the OP. 

It was weird that I was still getting an error after updating, but uninstalling this add-on and reinstalling it fixed the issue - as stated in my last post.

**Comment by bruxy70** [comment]
Ok, sorry, I thought that one was already resolved, did not notice it was someone else :)
