### ISSUE TITLE
Confused | Pickup on every 2nd and 16th of the month

### ISSUE THREAD

**Issue by leofabri** [bruxy70/Garbage-Collection#357]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hello, I'm trying to configure the following schedule:

| Waste | Collection Schedule |
|-------|---------------------|
| ✅   Paper   |         Weekly, every **_Wednesday_**            |
| ✅   Plastic  |         Weekly, every **_Wednesday_**            |
| ✅   Organic  |        Weekly, every **_Saturday_** and **_Wednesday_**            |
|✅    Bio waste  |         Weekly, every **_Saturday_**            |
|✅    General Waste  |         Weekly, every **_Saturday_** (from March 1 to November 30)            |
| ❓   Glass and Cans  |         Monthly, on the **2nd, and 16th of each month**            |

I managed to configure most of the entries (✅), but I'm struggling with the last one. I am not sure how to make the configuration based on a specific day number (or set of days) of the month.

### Exceptions and Holidays: 
I'll also have to add some exceptions. I haven't looked into these specific conditions so I haven't configured these yet, but I want to show them in case it's useful for development.

On **January 1st** | **January 6th** | **Easter Monday** | **April 25th** | **May 1st** | **June 2nd** | **August 15th** | **November 1st** | **December 8th** | **December 25th** | **December 26th** | **Every Sunday**:

- **General Waste:** the collection will be carried out, with the exception of Christmas Day, which will be postponed to the first working day (even if the shift does not coincide with the above schedule).
- **Organic:** the collection will not be carried out, with the exception of Easter Monday, June 2, and August 15, days in which the service will be carried out regularly
- **Paper, Plastic, Glass, and Cans:** the collection will be postponed to the next business day.
- **Bio waste:** during the holidays from March 1 to November 30, the collection will be carried out regularly.

**Comment by leofabri** [comment]
Thank you so much @bruxy70! The blueprint is working flawlessly. Yeah, when it comes to waste that there are so many use cases!

Using a custom blueprint is totally fine to me. Maybe, it might be nice to mention this on the wiki so that others can approach the integration fearlessly. 
As for the exceptions, I'll definitely check the other blueprints out. Doing the offsets myself and keeping track of all the exceptions is too hard for someone who struggles to remember his own phone number lol :)

Keep up the great work man!

**Comment by bruxy70** [comment]
Great that it worked. Where in the wiki do you suggest mentioning that?
I made a [video](https://youtu.be/qD7MeGLNxk4) about that BTW, so that might help. And I tried to to make the GitHub documentation and the Blueprints rather self-explanatory. Not much active on the wiki I am afraid.

**Comment by leofabri** [comment]
Sorry for not replying @bruxy70, I somehow did not see the notification. 
Anyways, you have done a great job! I saw the video, and my family is already enjoying how straightforward this is. 
I've noticed you added the blueprint to the readme... I think it's more than enough as it's also quite easy to implement. I doubt anyone would have a problem with it.
