### ISSUE TITLE
Integration is calculating on first occuring day instead of week number

### ISSUE THREAD

**Issue by ibl129** [bruxy70/Garbage-Collection#36]
Just updated to the v2.2. But as a matter of fact the following error occurs, when I try to configure by Home Assistant integrations:
-> name: plastics
-> frequency: monthly
-> collection_day: wednesday
-> monthly_day_order_number: 2

Today (third week over november, but the seconds wednesday this month) it's showing the plastics are getting picked up. Shouldn't it calculate from the first week of a month instead of the first occuring day in that month just as the old configuration in configuration.yaml worked?

**Comment by bruxy70** [comment]
I do not think this has changed. For the monthly collection, it has always been nth weekday of the month (e.g. 1st and 3rd Saturday each month). The concept of "on Wednesday 3rd week of November" was never considered. Is that necessary? What would happen if you'd configure 1st Wednesday, and the month would start on Thursday? Would the collection be skipped? 
You are perhaps confusing that with the collection `"every-n-weeks"`? That one is calculated based on the week number (but calculated from the beginning of the week).

**Comment by bruxy70** [comment]
Also, the parameter `monthly_day_order_number` has been changed to `weekday_order_number`.  See [readme](https://github.com/bruxy70/Garbage-Collection#parameters-for-monthly-collection)

**Comment by ibl129** [comment]
Yes I saw that the weekday_order_number was replacing monthly_day_order_number. I used an old variable to represent the issue I am having. 

But to be honest, yes it would be great when the calculation can be specific ended on the count of weeks. But maybe I am just the only one who would like this option 😉

Thanks for your fast reaction!

**Comment by bruxy70** [comment]
I am thinking how to add that in the next release. Just that I understand - let's take an example of Wednesday, 1st week of each month.
In November...Nov 1st was Friday. Does that mean that this will not happen on November, Dec 1st is Sunday, so it will not happen in December either, January 1st is Wednesday - so the 1st collection will be on Jan 1st. Correct?
Or do you mean that for November it will actually be on Wednesday that week - that was October 30?

**Comment by ibl129** [comment]
How cool would that be if you could implement this feature!
It’s meant like your last example. In case of the november month it will be collected on wednesday the 30th (which indeed still is October).

**Comment by bruxy70** [comment]
Ok, I'll add another parameter - `week_order_number`, instead of `weekday_order_number`. [Would that be understandable](https://github.com/bruxy70/Garbage-Collection#parameters-for-monthly-collection)?

**Comment by ibl129** [comment]
So like week_order_number represents the day on which the collection will be done and the first day of that ‘new’ month can be later on in that same week?

**Comment by bruxy70** [comment]
Not at all. The week order number is not the day, it is number or the week (or list of numbers).
So for monthly schedule, you will be able to configure either week_order_numbers, or weekday_order_numbers. Does it make sense? I will try to make the documentation clearer. Thanks for helping with that. 

... I guess that's the reason I am struggling with all the new feature requests - how to avoid the configuration getting big mess nobody understands (not even talking about the code...)

Anyhow, it will be ready at the beginning fo next week.

**Comment by bruxy70** [comment]
@ibl129 , if you'd like to test it, download the dev branch, copy all files from the custom_components/garbage_collection to your home assistant, in your config, replace `weekday_order_number` by `week_order_number` (or change it via integration config if this is how you configured it). And let me know if it does what you meant. Thanks!
