### ISSUE TITLE
problems about automation with new version of garbage-collection module

### ISSUE THREAD

**Issue by pilot1981** [bruxy70/Garbage-Collection#360]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi,
until today I always used these automation to get notification of day for garbage collection at home:

garbage_organico.yaml:

`
automation:
  alias: "Notifica ritiro organico"
  trigger:
    platform: numeric_state
    entity_id: sensor.raccolta_organico_mattino
    value_template: "{{ state.attributes.days }}"
    below: 1
  condition: []
  action:
# Sets date and time to date and time from timestamp (current date and time in this example)
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.datetime_organico
        date: >
          {{ now().timestamp() | timestamp_custom("%Y-%m-%d", true) }}
        time: >
          {{ now().timestamp() | timestamp_custom("%H:%M:%S", true) }}
`

notifica_organico.yaml:

`
automation:
- alias: "notifica il giorno dopo il ritiro organico"
  trigger:
    platform: template
    value_template: "{{ states('sensor.date_time').replace(',', '')|as_timestamp >= state_attr('input_datetime.datetime_organico', 'timestamp') + 19*60*60 }}"
  action:
    - service: notify.famiglia
      data:
        message: "Ciao Barbara, oggi è giorno di ritiro organico!"
    - service: notify.alexa_media
      data:
        target: 
          - media_player.echo_sala_da_pranzo
        data:
          type: tts
        message: "Ciao Barbara, oggi è giorno di ritiro organico! Adesso puoi portare fuori il pattume!"
`

Now, I have problem notification happen always the next day at wrong time....what I have to change?

**Comment by pilot1981** [comment]
Hi,
I need to get notification the day before garbage collection at 19 hour...what do you suggest to setup this simple automation?

**Comment by pilot1981** [comment]
I already done it!

- service: input_datetime.set_datetime
  data_template:
    entity_id: input_datetime.datetime_organico
    date: >
      {{ now().timestamp() | timestamp_custom("%Y-%m-%d", true) }}
    time: >
      {{ now().timestamp() | timestamp_custom("%H:%M:%S", true) }}


trigger:
platform: template
value_template: "{{ states('sensor.date_time').replace(',', '')|as_timestamp >= state_attr('input_datetime.datetime_organico', 'timestamp') + 196060 }}"

but it don't work anymore...

**Comment by bruxy70** [comment]
I do not know what this is supposed to do. Looks quite complicated and heavy. I'd keep the trigger simple.

Why don't you simply do it like that: https://www.home-assistant.io/docs/automation/trigger/#time-string

If you need to make such a complex trigger, I think last year there were some changes in HA in the past in template sensors based on the time, I think they stopped triggering the sensor update based on now(), this is why they introduced the trigger-based templates for that - so if you need that, I'd check that.

In any case, this has nothing to do with the garbage_collection integration or any version update....
