### ISSUE TITLE
Import from file: sensor max length is exceeded

### ISSUE THREAD

**Issue by Pe-MaKer** [bruxy70/Garbage-Collection#361]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

When I try to import the organic waste collection dates from a text file, I hit the limitation of 255 characters, a command_line sensor state can take.

All 41 dates add up to 450 bytes

`homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.import_bio. State max length is 255 characters.`

See my other types of waste which also remain just under the limit of 255 characters
Paper: 252 Byte
Residual waste: 252 Byte
Recycling: 131 Byte

I know this is not a bug but an expectable behaviour.
Is there a way to tweak this limit?

### Configuration

```JSON
everything according to documentation
```

### Debug logs

```shell
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.import_bio. State max length is 255
```

**Comment by bruxy70** [comment]
I guess doing that for a shorter period.
If you are somewhat more advanced, you can use a (python script)[https://www.home-assistant.io/integrations/python_script/] in the automation doing the update. That one would read the file and feed the dates to the garbage collection (so you won't even need the command_line sensor). Or even do the whole automation in appdaemon - there you can read a file as well.
