### ISSUE TITLE
Delay One Day if no Garbage collection

### ISSUE THREAD

**Issue by HVPereira** [bruxy70/Garbage-Collection#362]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hello everyone,

Sorry if this looks like a dummy question but I am still trying to wrap my head around this. I use garbage collection for tracking the filters replacement in my aquarium and the plan fertilization as shown below:

![image](https://user-images.githubusercontent.com/5346125/154295850-0ffaf566-0c32-452d-84a3-8e8fc22d2317.png)

The point here is I'm using verbose and would like to send some actionable notification where HASS will query the user to see if the replacement of the filter or the fertilization was performed. If not I wanted to delay one day... I've checked the documentation but I don't know how can I achieve this (or if it is even possible) did someone had a similar case? Also I'm using verbose so my comparison in the automation should consider the state 'Tomorrow' and 'Today' correct?

Hope someone can help me and sorry if this is already available somewhere here.

Best Regards,
HP

**Comment by bruxy70** [comment]
That would be a bit complicated and would get quite complex. I'd look at using the [timers](https://www.home-assistant.io/integrations/timer/) for that.

**Comment by HVPereira** [comment]
But is there a possibility to offset one day only in the variable? or there is only the possibility to offset the entire collection?
