### ISSUE TITLE
Function annual

### ISSUE THREAD

**Issue by Raddii** [bruxy70/Garbage-Collection#363]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi, I need help configuring the "annual" function because after the update, I only had one collection date there and before that there were more according to the documentation yyyy-mm-dd, yyyy-mm-dd. Unfortunately, this format does not work now. The question is, what is the format for entering several dates now?

**Comment by Raddii** [comment]
If I knew well in the annual function, there was an option to chase the date or turn off the date that I do not see now.

Then which function should be used for irregular loads?

**Comment by bruxy70** [comment]
https://github.com/bruxy70/Garbage-Collection#blueprints-for-manual-update
