### ISSUE TITLE
Calendar with frequency blank

### ISSUE THREAD

**Issue by braetkuegeli** [bruxy70/Garbage-Collection#364]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I would like to create a `blank` calendar and manually add the collection dates.
But after setting up the calendar and adding the dates with the `include dates` blueprint, dates are not listed in the calendar - even after restarting ha.
Also it's not possible to customize verbose state, because setup page 2 does not show up.
![image](https://user-images.githubusercontent.com/2705478/154809319-182a3664-3fbf-495c-b9a4-39a0065e69b2.png)

Do I something wrong?

**Comment by bruxy70** [comment]
This screen looks all right. The verbose format is showing on the second step - ok, there might be an issue that the second step does not show for the blank frequency. Let me check. As a workaround, you can use annual frequency, with one of the dates.
Did the automation you created from the blueprint start? Send me a screenshot of what you added in there.

**Comment by braetkuegeli** [comment]
I' ve update to version 4.5 and the 2nd config screen now appears.
The automations looks like this:
![image](https://user-images.githubusercontent.com/2705478/154833401-ca4bb0f6-65e0-4ed7-87ec-7c682eeaefe6.png)

In the home-assistant.log there are only these log entries for this:
After the log entry `Looking for next collection` there is no more entry for this sensor. Also the dates are not shown in the calendar.

>2022-02-20 08:33:15 DEBUG (MainThread) [custom_components.garbage_collection] Setting Qwell Lieferservice (blank) from ConfigFlow
>2022-02-20 08:33:45 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Qwell Lieferservice) Calling update
>2022-02-20 08:33:46 DEBUG (MainThread) [custom_components.garbage_collection] called add_date 2021-02-21 from sensor.qwell_lieferservice
>2022-02-20 08:33:46 DEBUG (MainThread) [custom_components.garbage_collection] called add_date 2021-03-28 from sensor.qwell_lieferservice
>2022-02-20 08:33:46 DEBUG (MainThread) [custom_components.garbage_collection] called update_state for sensor.qwell_lieferservice
>2022-02-20 08:33:46 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Qwell Lieferservice) Looking for next collection
>2022-02-20 08:33:45 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Qwell Lieferservice) Dates loaded, firing a garbage_collection_loaded event
>2022-02-20 08:33:46 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Qwell Lieferservice) Looking for next collection

**Comment by bruxy70** [comment]
Right. Before I dig-in, are you aware that you add dates in 2021, we are 2022 couple of weeks now...

**Comment by braetkuegeli** [comment]
Shame on me - now it works!

>2022-02-20 14:03:22 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Qwell Lieferservice) Looking for next collection
>2022-02-20 14:03:22 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Qwell Lieferservice) next_date (2022-02-21), today (2022-02-20)
>2022-02-20 14:03:22 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Qwell Lieferservice) Found next collection date: 21.02.22, that is in 1 days
