### ISSUE TITLE
Please make it clearer how to use options

### ISSUE THREAD

**Issue by crashmatt** [bruxy70/Garbage-Collection#366]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

It is not obvious to me how to apply some of the common parameters.  The hint on project page is:

_The configuration via configuration.yaml has been deprecated. If you have previously configured the integration there, it will be imported to ConfigFlow, and you should remove it._

For example, how to implement "expire_after"

I found configuration in.
/config/.storage/core.config_entries

Is this the correct place to edit?
Should it go in options, data or parameters?

`            {
                "entry_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                "version": 4.5,
                "domain": "garbage_collection",
                "title": "XXXXXXXXXXXXXXXXX",
                "data": {
                    "unique_id": "xxxxxxxxxxxxxxxxxxx",
                    "frequency": "even-weeks",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "first_month": "jan",
                    "last_month": "dec",
                    "collection_days": [
                        "mon"
                    ],
                    "verbose_state": false
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": null,
                "disabled_by": null
            }`

**Comment by bruxy70** [comment]
Configure it from Configuration / Devices and Services screen. Expire after is here:
![image](https://user-images.githubusercontent.com/44951610/154905080-1a52985a-ca72-4409-9241-9b84490e682c.png)
