### ISSUE TITLE
Include certain holidays for collection

### ISSUE THREAD

**Issue by kaizersoje** [bruxy70/Garbage-Collection#367]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Is there a way to include certain holidays for collection? For example: Here in Melbourne, the Melbourne Cup is a public holiday. However, collections can still happen on this day. There are other similar holidays like that.

**Comment by bruxy70** [comment]
Yes, the Holidays integration has a feature to pop the holidays out of the list. So these will then be ignored and collection will happen normally (that is the purpose of this feature).

**Comment by kaizersoje** [comment]
Hmmm it is still a public holiday. But not a holiday for collection. I could exclude that holiday during the garbage collection sensor setup in the previous configuration.

**Comment by kaizersoje** [comment]
I wouldn't want to pop it out of the holidays list as it is a holiday. However it should be possible to ignore the holiday for the garbage collection sensor.

**Comment by bruxy70** [comment]
...or you could write own automation, that will filter out the list of holidays you do not want to skip. But that would be kind of redundant - this is a core feature of the calendar, this is the reason why it is there....
