### ISSUE TITLE
 Days of receipt

### ISSUE THREAD

**Issue by bluorange** [bruxy70/Garbage-Collection#369]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I have a configuration problem. I don't know how to add individual pickup days. In a given year, these are: 2022-01-26,2022-02-23,2022-03-09,2022-03-23,2022-04-06,2022-04-20,2022-05-04.......... 
Before the update, there was an option in annual to add more dates

**Comment by bruxy70** [comment]
It's been removed in 4.4 and replaced by a more genric blueprint. More info [in the release notes](https://github.com/bruxy70/Garbage-Collection/releases/tag/4.4.5) and the [readme](https://github.com/bruxy70/Garbage-Collection#blueprints-for-manual-update)
