### ISSUE TITLE
Manual update automation/setup

### ISSUE THREAD

**Issue by molly200** [bruxy70/Garbage-Collection#371]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hello,
Thank you for this integration!
I am running HA in docker with a split configuration. The garbage collection in my town is done weekly and is divided for zones, which make the garbage collection very inconsistent.  And then, there are the holiday, which makes it even more complicated. As such, I need to import the schedule using your import blueprint/automation. However, I am having a hard time implementing this option. I’ve installed the integration as instructed, created a “import.txt” file with about 50 lines, listing one date with this format “dd-mm-yyyy” and created a  binary sensor command_line sensor.
Creating the sensor with a “command_line” was challenging, as it appears that the command_ line platform for the “sensor” entities is deprecated.  The only way the command line appears to work, is via the “binary sensor”,  but that may be the problem!
The automation seems to be triggered every time the configuration gets updated. However, the calendar does not get updated, no matter what I’ve tried. 
Does the import.txt file need to have the date to a specific format? I have tried all combinations!
The automation trace shows a trigger and then it immediately aborts.  There is no log or any errors that I can see.
What does the “Hide in calendar” means?  Does it need to be checked ?
Is there any manual configuration where one can input a list of dates?
The blueprint seems to use input selection. Do I need to create  an input_select for this to work?
Any help in making this work is appreciated!

Thanks

**Comment by bruxy70** [comment]
The hide in calendar option will not create the calendar. The manual configuration is done by the automation. In Your case, you use a blueprint for that automation, that reads the dates from the sensor and adds them in.
So the first thing I'd do is to check that the entries are present in the sensor.
The dates need to have ISO format, that is yyyy-mm-dd. But you can obviously change the automation to convert that to any format you need.
I am just making 5part series about making automations. So I think I will cover the questions about input selection in there. But in a nutshell, blueprint is basically a script or automation, that has a block of selectors in front, that allows you to configure the static parameters (such as sensor entity ID, or number constant) from GUI, when you create the automation from the blueprint. The automation then uses these selectors in templates. So if you want to customize it, you have two options - either customize the blueprint. Or, you can get rid of the selectors, replace it with your actual values and convert that to a standard automation. Personally, I'd use the first approach.

**Comment by molly200** [comment]
Thanks for the feedback!

I think I understand the automation concept with the blueprints. What I meant by the using of the input selection, was just asking if there is another way to input the data into the integration.  I don't have the understanding of the workflow of how the data is read and displayed by the integration so I can create my own automation.

I have checked the sensors and are created and imputed correctly into the blueprint. The cat command does read the file as it lists all the dates in the terminal. 

Yesterday after posting my problem, the HA log spits out he following:
" Import "Garbage Collection from txt: Error rendering Import Garbage Collection from txt repeat count template: UndefinedError: 'import' is undefined" " and
" Template variable error: 'import' is undefined when rendering '{{  states(import).split(' ') |cont }}'  "

Are these related to the integration script? 
When directed to create a command sensor do I supposed to create a regular sensor? I have tied numerous times to create one but HA does not display any new command_line sensor.entity. Does a binary_sensor.entity work?
I did change the date format but still not working.

**Comment by bruxy70** [comment]
https://www.home-assistant.io/integrations/sensor.command_line/

**Comment by bruxy70** [comment]
I think I answered, that the input select that allows adding the dates directly is in the import blueprint.
As for the import, I do not know. When I was playing with that, it worked. But i do not use it. If you say it does not work, i will remove the blueprint from my site, right?
If you figure out other way to import a text file, please share it here, so that others can use it as well. Thanks.

**Comment by molly200** [comment]
Ok thanks!

Don't remove it yet. It may be useful for someone else! I was playing with it and it looks that may be a problem with my split configuration. If I directly create a sensor in the main configuration under "sensor:", it seems to create an entity that the blueprint can see it. 

I'll see if I can get to the bottom of it and I will provide feedback if I can make it work!  Meanwhile, I will try the include blueprint and see if it does the job for me.

I am also using your Holidays integration. Great work! 

Thanks again for the integrations, your time and have a great weekend!
