### ISSUE TITLE
How to set a monthly pick-up?

### ISSUE THREAD

**Issue by LCMilstein** [bruxy70/Garbage-Collection#373]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I love the updated integration. I have it successfully tracking my garbage collection (twice weekly) and my recycling (every other week) using 2 separate integration instances added. I have a 3rd I'm trying to set that occurs on the 1st of every month (not a specific weekday, but rather Jan 1, Feb 1, Mar 1, Apr 1, etc.); I have tried all of the configuration options in the integration setup I can think of and can NOT get it to show on the proper day. Any chance you can provide guidance on what the setup should be to make that work?

**Comment by bruxy70** [comment]
The regular configuration is not designed for that. If you want to do this, you can use the "blank" frequency, setup the integration with a "Manual update" turn on, and have an automation that will fill-in the schedule automatically on each update. Do you want to do that? I'd think about a blueprint to do that. I think I saw more people who wanted to do that. I usually tell them to use google calendar integration instead of the garbage integration, but it comes up regularly :).

**Comment by bruxy70** [comment]
I have just realized that I did the blueprint already. Here it is:
https://github.com/bruxy70/Garbage-Collection#monthly-on-a-fixed-date

**Comment by LCMilstein** [comment]
Thank you! I was going to look into this today to answer your question from Friday. I'll see if I can figure out how to implement the blueprint now.

In the meantime, to reply to your other question, I don't yet have Google Calendar integrated and per Jeff @ SlackerLabs (https://www.youtube.com/watch?v=NQH0c6YGQqY), it's not going to be straightforward to make any of it work, but question back to you...
IF I make Google calendar work in general, would I still use Garbage Integration for the collection reminders or just set a recurring event in Google and go from there?

**Comment by bruxy70** [comment]
No, I guess you's use the google calendar integration instead of garbage collection. Or you can use the blueprint. Up to you.

**Comment by LCMilstein** [comment]
Got it. Well, I used the blueprint and it was VERY easy. I have it working and really appreciate it.

I find it weird that there's no "Add Event" feature in the calendar generally and it just pulls in dates from these other integrations, but that's beyond the point for now. Thank you again!
