### ISSUE TITLE
Date always shown in english

### ISSUE THREAD

**Issue by TobiasSchwarz74** [bruxy70/Garbage-Collection#374]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

The date (name of day, month) is always shown in english and does not use the HA users setting.
My users are all set to german, but the date (name of day, month) for garbage collection is always shown in english.

### Configuration

```JSON
every garbage collection
```

### Debug logs

```shell
no error message
```

**Comment by TobiasSchwarz74** [comment]
would be nice to convert this to feature request!

**Comment by bruxy70** [comment]
This is a backend integration, it does not do anything with how dates are formatted. It does not work with user settings.
