### ISSUE TITLE
Garbage Collection not showing up

### ISSUE THREAD

**Issue by PDXUser** [bruxy70/Garbage-Collection#375]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

This is on a fresh as in today install of HASSIO Version core-2022.3.2 Operating System Home Assistant OS 7.4 Pi4

When installed, I restarted the server as well as the hardware trying to fix the issue.  When I search for the Garbage Collection in the integrations, it is not found.  Additionally, I can not debug this as there is no entity for it or logs for it since it is not seeing it. 

There were no errors during installation as well. 

### Configuration

```JSON
See above:  Nothing to see in the system else I would add it here.
```

### Debug logs

```shell
Same as above.  Entering the custom_components.garbage_collection: debug will not work, HA says it is not found..
```

**Comment by bruxy70** [comment]
Do not know. There are about 4000 people using it, including me. No such issues.

**Comment by PDXUser** [comment]
Fantastic!  I'm glad nobody else has this issue and it turns out I don't anymore as well.  I ran into a gnarly issue with my  DNS server last night and just resolved it this morning.  After fixing that, I can now access it, so chalk it up to a bad DNS server for my end.
