### ISSUE TITLE
How to configure different weekly collections

### ISSUE THREAD

**Issue by swin66** [bruxy70/Garbage-Collection#377]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Can this cater for weekly collections that alternate each week?
e.g. our collections are weekly, but alternate between recycled (pink bags) and non-cycled (black bags).
So, we get a pink collection every 2 weeks, and a black bag collection every 2 weeks.
i.e. week 1 - pink, 2 - black, 3 - pink, 4 - black etc etc
And I'd like the UI to show an appropriately coloured bag icon.
Thanks

**Comment by bruxy70** [comment]
Yes. Configure 2 integration entities, one for pink, one for black. Both with collection every n days, with period 14 days, with different first date (or you can do even and odd weeks, but these are based on the week number, that resets each year).

**Comment by swin66** [comment]
Thanks for this. I set up 2 entities as described and that's fine.
Although, I have a small problem that if I set the entities to verbose mode, no text is shown. I left the defaults for the formatting etc.
However, ideally I'd like one UI icon to show either a pink bag icon or black one depending on what's coming next. How would I achieve that?
