### ISSUE TITLE
Change langage

### ISSUE THREAD

**Issue by Karine005** [bruxy70/Garbage-Collection#378]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hello, how can I change language for "today" and "tomorrow" ?
Thanks you.

**Comment by bruxy70** [comment]
Do not use verbose state and change the language on the front end. The easiest way is to use the garbage collection custom card I guess. Or make own template.

**Comment by Karine005** [comment]
Thanks, but I'm already in french on the frontend.
How can I do that with the card or with a template ?

**Comment by bruxy70** [comment]
You can use the custom hui markdown card, or custom card templater or custom config template card or custom lovelace template entity row.

**Comment by Karine005** [comment]
Ok, but which code should I write in these cards to have french ? (Excuse me I'm a beginner...)
Thanks.

**Comment by bruxy70** [comment]
In that case I'd suggest using the garbage collection card (available through HACS, that one has translation I think). 
Or if you'd like'd like to learn something new, I explain templates here https://www.youtube.com/watch?v=DCMRjfo723E https://www.youtube.com/watch?v=DCMRjfo723E. The date formatting is one of the examples.
