### ISSUE TITLE
Expire After being optional

### ISSUE THREAD

**Issue by lazodar** [bruxy70/Garbage-Collection#380]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi there, thank you first of all for your work. In the read.me you say that using the 'Expire After' parameter is optional, but I can't seem to work out how not to use it? Leaving it blank results in 00:00 which is still a time right? To clarify, I want to make a sensor that tells me to clean the filters, until I manually press a button to indicate the filters have been cleaned, and then make the sensor calculate the next date to clean them (30 days later) Hope its clear what I'm trying to achieve, that it is possible with this integration. Kind regards...

**Comment by bruxy70** [comment]
It is optional by having a default value. So if you do not configure it, it will automatically expire at the end of the day.
It would be difficult to use it for what you want - the calculated schedule is fixed, and it won't keep moving until you confirm that. I'd use a helper for that.

**Comment by lazodar** [comment]
Ok, I see. Thank you for your answer. I will try to do it some other way.
