### ISSUE TITLE
How can the icons be changed?

### ISSUE THREAD

**Issue by HA-Jon** [bruxy70/Garbage-Collection#381]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I’m trying to use this, so that I can have relevant icons.
Even just staying with mdi icons, how can the colour be set?
![09C572FE-E603-4943-BF67-2B2A3883773D](https://user-images.githubusercontent.com/81836718/160252937-b26d033c-e1d4-466c-9fe2-638baf64bec9.png)
![19BB4E8B-9311-4EA5-A52F-6A021FC1DEEB](https://user-images.githubusercontent.com/81836718/160252939-b052cf6b-aa88-41c2-8bb5-c72787da821c.jpeg)

**Comment by bruxy70** [comment]
I do not think you can set the mdi icons color (only binary sensors do that). Unless you use a custom card.
