### ISSUE TITLE
Include, exclude days no longer in integration setup 

### ISSUE THREAD

**Issue by emes30** [bruxy70/Garbage-Collection#382]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi,

Include/exclude are no longer in integration setup or I am missing something ?
I've setup collection days at the begining of the year and I've just noticed that all my exceptions has gone.
Do I have to add exceptions via blueprints now ?

Mike.

**Comment by bruxy70** [comment]
You have confirmed that you have read the FAQ. Did you?

**Comment by emes30** [comment]
Ok, I've read it now. For me simple things got way to complicated.
