### ISSUE TITLE
How to input large set of dates - exceeds 255 character

### ISSUE THREAD

**Issue by stu1811** [bruxy70/Garbage-Collection#385]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

My town has yard pickup. In May, June, Sept, and Oct it's every week. The rest of the summer it's every other week. My thought was to use the input file but it exceeds 255 character. Any suggestions?

```
2022-04-06
2022-04-13
2022-04-20
2022-04-27
2022-05-04
2022-05-11
2022-05-18
2022-05-25
2022-06-08
2022-06-22
2022-07-06
2022-07-20
2022-08-03
2022-08-17
2022-08-31
2022-09-14
2022-09-28
2022-10-06
2022-10-12
2022-10-19
2022-10-26
2022-11-02
2022-11-09
2022-11-16
2022-11-23
2022-11-30
2022-12-07
```

**Comment by stu1811** [comment]
HA Core throws an error stating it cannot store an entity with more then 255 character

**Comment by bruxy70** [comment]
Ok. There is nothing I can do about the HA limit. So you probably need to make the list shorter. Unless you find some logic in the dates and can fix it with some exceptions.

**Comment by stu1811** [comment]
Do you know if you can you use multiple blueprints simultaneously? ie split the txt file in half and read from both?

**Comment by stu1811** [comment]
One follow-up question. I cut my date list in half for now and I'm trying to use the import text bluerprint but I cannot select the command line templte.

```
sensor:
  - platform: command_line
    command: "cat /share/yard_waste.txt"
    name: yard_waste_pickup
```
![image](https://user-images.githubusercontent.com/12236842/161994989-0c743f18-2ba0-4e90-b0fd-bf80f023dae8.png)


![image](https://user-images.githubusercontent.com/12236842/161993660-4c6457a5-6e5e-4cea-b118-43cebd21bd2c.png)

**Comment by bruxy70** [comment]
Not sure why is that. The import selector uses a comand_line integration, so that should work IMHO. You can remove the integration specification from the blueprint. Then it will show all entities.

**Comment by stu1811** [comment]
That worked.

**Comment by stu1811** [comment]
@bruxy70 I came up with a new solution. Cat the file, remove any dates older than today, and echo the 20 newest dates. I created a script in share with following and called the script from my configuration.yaml.

```
#!/bin/bash                                                                                                                                                                                                                              
new_dates=$(for x in $(cat /share/import_dates.txt); do
                if [[ $(date -d $x +"%y%m%d") -ge $(date +"%y%m%d") ]]; then
                    echo $x
                fi
            done)
echo "$new_dates" | head -n20
```

**Comment by bruxy70** [comment]
This is excellent. Thank you. Will add that to the documentation
