### ISSUE TITLE
Offset dates reverting after HA restart

### ISSUE THREAD

**Issue by ukgaz1987** [bruxy70/Garbage-Collection#387]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Really love this feature but I seem to be having an issue with the date offset. I went through and offset my schedule based on holidays. They all changed fine but then if I restart Home Assistant, the dates revert back to the original dates on reload.

Is it something I am doing wrong that I have missed in the instructions?

**Comment by bruxy70** [comment]
Not sure why that happens. I could imagine that would happen if you called the offset outside the automation triggered by the update. But you say you followed the documentation and read the FAQ, do this is not the case. Not sure how this could happen. The offset is triggered on each update, even after the restart, not sure what's wrong.

**Comment by ukgaz1987** [comment]
Not sure what I had done wrong, I have just worked through it slowly again and seems to be working now, even after HA restarts :) thanks for getting back to me.
