### ISSUE TITLE
Example code for mobile notification to leave out bins

### ISSUE THREAD

**Issue by rosscullen** [bruxy70/Garbage-Collection#388]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Great project and really flexible. Would be great to see an automation example for mobile notifications of when to leave out the bins. Maybe within the automation to acknowledge that the bins have been left out (or ask me later/snooze for x minutes)

### Describe alternatives you've considered

Since the rewrite of the project, I'm not sure that trigger would work best. Maybe x hours after the change of a state?

Thanks

**Comment by bruxy70** [comment]
I made an Automatoins series on my YT channel, and I think I covered this example in the last part https://youtu.be/gPxzutyPmeI

BTW, the state is alwaws changing at midnight. So no point triggering that x hours after state change, you can trigger it at a specific time right away. Just check the state in the condition.
