### ISSUE TITLE
How to Change the Collection Day

### ISSUE THREAD

**Issue by GeorgeIoak** [bruxy70/Garbage-Collection#393]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Our collection day changed from Monday to Wednesday but I can't seem to find how to easily change our collection day. I've had this installed since the YAML days so that got converted from the updates so perhaps that's why I can't find an "edit" option?

**Comment by bruxy70** [comment]
Go to the Integrations under Devices and Services. There is Garbage Collection, select the one you need to change. Then configure, and you can change it...you do not even have to restart, it will update instantly.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/44951610/166983713-f1ad5d9a-e58f-4fef-b270-a564c695750c.png">

**Comment by GeorgeIoak** [comment]
Great, thanks. I knew it had to be hiding somewhere but sometimes I feel like it's a shell game with HA and every update you have to redo or learn a new way...

**Comment by bruxy70** [comment]
In the second step.
