### ISSUE TITLE
"Garbage Collection" does not appear in Integrations panel after installing in HACS

### ISSUE THREAD

**Issue by tylerlucas** [bruxy70/Garbage-Collection#406]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

After installing via HACS, the instructions say to go to Device/Services>Integrations>Add Integration -- however "Garbage Collection" does not appear.

### Configuration

```JSON
N/A -- haven't reached config stage
```

### Debug logs

```shell
N/A -- nothing added to configuration.yaml
```

**Comment by tylerlucas** [comment]
Disregard -- I accidentally installed the frontend card as opposed to integration.

**Comment by tylerlucas** [comment]
After installing the Integration, most of the existing integrations on my dashboard stopped working. All of the broken elements say "Custom element doesn't exist: button-card"

**Comment by bruxy70** [comment]
The integration is a backend thing. It has nothing to do with what shows on your dashboard. Also, the button card is a frontend element. You should see the integration in Configuration/Devices & Services. There you can see the device and the sensor it created. Or you can get there through the developer tools. Or you can see it in the calendar. It won't show on the dashboard automatically. If the dashboard is broken, I suppose this is related to the custom card you installed or uninstalled earlier.

**Comment by snickers2k** [comment]
same here. not showing up under integrations

**Comment by Joshndroid** [comment]
i had to restart it about 5 times before it actually showed up i even started my own issue #402
