### ISSUE TITLE
Holiday Blueprint

### ISSUE THREAD

**Issue by bkr1969** [bruxy70/Garbage-Collection#408]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I have two entities (trash and recycling) on different schedules.  Is there a way to configure the Holiday blueprint to affect both?  When I select the entity in the dropdown, There doesn't seem to be a way to add an additional entity.

**Comment by bruxy70** [comment]
Just create two automatins. One for each entity.
