### ISSUE TITLE
What am I doing wrong that I cannot add a helper?

### ISSUE THREAD

**Issue by WongGendheng** [bruxy70/Garbage-Collection#411]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hey bruxy70, 

thanks for all the work. I have been using the integration for a long time now and it is a great addition to my smart home. In the past I used the "anually" method combined with the "include" functionality. It worked great for me.

Recently, I set up a new instance of HA. Everything is up-to-date. I tried following your instructions for the setup, but am very confused about the "helpers" that I'm supposed to add. No matter how often I restart HA or reinstall the integration, the option to add the "garbage collection" helper does not show up. I also tried reloading with CTRL+SHIFT+R, different browsers and removing my browsers cache.

I ended up adding the integration 4 times (which to be honest feels like the way it is supposed to be done) with manual update enabled and pushed the data with the help of the automations that you provided. But for my sanity's sake... are the instructions wrong or did I mess up somewhere? 

![Configuration](https://user-images.githubusercontent.com/44609253/178146660-b01ab3fe-9b49-45e4-8978-6b0fd5104001.png)
![Helper](https://user-images.githubusercontent.com/44609253/178146675-4f409288-56b2-4e28-88b9-509111d9887b.png)
![Integrations](https://user-images.githubusercontent.com/44609253/178146679-6ffdf0a1-a91f-4d90-b1c2-7043e5a846d4.png)

Cheers Wong

**Comment by bruxy70** [comment]
And you are running the 4.8.0 version?

**Comment by WongGendheng** [comment]
Apparently not. I literally installed it today and there was no update pending (I swear). I checked again after your comment and - of course - there is an update. Sorry for wasting your time. It works now. Cheers
