### ISSUE TITLE
New update broke group sensor

### ISSUE THREAD

**Issue by Anto79-ops** [bruxy70/Garbage-Collection#412]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Hi!

Thanks again for your time and effort here.

Just updated to the new helper system. I had food cart bin that has two different schedules so I create 2 different sensors with the schedules and then created a 3rd group sensor to combine the 2 other sensors.

After the update, I noticed the group sensor was not display properl (null), so when Ichecked the grouped sensor options in the helpers menu, I noticed the two entities were missing. So when I tried to readd the sensors to the group sensor, I get an error:

![image](https://user-images.githubusercontent.com/79593761/178151086-56cc23c9-0304-4b14-a786-d958df4599ba.png)

Any thoughts on this?

### Configuration

```JSON
updated from 4.8
```

### Debug logs

```shell
none that I can see (debug is not enabled).
```

**Comment by Anto79-ops** [comment]
No problem. Let me know if need me to anything.

**Comment by bruxy70** [comment]
fixed in the new release

**Comment by Anto79-ops** [comment]
thank you, sir! that fixed it.

Happy Garbage day to all!
