### ISSUE TITLE
Garbage Collection not visible in Integrations

### ISSUE THREAD

**Issue by hammermcg** [bruxy70/Garbage-Collection#419]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi Vaclav, thanks for the cool integration, I'm using it with the custom-button card in lovelace and looks good and working fine.

One challenge is that though it's installed and working properly I can't see the Integration shown under Integrations.  I added new garbage collection sensors & schedule etc through both Settings > Devices > Helpers page and through Settings > Devices > Integrations page.  But I assume I should be able to see the Integration under the Settings > Devices > Integrations, and hence I can't seem to delete any collections or edit schedules for existing ones?

Any suggestions?  No stress if not, since it is working fine.  Thanks

**Comment by bruxy70** [comment]
That's correct, the helpers do not show  under Integrations, but under the helpers tab. You can manage them from there.

**Comment by bruxy70** [comment]
That's correct, the helpers do not show  under Integrations, but under the helpers tab. You can manage them from there.

**Comment by hammermcg** [comment]
Ok understood and managed to delete old ones from helpers.  Tks

**Comment by hammermcg** [comment]
Thanks
