### ISSUE TITLE
how to edit configuration after initial setup ?

### ISSUE THREAD

**Issue by Vebryn** [bruxy70/Garbage-Collection#423]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi,

I would like to edit initial setup. I find #366 with a screenshoot on how to edit but I'm unable to found it on my HA 2022.08.
I look at helper, device, service, blueprint, just no update button or something else.

How to edit icons, offset, etc. ?

Best regards

**Comment by bruxy70** [comment]
If you have a schedule already configured, you will find in in the helpers. There you can change the configuration.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/44951610/188121577-f77aeb2a-8334-4005-aae3-233d30fdc424.png">

If you did not create a schedule yet, just add a new helper.

Offset is not an option anymore. If you really need to do that, this is possible through an automation blueprint, but it si an advanced option (check documentation)

**Comment by Vebryn** [comment]
I miss this buttons ! Thank you
