### ISSUE TITLE
How-to? First and third Friday every month 

### ISSUE THREAD

**Issue by jankete** [bruxy70/Garbage-Collection#428]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi, is it possible to schedule the "first and third Friday" each month? Even or odd weeks can't be used, because some months have 5 Fridays (like this September).

**Comment by bruxy70** [comment]
Yes, a standard feature. Why don't you try? Select the monthly frequency, then...
(now you know, and if you like it, you can always [buy me a coffee](https://www.buymeacoffee.com/3nXx0bJDP) 😜)

<img width="759" alt="image" src="https://user-images.githubusercontent.com/44951610/192612436-5d8547d0-a257-4df7-a321-00d7f164d389.png">

**Comment by jankete** [comment]
Oh my ... I must have been blind 🙈

Thanks!
