### ISSUE TITLE
Configuration question regarding card-templater

### ISSUE THREAD

**Issue by JimboJamez** [bruxy70/Garbage-Collection#429]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I am trying to follow your directions for setting up a custom card for garbage collection. I am not understanding what the 'sensor.bio' entity is, or where it is derived from:

`type: 'custom:card-templater'
card:
    type: picture-entity
    name_template: >-
      {{ state_attr('**sensor.bio**','days') }} days
    show_name: True
    show_state: False
    entity: **sensor.bio**
    state_image:
      "0": "/local/containers/bio_today.png"
      "1": "/local/containers/bio_tomorrow.png"
      "2": "/local/containers/bio_off.png"
entities:
    - **sensor.bio**`

Are you able to shed some light on this, please?

**Comment by bruxy70** [comment]
In this example, sensor bio is the entity created by the garbage collection helper.
This is not essential for this helper to use, it is just an example to illustrate a possible (advanced) use in a dashboard.
If you find it hard to use, just ignore it.
