### ISSUE TITLE
Date formatting for an annual non-regular schedule

### ISSUE THREAD

**Issue by rumunn95** [bruxy70/Garbage-Collection#430]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

How to format dates if I have several of them in the older version worked like this:
**2022-10-12,2022-11-18,2022-12-14**
in the new version I have a date formatting error ;(

**Comment by bruxy70** [comment]
The annual collection only takes 1 date. It always did, there was never a version that would support multiple dates.
Also, the date shall be in the format mm/dd. Without the year - it will repeat each year.

**Comment by rumunn95** [comment]
Why the older version worked this way for me, I chose annual and entered dates separated by commas because I have a non-regular garbage collection plan and it worked until I updated HA Core to version 10, I had an error downloading calendar data, so I updated the add-on and now I don't know how set it up because I don't have regular waste collection.
Below is the screen as I had it done, unfortunately it is not mine because my settings were lost after updating the add-on
![8c1c0b476252ce597ddec9207c49c3147860a6c1](https://user-images.githubusercontent.com/93547140/194924179-563c80ad-6551-43b8-919d-2e605f10355a.png)

**Comment by qirk4** [comment]
Is there an option where we can do custom dates?
Like A month: 1 time, B month: 2 times...etc

**Comment by bruxy70** [comment]
Yes, there is, using manual update. The blueprint is in the examples included in the documentation.
