### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by mattiabrunello5** [bruxy70/Garbage-Collection#431]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi, i wish to know if its possible to change the language of the month ( maybe edit some file in the repo?)
![1](https://user-images.githubusercontent.com/66752330/195070624-d660cf15-9f59-491f-9070-de312a08d0c3.PNG)

thanks

**Comment by bruxy70** [comment]
The translations are done on front-end (in the user context - in fact, each user can have a different language configured).
The integration runs on the back-end (it only has one state, even if no user is signed in). I think it runs in the system locale, that is English I thing.
And that's the problem with the "Verbose state" - that is done on the back end and it "bakes" it in the state (I think it is conceptually wrong and I should have rejected that, but it is done, many people use it and it would be hard to remove it).

So from the above, I'd render this human-readable state in the dashboard. Then it will run in the user context and should respect the language you have set-up for the user.
