### ISSUE TITLE
Garbage Collector causes HA to hang in some cases

### ISSUE THREAD

**Issue by mackowskim** [bruxy70/Garbage-Collection#433]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Hi,
First of all, thanks for this integration!

I have an issue when I try to set up monthly collection on first Monday or Thursday of the month (depends which comes first).
So I tried this helper setup:
1. MONTHLY collection

2. Collections days: Mon, Thu
3. First day of the month
4. Then the last option (which I suppose means whichever comes first in the first week of the month)
![obraz](https://user-images.githubusercontent.com/45004433/196414838-f78b27b2-5211-4c65-9e2d-445628954174.png)

Whan I click Apply it shows just SUCCESS and my entire HA instance hangs. Calendar stops working and HA stops responding.
After restart, the new helper won't appear

### Configuration

```JSON
No helper created for the given case
```

### Debug logs

```shell
Nothing relevant in the log:


2022-10-18 13:44:09.574 DEBUG (MainThread) [custom_components.garbage_collection] Setting Śmieci kolorowe (monthly) from ConfigFlow
2022-10-18 13:44:09.575 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.garbage_collection
2022-10-18 13:44:09.576 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Śmieci kolorowe) Calling update
```

**Comment by bruxy70** [comment]
Ok, thanks. Confirmed. Will look at this.
The last option is IMHO a weird option that means it will not look for 1st Monday or Thursday in the month, but it will always take Monday and Thursday of the 1st week of the month (meaning it has at least 1 day in that month).
So it could be, that if 1st of the month is on Tuesday, it will take the Monday 31st as the 1st Monday of the month.
I think it is weird, but there are apparently some countries where this is common.

If you configure Monday and Thursday, it will always register both Monday and Thursday, not whichever comes first. If you want to do what you describe, I guess you'd have to do it through a manual update automation - go for Thursday, and if the date is 4th (so Monday was 1st), then move it to Monday (offset it by -3)

**Comment by mackowskim** [comment]
Thanks for your update.
So what if the month starts from Saturday?
Then Monday is 3rd and Thursday is 6th.
Would you be so kind and send me manual config that would work?

**Comment by bruxy70** [comment]
In that case, it will schedule the collection on 3rd and 6th.
So if I understand what you want to do, configure it for Thursday only.
Enable manual update.
Then create an automation based on documentation, checking all the dates and if the day is == 4, call the offset.
If this is too complicated for you, then just forget it and deal with the two dates, Monday and Thursday. Or pick one of the two.
