### ISSUE TITLE
Unable to change includes done on previous versions

### ISSUE THREAD

**Issue by przemoc86** [bruxy70/Garbage-Collection#435]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi,

I was looking for this option few hours and I cannot find. I've put dates for whole 2022 with old version via Integration board. Now, I'm adding through blueprints. But I still have those old includes which are wrong (schedule for second part of the year has been changed). Is there any options to remove those old includes done with previous integration version?
Thanks in advance

**Comment by bruxy70** [comment]
The legacy deprecated configuration is removed automatically by the integration. And the setting does not even exist in the configuration dialogue. So I am not sure where you might have them.

**Comment by przemoc86** [comment]
There are still visible in calendar.garbage_collection
![2022-11-04 08_45_31-Calendar – Home Assistant – Opera](https://user-images.githubusercontent.com/62384501/199920089-e1a898a3-c61f-4041-97b5-465482502d13.png)

For example on a screen "Selektywne" on 11 and 12 of November, when in Blueprint I'm adding only 12. 
![2022-11-04 08_47_40-Settings – Home Assistant – Opera](https://user-images.githubusercontent.com/62384501/199920608-4178dc6d-995d-47aa-acf7-26848f866336.png)

But I solved how to do it ;) Sometimes it's really good to leave something and go to sleep :D I've used Your exclude blueprint and I'm just adding those old bad dates to remove them. And from 2023 it won't be needed. But for now workaround is working
![2022-11-04 08_53_53-Calendar – Home Assistant – Opera](https://user-images.githubusercontent.com/62384501/199921303-e832b89d-8daf-456e-9977-608efd21dcea.png)

**Comment by bruxy70** [comment]
Right. I have no idea how it got in. Even if the configuration was not removed, the integration does not have the logic to process that. So the configuration would be ignored. Isn't it possibly coming from the standard helper configuration (e.g. annual/monthly etc?). Anyhow, glad you solved it.
