### ISSUE TITLE
cannot import name 'CalendarEventDevice' 

### ISSUE THREAD

**Issue by Marmoulak** [bruxy70/Garbage-Collection#436]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Hi
Thanks for your useful integration. 

I get this error
Unable to prepare setup for platform garbage_collection.sensor: Platform not found (cannot import name 'CalendarEventDevice' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).

info: Home Assistant 2022.11.1 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221102.1 - latest 
Can you help?

### Configuration

```JSON
I can not access it. something is wrong.
```

### Debug logs

```shell
2022-11-05 23:13:47.803 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform garbage_collection.sensor: Platform not found (cannot import name 'CalendarEventDevice' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).
```

**Comment by bruxy70** [comment]
Is this a new install or did it work before and then it stopped?
I am unable to replicate it, it works and does not show the error both on my production and test. Let's see if more people have the issue, to find some commonalities perhaps.

**Comment by Marmoulak** [comment]
it worked perfectly before. I got the error after updates. 
I have tried to uninstall and install it again but didn't help. 
I can not see src folder under usr anymore. Could be that?
/usr/src/homeassistant/homeassistant/components/calendar/init.py

**Comment by bruxy70** [comment]
The calendar component should be part of the home assistant core I think, looking at the GitHub, I think you might be right, it should be there https://github.com/home-assistant/core/tree/dev/homeassistant/components/calendar
But I use HA OS type of install, so I cannot verify.

**Comment by marianbezeg** [comment]
Running on same version without issue.

Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3

I'd same error after upgrade of HA to newest version with this component installed manually before upgrade.
Now I've installed it via HACS and its running without any issues.

**Comment by Marmoulak** [comment]
as I see now in documentation "The configuration via configuration.yaml has been deprecated"  and all my code are in configuration.yaml.
according to documentation: Go to Settings/Devices & Services/Helpers, click on the + CREATE HELPER button, select Garbage Collection and configure the helper.
I have uninstall and install it again. But I do not se in the Helper any Garbage Collection. se picture
![image](https://user-images.githubusercontent.com/44494190/201766105-2c898acd-c83f-46f3-b2af-5f6ff055424a.png)
and if I add it via Add integration it seems strange. see her:
![image](https://user-images.githubusercontent.com/44494190/201766503-9278421d-2634-44e5-b43a-6a6410b9647b.png)
