### ISSUE TITLE
Just the first day of collection is shown in calendar

### ISSUE THREAD

**Issue by Corrado-possieri** [bruxy70/Garbage-Collection#437]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi,
I configured the helpers as suggested in the documentation but just the first day of collection is shown in calendar and in the countdown. Am I doing something wrong?

**Comment by bruxy70** [comment]
Probably. Mine shows all of them (for the current and the following year anyhow).
<img width="875" alt="image" src="https://user-images.githubusercontent.com/44951610/201029667-019524b7-f5e7-4232-9c95-51a1d4fff3a1.png">
