### ISSUE TITLE
The sensor. is showing wrong values if there is no any schedule in future

### ISSUE THREAD

**Issue by marianbezeg** [bruxy70/Garbage-Collection#438]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Sensor is showing that next schedule will be in 54 days. But there is no future schedule ("Next date") for this sensor.

![image](https://user-images.githubusercontent.com/25847353/201056756-62868bcc-eddc-46b4-ad4a-75aee4c9ca65.png)

### Configuration

```JSON
alias: Include dates - Nebezpečný odpad
description: ""
use_blueprint:
  path: bruxy70/include.yaml
  input:
    garbage_collection_entity: sensor.nebezpecny_odpad
    include: |-
      2022-02-28
      2022-08-24


Sensor is configured as "blank" with manual update.
```

### Debug logs

```shell
2022-11-10 10:49:09.061 DEBUG (MainThread) [custom_components.garbage_collection] Setting Nebezpečný odpad (blank) from ConfigFlow
2022-11-10 10:49:19.696 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Nebezpečný odpad) Calling update
2022-11-10 10:49:19.696 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Nebezpečný odpad) Dates loaded, firing a garbage_collection_loaded event
2022-11-10 10:49:19.965 DEBUG (MainThread) [custom_components.garbage_collection] called add_date 2022-02-28 from sensor.nebezpecny_odpad
2022-11-10 10:49:20.120 DEBUG (MainThread) [custom_components.garbage_collection] called add_date 2022-08-24 from sensor.nebezpecny_odpad
2022-11-10 10:49:20.171 DEBUG (MainThread) [custom_components.garbage_collection] called update_state for sensor.nebezpecny_odpad
2022-11-10 10:49:20.172 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Nebezpečný odpad) Looking for next collection
```

**Comment by bruxy70** [comment]
I have just configured it with the same blueprint and dates, and this is what I get:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/44951610/201077006-3ddea650-c385-4311-a204-0256e687eeb6.png">

**Comment by bruxy70** [comment]
<img width="444" alt="image" src="https://user-images.githubusercontent.com/44951610/201077235-dd6a28d6-9734-483b-81e7-bab20204d4ef.png">

**Comment by marianbezeg** [comment]
I've checked my sensor and its almost same.
![image](https://user-images.githubusercontent.com/25847353/201088739-1d017d61-3589-4be0-9832-6258b8b52951.png)
There is nothing in calendar in next year. I see that you have number 2 there as well. Shouldn't this be something like no schedule, N/A etc. ?

**Comment by bruxy70** [comment]
I will see if I can change that without breaking things.

**Comment by marianbezeg** [comment]
Looks like there is another issue with same thing. After the last scheduled date state is always today...

![image](https://user-images.githubusercontent.com/25847353/202922612-de620be5-9367-4019-a9b9-5a313d57588d.png)

**Comment by marianbezeg** [comment]
Me again, i edited code to fix this issue. I dont know if this is  correct approach but at least its working for me :) 

![image](https://user-images.githubusercontent.com/25847353/202924351-1955b5fc-0cfa-4bdf-ba66-eb5054187b90.png)
![image](https://user-images.githubusercontent.com/25847353/202924364-16f42362-4db3-4550-b6bc-00f16e1855ac.png)
![image](https://user-images.githubusercontent.com/25847353/202924391-471f2608-69cc-466c-90f3-1b2690657bcf.png)

**Comment by bruxy70** [comment]
Thanks for the find. I did not really expect this condition, but you are right that with the blank and no dates added it could happen. So I added the code to set the state and next date to None. Check the latest release if it helps. If yes, please close the ticket.

**Comment by marianbezeg** [comment]
@bruxy70 well, it looks like that now its working correctly. 

Maybe last  thing is  to keep icon to "self._attr_icon = self._icon_normal" if there is no schedule as now there is no icon for the sensor. I assume that one from configured helper should be visible, but maybe its only how I see this thing 😄 

![image](https://user-images.githubusercontent.com/25847353/203032129-a6c26ed0-9cff-4db5-a9ed-14e9870e6b2f.png)
