### ISSUE TITLE
Add Frequency "Last [day] of Month" to options.

### ISSUE THREAD

**Issue by Vato9394** [bruxy70/Garbage-Collection#440]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Is your feature request related to a problem? Please describe.

Sometimes, garbage collectors come and collect the garbage for example the last Monday of the month.
If you choose Monthly, you can only choose the number week in that month.
Sometimes, the last Monday of the month is in the 4th week, sometimes in the 5th week.

### Describe the solution you'd like

I would Like to have the option "last [day] of Month" in the collection frequency selector.

### Describe alternatives you've considered

I tried some templates, but It would be Nice if it is build in.

**Comment by bruxy70** [comment]
For that, the solution is to choose the first Monday of the month and offset it by 1 week back. I do not intend to further complicate the configuration by adding more configuration options.

**Comment by Vato9394** [comment]
Thanks for the explanation. makes sense!
