### ISSUE TITLE
Skip Weekends / Only weekends

### ISSUE THREAD

**Issue by karldonteljames** [bruxy70/Garbage-Collection#446]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Good evening. I've been using this for a while to help my children track their chores and it works really well, so thank you so much for that!

My question is if is possible to have an option for every n-days, but skip weekends and conversley everyday but skip weekdays. (so child 3 does the chore both days at the weekend, and the weeks it is every other day, i.e if child 1 did it Friday, it would be the turn of child 2 the following Monday. - In this case we are talking about the dishwasher. 😄 

Thanks in advance.

**Comment by bruxy70** [comment]
Yes, this can be done, but you'd have to configure it for a manual update, and set-up an automation triggered by the update, iterate through all the calculated dates, check whether they fall on weekend, and move the dates if they do.
Other thing to think about is, whether you want all the dates following this "correction" move to the original schedule, or start counting from this moved date. If the second, it might be easier starting from a blank frequency, and create the schedule by the automation (also on manual update).
If you are not experienced with automations, that might be hard thought, this is quite an advanced technique (that makes this quite specific scenario possible though).
