### ISSUE TITLE
Annual date format

### ISSUE THREAD

**Issue by MarcinKnD** [bruxy70/Garbage-Collection#448]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

What is a correct format to set annual dates?

I tried format : 2023-05-05,2023-06-08 and 05/05,06/08 and both have format error. 
Single date in format 05/05 is ok, but how to input few dates? what is correct format to separate dates?
![2023-01-02 (2)](https://user-images.githubusercontent.com/37018109/210210198-32860895-c4d5-4c81-9324-fdfcd4dfd521.png)
![2023-01-02 (3)](https://user-images.githubusercontent.com/37018109/210210185-643e076b-82f8-429b-9c46-c48c2b9f46db.png)

**Comment by bruxy70** [comment]
Annual calendar is for events that re-occur once a year at the same date. So it is configured the way you describe, without the year.
What you try to do could be done with a manual update, but it is too complicated.
I suggest you use the Home Assistant built-in calendar, it does it all.
