### ISSUE TITLE
Add Exceptions & Anomaly Collections

### ISSUE THREAD

**Issue by Danirali** [bruxy70/Garbage-Collection#451]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Is your feature request related to a problem? Please describe.

Add a feature where you can add exceptions like bank holidays, to compensate for bank holidays anomaly collection dates be added. 

e.g. Exceptions ignore a collection
1 Jan (Holiday) -> 4 Jan (Alternate date)

### Describe the solution you'd like

Ignoring set dates and adding out-of-schedule dates

### Describe alternatives you've considered

Even adding out-of-dates collection would allow my automations to run smoothly.

**Comment by bruxy70** [comment]
This feature has been removed, and replaced by an option to control the dates with automations. There are few blueprints that can be used and modified based on different requirements.
