### ISSUE TITLE
Calendar replacement

### ISSUE THREAD

**Issue by tomlut** [bruxy70/Garbage-Collection#454]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Sad to see that this integration is being depreciated as it made it very simple to create template binary sensors like this to control display of picture card reminders in my dashboards:
```
- name: "Garbage Today"
  icon: "mdi:trash-can"
  state: "{{ is_state('sensor.waste', '0') }}"

- name: "Garbage Tomorrow"
  icon: "mdi:trash-can"
  state: "{{ is_state('sensor.waste', '1') }}"

- name: "Recycling Today"
  icon: "mdi:recycle"
  state: "{{ is_state('sensor.recycling', '0') }}"

- name: "Recycling Tomorrow"
  icon: "mdi:recycle"
  state: "{{ is_state('sensor.recycling', '1') }}"
```

Assuming I created a local calendar with repeating dates for recycling and garbage collection, how would I update theses template binary sensors so that they continue to function?

**Comment by bruxy70** [comment]
There is no need for such templates in the local calendar, this is directly in the entity state. Plus you can trigger automations through events.

**Comment by tomlut** [comment]
Events are of zero use when using conditional cards. I need a state.

**Comment by bruxy70** [comment]
you can set an entity value with a trigger

**Comment by tomlut** [comment]
So triggered binary sensors.

Seems a lot less of an elegant solution, especially when events overlap, as I understand it, requiring seperate calendars.
