### ISSUE TITLE
frontend disappiar after clicking

### ISSUE THREAD

**Issue by Destroyer061090** [bruxy70/Garbage-Collection#455]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I clicked several time on the icon and after a while it completly disappear the UI... i was think the reason why was the setting "hide_before" but even delete it it never come back... i tried also to re-install everithing but nothing fix this issues. any idea?

**Comment by bruxy70** [comment]
Not sure. The integration does not really do anything with the front end. All it does is, it sets the entity state and attributes.

**Comment by bruxy70** [comment]
Looking at the template, I think it should be `states`, not `state`. Always a good idea testing templates in Developer Tools - I do that as well.
If this does not fix it, I suggest you open the issue with the custom card. This repo is for the helper (back end).
