### ISSUE TITLE
Bin Collection on last Thursday of the month

### ISSUE THREAD

**Issue by benjani85** [bruxy70/Garbage-Collection#456]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I've read through the readme but can't seem to find an answer for my use case. I have a garden waste bin that gets collected on the last Thursday of every month. In the configuration I can select the Nth week but some months have 4 Thursdays and others 5 Thursdays. Is there a way to achieve what I'm after that I've maybe missed?

**Comment by bruxy70** [comment]
https://github.com/bruxy70/Garbage-Collection#offset

**Comment by benjani85** [comment]
That's perfect thank you!
