### ISSUE TITLE
biennial ( Every two years ( 730 days )

### ISSUE THREAD

**Issue by niighthawk** [bruxy70/Garbage-Collection#457]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

how to make something happens every 2 years ( biennial ) ?

i Tried the Every-n-days ( 1-1000 jours but I always ending with a Unknow State ) when i go under 366 ( 365 ) the days are working again

**Comment by niighthawk** [comment]
![image](https://user-images.githubusercontent.com/30214804/229385735-6c53f7a6-ba77-40ca-aab5-d18b7ef3e39c.png)
![image](https://user-images.githubusercontent.com/30214804/229385752-a212afd5-aeb4-4221-86d2-412e45e11178.png)

**Comment by bruxy70** [comment]
The integration does not support 2 years. I'd go for a different solution, such as local calendar.
