### ISSUE TITLE
Can't modify include_ or exclude_dates via Config Flow

### ISSUE THREAD

**Issue by 1DontEx1st** [bruxy70/Garbage-Collection#46]
I might be missing it, but is it not possible to change include/exclude days once the sensor exists?

**Comment by bruxy70** [comment]
Go to Configuration/Integrations, select the sensor and then settings (top left corner).
![image](https://user-images.githubusercontent.com/44951610/69738919-17e55380-1137-11ea-9523-6fde0825f5ba.png)

**Comment by mrpeaches87** [comment]
i am trying to set an include and exclude for the holiday this week with the config flow and it seems to be ignoring it, still displaying my chosen day of the week as the next pickup. doesn't seem to change with newly created or editing an existing sensor.

**Comment by bruxy70** [comment]
Thanks. I see, will look at that. Looks lile adding the timezone broke quite a few things ....

**Comment by bruxy70** [comment]
@mrpeaches87 , did the release 2.6 fix that? Thanks!

**Comment by mrpeaches87** [comment]
i switched to yaml mode and it's still a day off. the update didn't help with this particular issue.

is the next date field supposed to have the full time in it? the date of this pickup is supposed to be 12-20
```
next date
2019-12-19T19:00:00-05:00
```

**Comment by bruxy70** [comment]
No, it is supposed to be just the date in ISO format.
Ok, it became quite messy with all the attempts to add timezone all around the place.
So, here is an attempt to fix that, I am going back where it started (using just date, without the time), but this time I am taking the current date from HA, which should be in the right timezone.
Can you @mrpeaches87, @lockyt, and @aolley do me a big favor, grab the development branch and try if it still works? It seems to work here, but I am only 1 hour from UTC. I have tried to change my timezone to try that, but it is apparently not that simple.
Thanks

**Comment by aolley** [comment]
Using the current development branch, I get a next date of:
2019-12-02T10:30:00+10:30

That should read 2019-12-02T00:00:00+10:30.

Putting myself back on v2.5, and I get the correct timestamp.

**Comment by bruxy70** [comment]
Ok, get it. Made one more change. Now it should render what you expect. 
Does that work? Or I can do it without TZ, so it would read 2019-12-02T00:00:00.

**Comment by mrpeaches87** [comment]
working great now on the dev branch!

**Comment by bruxy70** [comment]
Solved by release 2.7
