### ISSUE TITLE
How do i delete an entry

### ISSUE THREAD

**Issue by jonny190** [bruxy70/Garbage-Collection#460]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I have no integration listed on the integrations page, cannot delete the device and ive tried reinstalling but nothing

**Comment by jonny190** [comment]
Any Ideas?

**Comment by bruxy70** [comment]
I think this is a general question - once you remove the integration, then the integration is not there to do anything anymore. So the best is to remove the entities first, before removing the integration. If you missed, I think you should be able to go to the entitities and remove them from there.
