### ISSUE TITLE
Features in local calendar

### ISSUE THREAD

**Issue by Protoncek** [bruxy70/Garbage-Collection#463]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi!
I'm very sad for end of support for this card... i'm exploring HA's "local calendar", but first impressions are that not all features of your card are there... one of them is this: i can only see event, which will trigger first, not others (in 'calendar.my_calendar' sensor). 
An example: i have three containers: yellow, brown and black. With your addon i can see days until "trash removal" for all three, with local calendar i can only see days for container which comes next...
As usuall in HA documentation, original "local calendar" is explained very scarse in HA... 
is there any way to see similar with local calendar?

**Comment by bruxy70** [comment]
I think you can see all of them in the calendar. If this is something that is needed, I am quite sure that sooner or later someone will make a script for that. But I do not think they are available in any entity state at this moment.

**Comment by Protoncek** [comment]
Yes, i can see them, correct. I guess i’ll dig some more on gogole to see if any solution has come up. I did find an addon, but it’s only for google calendar, not local one. 
thanks!

**Comment by AngloYorkshire** [comment]
I am very upset to see this removed - wish it could have just stayed there.
This was a great way showing when your garbage was due especially with the pictures.
I hopethe same sort of thing can be done with a calendar and showing the picture change colour as well as showing how many days to go.
So disappointed :-(

**Comment by bschatzow** [comment]
I agree that it is more difficult now but understand the reason it was removed. Now we need to figure out how to get the same results a different way. So far, I am not close.

**Comment by stboch** [comment]
My issue is local calendar does not have a service for updating and existing calendar event, IE for slide and offset events. This integration allowed me to move away from a google calendar, I hope that HA can close the gaps on the features or at least this integration doesn't break with another update.

**Comment by goofy7264** [comment]
don't forget you can always fork this project and adding your fork'd repo to hacs as a manual repo (or install manually) .  Yes, there is a risk that a breaking change will cause it to stop working down the road, but either you can fix it yourself, or at least you've kicked the can down the road for now,.

**Comment by karldonteljames** [comment]
> Yes agree, so sad that you decide to remove this integration @bruxy70 , it's a nice integration, almost the most usefull i have in HA in the bunch of integrations...AND the calendar doesn't provide sensors...

This is an issue I'm having too. Having sensors like Mum_Dishwasher, Dad_Bins, and Child_FeedPets Is really useful, and I have a number of automation based on those sensors outputting "Today" Is there any way to achieve something similar with the Local Calendar?

**Comment by bruxy70** [comment]
Definitely. The calendar state becomes 'on', so simple.
I also made a video about simple templates to calculate days till the next event, so there you can automate a day before for example.

**Comment by karldonteljames** [comment]
I've managed to get both Grocy and Todoist integrated into HA, however, neither of these give the simple setup, yet complex functionality that was provided by this plugin.

I've set up a weekly schedule for two chores and three people, which in this plugin gave me three sensors and an output of today, tomorrow, or a date. I now have one sensor with lots of data in, and doesn't actually show if it is active today or not.

sensor.grocy_chores:
state_class: measurement
chores: 
- id: 1
  name: Dad - Bins - Week 1
  description: Dad - Bins - Week 1
  period_type: weekly
  period_config: monday,tuesday,wednesday,thursday,friday,saturday,sunday
  period_days: 1
  track_date_only: true
  rollover: false
  assignment_type: in-alphabetical-order
  assignment_config: '1'
  next_execution_assigned_to_user_id: 1
  userfields: null
  last_tracked_time: null
  next_estimated_execution_time: '2023-05-22T23:59:59'
  last_done_by: null
  track_count: 0
  next_execution_assigned_user:
    id: 1
    username: admin
    first_name: null
    last_name: null
    display_name: admin
- id: 2
  name: Dad - Bins - Week 2
  description: Dad - Bins - Week 2
  period_type: weekly
  period_config: monday,tuesday,wednesday,thursday,friday,saturday,sunday
  period_days: 1
  track_date_only: true
  rollover: false
  assignment_type: in-alphabetical-order
  assignment_config: '1'
  next_execution_assigned_to_user_id: 1
  userfields: null
  last_tracked_time: null
  next_estimated_execution_time: '2023-05-29T23:59:59'
  last_done_by: null
  track_count: 0
  next_execution_assigned_user:
    id: 1
    username: admin
    first_name: null
    last_name: null
    display_name: admin
- id: 3
  name: Mum - Dishwasher - Week 1
  description: Mum - Dishwasher - Week 1
  period_type: weekly
  period_config: monday,tuesday,wednesday,thursday,friday,saturday,sunday
  period_days: 1
  track_date_only: true
  rollover: false
  assignment_type: in-alphabetical-order
  assignment_config: '1'
  next_execution_assigned_to_user_id: 1
  userfields: null
  last_tracked_time: null
  next_estimated_execution_time: '2023-05-22T23:59:59'
  last_done_by: null
  track_count: 0
  next_execution_assigned_user:
    id: 1
    username: admin
    first_name: null
    last_name: null
    display_name: admin
- id: 4
  name: Mum - Dishwasher - Week 2
  description: Mum - Dishwasher - Week 2
  period_type: weekly
  period_config: monday,tuesday,wednesday,thursday,friday,saturday,sunday
  period_days: 1
  track_date_only: true
  rollover: false
  assignment_type: in-alphabetical-order
  assignment_config: '1'
  next_execution_assigned_to_user_id: 1
  userfields: null
  last_tracked_time: null
  next_estimated_execution_time: '2023-05-29T23:59:59'
  last_done_by: null
  track_count: 0
  next_execution_assigned_user:
    id: 1
    username: admin
    first_name: null
    last_name: null
    display_name: admin
- id: 5
  name: Child1 - Fridge, Pets, Livingroom - Week 1
  description: Child1 - Fridge, Pets, Livingroom - Week 1
  period_type: weekly
  period_config: monday,tuesday,wednesday,thursday,friday,saturday,sunday
  period_days: 1
  track_date_only: true
  rollover: false
  assignment_type: in-alphabetical-order
  assignment_config: '1'
  next_execution_assigned_to_user_id: 1
  userfields: null
  last_tracked_time: null
  next_estimated_execution_time: '2023-05-22T23:59:59'
  last_done_by: null
  track_count: 0
  next_execution_assigned_user:
    id: 1
    username: admin
    first_name: null
    last_name: null
    display_name: admin
- id: 6
  name: Child1 - Fridge, Pets, Livingroom - Week 2
  description: Child1 - Fridge, Pets, Livingroom - Week 2
  period_type: weekly
  period_config: monday,tuesday,wednesday,thursday,friday,saturday,sunday
  period_days: 1
  track_date_only: true
  rollover: false
  assignment_type: in-alphabetical-order
  assignment_config: '1'
  next_execution_assigned_to_user_id: 1
  userfields: null
  last_tracked_time: null
  next_estimated_execution_time: '2023-05-29T23:59:59'
  last_done_by: null
  track_count: 0
  next_execution_assigned_user:
    id: 1
    username: admin
    first_name: null
    last_name: null
    display_name: admin

count: 6
unit_of_measurement: Chore(s)
icon: mdi:broom
friendly_name: Grocy chores

**Comment by karldonteljames** [comment]
I assume these 'true' 'false' states, and individual sensors that were in garbage collection are unlikely to be merged into the calendar in the same way as they used to work?

**Comment by bruxy70** [comment]
Definitely not. The calendar state is standard and consistent with other integrations. The garbage collection was an inconsistent exception. But it can be easily done through templates.

**Comment by karldonteljames** [comment]
could you possibly give me an example of how i can create a template sensor for this particular setup, please?

**Comment by bruxy70** [comment]
https://youtu.be/RpwAhy7f52I

**Comment by karldonteljames** [comment]
Thank you for the video. it's really helpful, and I'll start to migrate my automation over. However looking at this, doesn't this require a calendar for each collection or chore though?

**Comment by bruxy70** [comment]
I have a script doing automatic offset for holidays and holidays in week using local calendars. Will make a video about that hopefully over the weekend. It is not ideal, but I'd call it a good start.
