### ISSUE TITLE
How to remove your HACS Correctly

### ISSUE THREAD

**Issue by thorrrr** [bruxy70/Garbage-Collection#464]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

HI 
Please could you help by doing a post or a video or even reply here  on how to get your HACS integration out f HA correctly.
I have tried and keep getting errors saying code needs stripping out of your config.yml file but i have none.
I just need the correct process on how to remove please. YOu have extensive docs to show how to install but zero on how to remove!
It is a shame you removing it i thought it was very good. I watched your video it is a lot more complicated to get it working to the same level of your integration.  But i guess it stops you having to maintain it so i get it

**Comment by AngloYorkshire** [comment]
MIne removed ok but the calendar is still showing under Calendars. How do I remove the calendar?

**Comment by ilsalgo** [comment]
> 

same for me :(

**Comment by ilsalgo** [comment]
> MIne removed ok but the calendar is still showing under Calendars. How do I remove the calendar?

same for me :(

**Comment by pico1881** [comment]
I solved it by creating a local calendar with the same name "Garbage collection" and then I deleted it

**Comment by ilsalgo** [comment]
> I solved it by creating a local calendar with the same name "Garbage collection" and then I deleted it

Top!! thank you :)

**Comment by papinist** [comment]
> I solved it by creating a local calendar with the same name "Garbage collection" and then I deleted it

Tried that and ended up with two calendars called "Garbage collection" :-O In my case deleting it won't remove the old one.

**Comment by Deanosim** [comment]
Well I've managed to remove the Calender by creating one with the same name.
But i've got other errors.
![image](https://user-images.githubusercontent.com/4834976/236662879-8dba128e-edbc-4cd6-8bc9-fe05fc97eb49.png)

**Comment by papinist** [comment]
When I create a new calendar named "Garbage collection" it is created with identifier "garbage_collection_2" because "garbage_collection" already exists.

**Comment by lasry1** [comment]
in my case I had 2 helpers that gave me errors if I removed the integration without removing them.
To delete the calendar I have done was someone said above, create a local one with the same name and then delete it.

**Comment by marvin8** [comment]
I'm getting the same error as https://github.com/bruxy70/Garbage-Collection/issues/464#issuecomment-1537337369

I haven't worked out yet where the reference to the no longer existing `setup.py` is coming from.

**Comment by lasry1** [comment]
add again the repo, install an old version and then uninstall it. that helped me

**Comment by marvin8** [comment]
Thanks @lasry1  That worked for me.

For anyone else trying it, make sure to delete any related helpers first, before uninstalling GC again.

**Comment by papinist** [comment]
I finally managed to remove it.. thanks to your suggestions!
This is the steps I've taken:

- reinstall Garbage collection repo from hacs and reboot
- remove helpers I created in the past
- remove Garbage collection repo and reboot
- still have the calendar but with an error: "can't retrieve events for calendar Garbage collection" so I created a new local calendar with the same name ("Garbage Collection"), checked that the error was gone, and remove local calendar

And finally it's gone :)

**Comment by Deanosim** [comment]
Yep that was it for me, just had to properly remove all the related stuff fully and then restart Home Assistant and the setup.py error went away. and I can't find any remaining traces of GC left, thanks for the suggestions everyone. :)

**Comment by elderec** [comment]
I was able to remove by:

- Remove Garbage Collection from HACS
- Restart HA
- Remove configured Garbage Collection Integrations
- Restart HA

Calendar is gone and no more errors in HA startup log.

**Comment by cobradodo** [comment]
> Well I've managed to remove the Calender by creating one with the same name. But i've got other errors. ![image](https://user-images.githubusercontent.com/4834976/236662879-8dba128e-edbc-4cd6-8bc9-fe05fc97eb49.png)
Hi,
i have the same problem.
it is not possible to reinstall an old version

**Comment by maxwood** [comment]
> > Well I've managed to remove the Calender by creating one with the same name. But i've got other errors. ![image](https://user-images.githubusercontent.com/4834976/236662879-8dba128e-edbc-4cd6-8bc9-fe05fc97eb49.png)
> > Hi,
> > i have the same problem.
> > it is not possible to reinstall an old version

Same issue here

**Comment by cobradodo** [comment]
> > > Well I've managed to remove the Calender by creating one with the same name. But i've got other errors. ![image](https://user-images.githubusercontent.com/4834976/236662879-8dba128e-edbc-4cd6-8bc9-fe05fc97eb49.png)
> > > Hi,
> > > i have the same problem.
> > > it is not possible to reinstall an old version
> 
> Same issue here
> 
> Edit: Fixed it, just went through integrations, devices, entities and deleted anything that referenced Garbage Collection. Restarted HA - done :)

I had to get rid of the entities by editing the core.config_entries file
