### ISSUE TITLE
Request to be re-enabled this integration

### ISSUE THREAD

**Issue by cjramseyer** [bruxy70/Garbage-Collection#467]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

While I fully understand the intent to move the users of this integration to the HA local calendar, the local calendar doesn't fit the abilities of this integration.

Waste, Recycling, Yard waste, etc. is not simply a recurring appointment.  It also varies in scheduling based on holidays, or time of year (where we live, yard waste is only picked up during spring through fall).  Any changes during holidays are likely to vary by country or other factors, which the HA local calendar does not currently support doing automatically.

I have already forked the repository, and, if necessary will look at re-activating this integration via my own repo.  I have no desire to take away from the original author, and all the hard work that has gone into this integration, but my setup will simply not function using the current abilities of the local HA calendar.

I would appreciate some feedback and follow-up on this request at the next convenience.

**Comment by bruxy70** [comment]
No issues, go ahead. Or I can make you an author on the original repo if that works for you.

**Comment by bruxy70** [comment]
I have a script doing automatic offset for holidays and holidays in week using local calendars. Will make a video about that hopefully over the weekend. It is not ideal, but I'd call it a good start.

**Comment by cjramseyer** [comment]
> No issues, go ahead. Or I can make you an author on the original repo if that works for you.

I will leave this entirely up to you.  I need to come up to speed on building HA custom integrations, and I don't expect there to be too much to do to maintain this.

**Comment by bruxy70** [comment]
Well, in such a case, I'd start with more simple one. Sooner or later they will make a breaking change, and you'll have to fix this. And you'll be quite under pressure. But I will add you as collaborator to this project. Will see.

**Comment by cjramseyer** [comment]
Thank you for the invitation.  I look forward to seeing what we can do with this.
