### ISSUE TITLE
Not able to create sk.json

### ISSUE THREAD

**Issue by misa1515** [bruxy70/Garbage-Collection#474]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Not able to create sk.json (screenshot attached)

![image](https://github.com/bruxy70/Garbage-Collection/assets/61636045/a5864a23-fc83-421b-a55c-67f6f26664d3)

### Configuration

```JSON
.
```

### Debug logs

```shell
.
```

**Comment by cjramseyer** [comment]
Inability to create a json file is not a Garbage Collection issue.
