### ISSUE TITLE
integration 'garbage_collection' calls async_forward_entry_setup - is deprecated and will stop working in Home Assistant 2025.6

### ISSUE THREAD

**Issue by misa1515** [bruxy70/Garbage-Collection#475]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Logger: homeassistant.helpers.frame
Zdroj: helpers/frame.py:184
Prvýkrát sa vyskytol: 23:17:52 (17 výskytov)
Naposledy prihlásený: 23:18:24

Detected that custom integration 'garbage_collection' calls async_forward_entry_setup for integration, garbage_collection with title: Komunálny odpad and entry_id: 820d7188e79abf5f8777ee91d3ae1bf7, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/garbage_collection/sensor.py, line 176: await self.hass.config_entries.async_forward_entry_setup(, please create a bug report at https://github.com/bruxy70/Garbage-Collection/issues

### Configuration

```JSON
not relevant
```

### Debug logs

```shell
not relevant
```

**Comment by Suxsem** [comment]
Same issue here

**Comment by Suxsem** [comment]
Not stale

**Comment by misa1515** [comment]
![2024-09-13_19-13-50](https://github.com/user-attachments/assets/0b1479fe-bdb3-417a-9e59-95ad9879bd13)

![2024-09-13_19-15-30](https://github.com/user-attachments/assets/b79457bd-c31a-4fbf-be77-4c6c25f35485)
