### ISSUE TITLE
Question about Monthly

### ISSUE THREAD

**Issue by causefx** [bruxy70/Garbage-Collection#5]
For Monthly you have this listed:

monthly_day_order_number | Yes | Number of the collection_day each month. E.g., if collection_day is "sat", 1 will mean 1st Sunday each month, 2 for 2nd Sunday each month etc. (integer 1-4)Default: 1(relevant for monthly_collection)
-- | -- | --

Is `Sunday` a typo?  Should it be Saturday?  

I'm trying to figure out how to set a collection for the 2nd Tuesday of each month.

Would I set `collection_day` as `tue` and `monthly_day_order_number` as `2` ?

**Comment by bruxy70** [comment]
Yes, this is a typo, thanks for finding it, will fix it in next release.
Yes, you got it right.

**Comment by causefx** [comment]
Sweet! Thanks for this tool!

Want me to close issue or leave open?

**Comment by bruxy70** [comment]
You can leave it, I will close it with the release. Thanks.

**Comment by bruxy70** [comment]
Fixed in the release 1.6
