### ISSUE TITLE
Change Locale of verbose state

### ISSUE THREAD

**Issue by Sebclem** [bruxy70/Garbage-Collection#51]
Hi !

I don't know if it's possible but it will be great if we can change the locale of the date (strftime) when using the verbose state.
In my setup i print the day of week (%A), my HA is in french but the verbose state is print in English.

**Comment by bruxy70** [comment]
Hi, The localization should really be done by the front end, not at the back en (and I have an increasing feeling, that adding the verbose state was a wrong idea from start, as it is now taking completely wrong direction). 
The language as a property of the user. So the way it should be done is, you should take the `next_date` attribute and do the formatting from there. And I think that should render the date in the correct format based on the language set for each user. Would that work?

**Comment by bruxy70** [comment]
..said that, I have tried 
```
{{ as_timestamp(state_attr('sensor.test','next_date')) | timestamp_custom('%A') }}
```
And I am affraid this is not localised either.

**Comment by Sebclem** [comment]
Ok i see and i'm completely agree with you.
I don't know why Jinja don't localise the date.
I have created a template sensor to trick that, i don't know if it's the right solution but it's work so...
This is my declaration if someone want to use it:

``` yml
sensor:
  - platform: template
    sensors:
      ordure_menagere_frindly:
        friendly_name: "Ordure Ménagère"
        value_template: >-
          {% set mo = as_timestamp(state_attr('sensor.ordure_menagere','next_date')) | timestamp_custom('%w')| int %}
          {% set day = ["Dimanche","Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"] %}
          {% set days_left = state_attr('sensor.ordure_menagere', 'days') %}
          Dans {{ days_left }} jour{%if(days_left >1)%}s{%endif%} ({{ (day[mo]) }})
        icon_template: >-
          {% if is_state('sensor.ordure_menagere', '2') %}
            mdi:trash-can
          {% elif is_state('sensor.ordure_menagere', '1') %}
            mdi:delete-circle
          {% else %}
            mdi:delete-restore
          {% endif %}
```

**Comment by bruxy70** [comment]
Right. I guess this gets you what you need. OTOH not ideal either.
Anyhow, I was experimenting, trying to set locale. Got it working on my PC, but for some reason, this did not work on HA. So even if I added this option, it would not help. I will close the issue if you are ok with that.

**Comment by Sebclem** [comment]
Yes, it's ok for me, I think it's more a Jinja/HA problem now.
Thank you !
