### ISSUE TITLE
can't delete integration

### ISSUE THREAD

**Issue by mac-city** [bruxy70/Garbage-Collection#53]
installed through home assistant hacs, configured with config flow i think, and never could get it working correctly, so i uninstalled it and deleted the card from lovelace.

now i am getting this notification from home assistant...
The following components and platforms could not be set up:

garbage_collection
Please check your config.

i tried clicking the trash icon under configuration / integrations / trash collection, but nothing happens.

can anyone help me clean this up?

**Comment by bruxy70** [comment]
Did you configure it from YAML or from the integration UI? If YAML, did you remove the configuration? Did you restart HA after the removal?

If you see the integration under the integrations, it means it wasn't uninstalled. Maybe try to install it from HACS again, restart HA, try to remove the integration and then remove it from HACS?

Also, just wondering why you could not get it to work properly?

**Comment by mac-city** [comment]
> Did you configure it from YAML or from the integration UI?

integration UI


> Also, just wondering why you could not get it to work properly?

always said trash pickup is in 2 days, every day.  also, i kind of realized in my case, having reminders in lovelace is not very useful since i rarely use lovelace.

i was thinking of your solution to re-install, then remove integration, then uninstall from hacs.  i was hoping there was a more direct approach to manually removing the integration.

i will try that and get back to you, thanks for responding.

**Comment by bruxy70** [comment]
Sorry for the trouble. This is managed by HA, the individual integrations do not really deal with the installation/removal. If this does not work, I'd address that with the HA community.

**Comment by mac-city** [comment]
i did as you said and it was cleaned up and no more ha notifications.  i didn't realize you need to remove the integration before uninstalling, but i am learning every day.  thanks!
