### ISSUE TITLE
Translation inversion in sensor.fr.json

### ISSUE THREAD

**Issue by olijouve** [bruxy70/Garbage-Collection#55]
Hi,

Just to let you know, there is an translation inversion in today and tomorrow in sensor.fr.json.

I first thought something had changed in last release but after digging why my UI reports bad status i realised that the issue come sfrom bad labels in sensor.fr.json

It sould be:
```
{
    "state": {
        "Today": "Aujourd'hui",
        "Tomorrow": "Demain"
    }
}
```

**Comment by bruxy70** [comment]
Thanks
