### ISSUE TITLE
Using include and exclude on entities created using config flow

### ISSUE THREAD

**Issue by jmutnick** [bruxy70/Garbage-Collection#58]
I created my senors using the config flow but would like to add include and exclude dates?

Is this possible?  Or would I have to delete them from the config flow and create them in yaml?

**Comment by bruxy70** [comment]
Yes it is possible. Just add the dates to the lines "include dates" and "exclude dates", You do not have to delete the sensor, you can modify it from Integrations GUI.

**Comment by jmutnick** [comment]
I don't see those options when I add a sensor or go to modify it.

Create:
![image](https://user-images.githubusercontent.com/13835801/71486283-97704c00-27e3-11ea-9060-7555a9815ec7.png)

Update: 
![image](https://user-images.githubusercontent.com/13835801/71486317-b1119380-27e3-11ea-8c37-215dbe17037f.png)

**Comment by bruxy70** [comment]
It shows 2 or 3 dialogs, depending on what frequency you choose. So if you choose weekly (like you did), in the second step you can choose the weekday(s), and on the 3rd step other options, including include/exclude dates.

**Comment by jmutnick** [comment]
Excellent!  Thanks for your help.  I really like this sensor.  Going to close the issue now.
