### ISSUE TITLE
(Request) Special case of Bank Holiday week

### ISSUE THREAD

**Issue by ppmt** [bruxy70/Garbage-Collection#6]
Not sure how easy it would be but if I don't ask I won't know :)

Here in the UK in my council shift the normal collection do to the next daym when there is a bank holiday during the week.

In the UK most bank holiday are on a Monday so that makes it a bit easier.
In my case the normal collection day is Friday so on a bank holiday week it will be on Saturday.

I can see it as virtually impossible to code in an easy way but who knows :)

**Comment by bruxy70** [comment]
I guess if I knew the banking holidays, I can add an option to either skip it, move it to next day or move it to the next working day. The trouble is, I'd have to have a database of banking holidays in different countries - which would be overkill, I am not Google.
I  guess I can add an option to "exclude specific days" and "add extra days". But that would mean that you'd have to manually configure the banking holidays each year - and I guess you would not care to do it for the whole year, each year, my thinking is that you probably know that "if the collection is scheduled for today and it is a banking holiday, it will be tomorrow". WDYT?

**Comment by ppmt** [comment]
Yes I can see that it would be complicated. And for all I know my council is the only one in the UK to do it..
It would really help because believe it or not when it is Friday I have long forgotten that Monday was off! So I get them out to find them still full at the end of the day and then I have to do it again the next day!

How about having a list which could be filled with the week numbers of bank holiday week?
Up to you as in any case I will still use your nice little components

**Comment by bruxy70** [comment]
Ok, I will add two parameters: `include_dates` and `exclude_dates`, where you'd be able to add a list of dates to add and to ignore. I think week numbers would be too specific. Would that help?

**Comment by ppmt** [comment]
That would be great!
We don't have that many bank holiday so doing that once a year is no big deal

**Comment by bruxy70** [comment]
Included in the relase 1.6

**Comment by ppmt** [comment]
I can confirm it works. 
I excluded today's date and added tomorrow and the day switched as expected.  One little thing is that HA won't start if you enter a wrong date by mistake (like 31 days in September!) - Don't ask me how I know!

**Comment by bruxy70** [comment]
If you do a config check before the restart, it would tell you that:
ValueError: day is out of range for month
Fatal error while loading config: day is out of range for month
Failed config
  General Errors: 
    - day is out of range for month

**Comment by ppmt** [comment]
FOr some reason the GUI check config hangs for me. It shows me the error only if I use the hassio CLI
No big deal. Thanks a lot for implementing this function so quick!

**Comment by 1DontEx1st** [comment]
Just adding another thanks...over here in the states my local pickup is also delayed by a day when there's a holiday...occasionally things line up across the pond :)

**Comment by bruxy70** [comment]
A friend of mine found the error with the date format. If you use include/exclude dates, please make sure you put them within quotes:
right: '2019-09-30', wrong 2019-09-30.
Without the quotes, home assistant tries to convert the date before it even gets to my code, and it fails. I am trying to address that with the community.

**Comment by ppmt** [comment]
By adding the quote the The Check Config is not hanging anymore

**Comment by garmck** [comment]
Just wondering, instead of manually configuring dates every year, you could possibly use the following - [https://github.com/dr-prodigy/python-holidays](url)

The homeassistant sensor [https://www.home-assistant.io/components/workday/](url) uses this to gather holidays for each region.
I'm not a dev so not sure how much effort would be required to integrate, but thought I'd share as possible enhancement.

**Comment by bruxy70** [comment]
Thanks for the suggestion. I thought about that, but I can't figure out how to configure the alternative collection day. I guess there would be a lot of options, also if you consider all the different frequencies (like following week, following working day (unless it is on weekends, but except holiday), previous working day, first working day next week...and I am afraid that each company would come up with some other rules. Any idea how to do that intelligently? 
Perhaps configuring kind of other collection scheme, that will be used as a bavkup? (But what if this date is on holiday as well).
Any suggestions? 
I have an overall feeling, that the configuration is already bloated with all the options added, I am thinking to structure it a bit.
