### ISSUE TITLE
Multiple Integrations in configurations instead of devices.

### ISSUE THREAD

**Issue by pendlet** [bruxy70/Garbage-Collection#63]
Not sure if this is a bug or an error on my part or just a limitation of integrations. 
I installed using HACS and integrations and got one sensor up and running.  I want to add more to include stuff for different events like birthdays and other reoccurring events. The only way i see to add more is to re add an additional integration which works but i would have thought that i would only need one integration and have multiple devices listed under it.  Is there a way for me to add more sensors? 

**Configuration**
Config Flow (GUI):

**Comment by bruxy70** [comment]
I am afraid this is not a bug, neither error, this is how it works. You add an integration for each sensor. There is no functionality in HA to manually add a "device" to an integration. 
I have been discussing with the team behind HA config flow, there is no other way to do that. There is a concept of multiple "devices" for some integrations that are standard HA integrations (like Z-Wave), but it only works for physical devices. But if you look at ESPHome for example, it works exactly the same. I would also prefer to have one integration and add multiple devices, but not possible. This is not a technical limitation though, you can add the integration as many times you want.
If you do not like having multiple integrations, you can configure it in YAML config.

**Comment by pendlet** [comment]
Thanks for the quick response. I figured it would be something like that.
