### ISSUE TITLE
Date translation

### ISSUE THREAD

**Issue by lseufer** [bruxy70/Garbage-Collection#66]
Hi, 

Only the verbose arguments are getting translated. The dates remain in English and so does the "in XX days". Any chance you add those to the translation files?

Many thanks.

**Comment by bruxy70** [comment]
Unfortunately not. Tried that, HA does not support setting locale for the dates.
You can translate the "in XX days though" using verbose_format. And you can set the date format using date_format. But it won't translate month names.

**Comment by jankete** [comment]
What about a translation for "tomorrow" and "today". Any chance here?

**Comment by bruxy70** [comment]
Sure, that is no problem. Already translated to French, German, Italian and Czech. Feel free to make a pull request with your language [HERE](https://github.com/bruxy70/Garbage-Collection/tree/development/custom_components/garbage_collection/.translations). It is the files `sensor.XX.json` (the files with just language name translate the configuration web page - feel free to translate that as well ;).

**Comment by jankete** [comment]
Hm, if its already translated to german, why is it displayed in english on my frontend with "Garbage Collection Card"? I have installed version 2.12 via HACS and I use the verbose option for the sensor.

**Comment by bruxy70** [comment]
If you have the language in your user profile set to German, the sensor state should be in German (check the actual sensor state in Developer Tools/States - could it be that the language is coming from the Garbage Collection custom card?)

**Comment by jankete** [comment]
My Profile is set do "Deutsch", but the sensor state shows "Tomorrow"

![image](https://user-images.githubusercontent.com/22338766/71967357-8b34b780-3203-11ea-9872-629868e09467.png)

**Comment by bruxy70** [comment]
I see. It looks like it stopped working. I will look at it. Thanks.

**Comment by bruxy70** [comment]
Ok, I guess I forgot how it works. So, here we go. The actual state is in English (it is actually supposed to be in lower case, will fix that in the next release). So that you can use it in your automations and they will run regardless of the user language preference. 
On the front end, the state is translated based on your user preference. So if you put a card on Lovelace, or you click on the i in the circle, it the state should be in German. Please check!

**Comment by jankete** [comment]
Yes, if I just use the "entity" card, it is displayed in German. So it seems to be an issue with "Garbage Collection Card". I'll continue there 😉

**Comment by bruxy70** [comment]
I think it could be related to this https://github.com/amaximus/garbage-collection-card/issues/16

**Comment by jankete** [comment]
Maybe, but there it seems, that this could not be solved. 🤔 And if I use the verbose mode to display the right date format, I have no chance to manually translate 'tomorrow' or 'today', as there is no option in verbose mode for this.

**Comment by WongGendheng** [comment]
When I put my HA profile to German, the garbage collection card shows the German translation for "tomorrow" and "today". However, I do not want to set my HA profile to German. How can I get the German translation while keeping my HA profile Englisch? Already tried to paste content of the "sensor.de.json" into the "sensor.en.json", but somehow the it does not affect the outcome.

**Comment by bruxy70** [comment]
That is weird, that should work. The way it works is, the sensor sets the value to "today/tomorrow". And then the front end translates it based on the user language, using the translation files. So if you fool it and put the German words in the English translation file that should work.
If you use the garbage collection card though, there is another translation under the card, so you might need to change it there as well (suppose the standard translation service does not work in custom cards, so amaximus added his on top).

**Comment by WongGendheng** [comment]
> 
> 
> Yes, if I just use the "entity" card, it is displayed in German. So it seems to be an issue with "Garbage Collection Card". I'll continue there 😉

You can edit the file

>  "\config\www\community\garbage-collection-card\translations\en.json" 

according to your needs. That did it for me.

**Comment by WongGendheng** [comment]
@bruxy70 Yes, it works perfectly. The garbage-collection-card was the problem in my case. I just changed the translation file there as well and everything is perfect now. Thank you for this cool sensor :)
