### ISSUE TITLE
End month can't be before start month

### ISSUE THREAD

**Issue by gregoryduckworth** [bruxy70/Garbage-Collection#7]
There are a few situations in the UK, where things revolve around the tax year, which is Apr-Mar. It would be nice if this plugin supported that, at present if you have:
```
first_month: "apr"
last_month: "mar"
```
it just goes off March as being the last month and doesn't loop round.

**Comment by bruxy70** [comment]
This will take me some time - will have to make it either very cumbersome or rewrite it from scratch. I am going for the rewrite....

**Comment by bruxy70** [comment]
This is added in the release 1.7

**Comment by gregoryduckworth** [comment]
Thanks for this, it is working perfectly!
