### ISSUE TITLE
Start of the "every-n-week" issue?

### ISSUE THREAD

**Issue by war1000** [bruxy70/Garbage-Collection#78]
**Describe the bug**
I defined the following sensors in configuration.yaml but the Yard Waste which has a starting week defined is not working. What am I doing wrong or is this a bug?

**Configuration**
YAML or Config Flow (GUI):
########### GARBAGE SENSORS ##########
garbage_collection:
  sensors:
  - name: Compost 
    frequency: "weekly"
    collection_days: "fri"
    verbose_state: true
  - name: Garbage 
    frequency: "every-n-weeks"
    collection_days: "fri"
    period: 2
    first_week: 2
    verbose_state: true
  - name: Recycling 
    frequency: "every-n-weeks"
    collection_days: "fri"
    period: 2
    first_week: 1
    verbose_state: true
  - name: "Yard Waste"
    frequency: "every-n-weeks"
    collection_days: "fri"
    period: 2
    first_week: 12
    verbose_state: true
```

**Screenshots**

![image](https://user-images.githubusercontent.com/57807544/71785966-e5e7cc80-2fd3-11ea-90df-fb77828a6ad9.png)

**Comment by bruxy70** [comment]
The first_week parameter is not meant to "filter" the start of the collection period. That is the function of first_month and last_month. And you can combine it with exclude_dates if necessary. 
Using it to set the start of the collection period would make no sense as it only applies to this specific frequency.
The way first_week works is, it is kind of offset (maybe this is what I should have called it). If you say every 2 weeks, with the first week of 1 it will be odd weeks, with 2 it will be even weeks. But the first week is not supposed to be greater than the period. I will add a check for that.
Please use the first_month to set the beginning of the collection period. Thanks.

**Comment by war1000** [comment]
@bruxy70 , thank you very much for the quick reply and i will incorporate this in a bit and report back. An thank you very much for the great work!

**Comment by war1000** [comment]
Ok the following worked. I needed the Yard Waste to start on March 20, 2019. The following give me that.

`  - name: "Yard Waste"
    frequency: "every-n-weeks"
    collection_days: "fri"
    period: 2
    first_month: "mar"
    first_week: 14
    last_month: "dec"
    verbose_state: true`

However, your offset idea seems like a better implementation approach since this should be used in conjunction with start and end months.

**Comment by war1000** [comment]
Ok was able to get it to work with the following config. I needed the yard waste to start on Mar 20th. I like your offset idea. Seems more intuitive.

> ########### GARBAGE COLLECTION SENSORS ##########
garbage_collection:
  sensors:
  - name: Compost 
    frequency: "weekly"
    collection_days: "fri"
    verbose_state: true
  - name: Garbage 
    frequency: "every-n-weeks"
    collection_days: "fri"
    period: 2
    first_week: 2
    verbose_state: true
  - name: Recycling 
    frequency: "every-n-weeks"
    collection_days: "fri"
    period: 2
    first_week: 1
    verbose_state: true
  - name: "Yard Waste"
    frequency: "every-n-weeks"
    collection_days: "fri"
    period: 2
    first_month: "mar"
    first_week: 10
    last_month: "dec"
    exclude_dates:
    - '2020-03-06'
    verbose_state: true
