### ISSUE TITLE
Individual dates

### ISSUE THREAD

**Issue by skeptizzle** [bruxy70/Garbage-Collection#95]
**Is your feature request related to a problem? Please describe.**
Nope. 

**Describe the solution you'd like**
I would like to have a feature for inputting individual dates, just like "group". Comma separated would be fine. 
We have a trashcan that gets collected without any interval, see attached image. 

**Describe alternatives you've considered**
Not using it for this trashcan. 

**Additional context**
![Screenshot_20200206-223132](https://user-images.githubusercontent.com/8722790/73980612-e1933400-4930-11ea-8a2e-37262c45e62f.png)

Thanks for an otherwise great integration! 👍

**Comment by bruxy70** [comment]
How about an `annual` frequency on `01/01`, and then add all the other dates with `include_dates`?
This parameter was not meant to be used for annual frequency (that has been designed for things like birthdays), but technically, it should work I think - if you configure it in YAML, the integration page will not show the configuration option. Please try and let me know. I would then allow it officially for annual as well in the next release.

**Comment by WongGendheng** [comment]
Definately works with annual and include_dates. Just set the first date you would have included as the annual date (because it is required) and include the rest with include_dates.

**Comment by skeptizzle** [comment]
@WongGendheng thanks for testing and confirming before I had time!

**Comment by kkmaslowski** [comment]
@bruxy70 Can I add multiple dates from Lovelace gui?

**Comment by bruxy70** [comment]
Of course. Just keep adding the same way as you added the first one.

**Comment by kkmaslowski** [comment]
> Of course. Just keep adding the same way as you added the first one.
Ok. Tried it. I added 4 dates - I see only 2 of them in calendar. Where all dates are saved? I opened core.config_entries and I see only 1 date:

  ```
          {
                "entry_id": "efa56b770e3c11ebb1c9b1f81bb6697e",
                "version": 1,
                "domain": "garbage_collection",
                "title": "\u015amieci komunalne",
                "data": {
                    "unique_id": "7c66c5e8-efe8-4271-8cab-35ace746a41b",
                    "frequency": "annual",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "verbose_format": "dnia {date}, za {days} dni/dzie\u0144",
                    "date_format": "%d-%b-%Y",
                    "date": "10/21"
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_poll",
                "unique_id": null
            }
```

Could you create schedule named 'manual' that will support adding all dates separated by semicolon, for example: _2020-10-07,2020-11-05,2020-12-07_? It would be great.

**Comment by bruxy70** [comment]
Will be made possible by #287
