### ISSUE TITLE
Additional schedule option (e.g. first Thursday each month)

### ISSUE THREAD

**Issue by pichlerralf** [bruxy70/Garbage-Collection#96]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Additional schedule for collection like "first thursday of month".

**Describe alternatives you've considered**
Entering specific dates each year.

**Additional context**
Thanks very much for this great enhancement!

**Comment by bruxy70** [comment]
@pichlerralf, I do not understand. Please give me an example. Thanks.

**Comment by pichlerralf** [comment]
Hello,
example: i have a trash which is schedueled each Thursday on the first week of the month.

Currently i see not option to select from "first/second/third/... week of month", so i need to add it via separate specific dates. Possible, but above option would last for the next years, too.

Thanks very much in advance!
/ Ralf

**Comment by bruxy70** [comment]
That's what the monthly frequency is for.
https://github.com/bruxy70/Garbage-Collection#parameters-for-monthly-collection

There are even two flavors, one for the nth weekday, one for the nth week (e.g. this month, 2th Tuesday would be 11th, but Tuesday 2nd week was  4th)

**Comment by pichlerralf** [comment]
Yes, you're right, thats the way i can go with it.
Thanks very much for your help!

/ Ralf
