### ISSUE TITLE
Garbage collection on specific date list only

### ISSUE THREAD

**Issue by pichlerralf** [bruxy70/Garbage-Collection#97]
Hello,

hope i'm correct to paste this here:
maybe i am missing something, but did not find anything on the docs.

I am having garbage collection on specific dates only, so i would like to set this up.

Config trying like this:

```
  - name: Paper # specific dates
    include_dates:
    - '2020-03-05'
    - '2020-04-02'
    - '2020-05-07'
    - '2020-06-05'
    - '2020-07-02'
Thanks for your help in advance!
```

I would suggest this as a feature request.

/ Ralf

**Comment by bruxy70** [comment]
Hi. Check the issue #95

**Comment by pichlerralf** [comment]
Thanks a lot for the fast response.
Didin't saw this item.
Will try as described.

/ Ralf
