### ISSUE TITLE
Garbage Collection does not appear to be observing leap year

### ISSUE THREAD

**Issue by eldirinice** [bruxy70/Garbage-Collection#98]
**Describe the bug**
Garbage Collection does not appear to be observing leap year, causing collection dates after February 29, 2020 to show as one day later than they actually should be.

**Configuration**
YAML or Config Flow (GUI): Config Flow

```
Frequency: every-n-days
Verbose state: true
First collection month: jan
Last collection month: dec
Collection every n days: 14
First date: 2020-01-06 (a Monday)
No holiday config, extra dates, excluded dates
```
Expected outcome: The component should show my next collection date at Monday, March 2nd, 2020.
Actual outcome: The component shows my next collection date as Tuesday, March 3rd, 2020. 

**Error log/debug information**
```
No error logs
```

**Screenshots**
![image](https://user-images.githubusercontent.com/41747264/75097083-095adc80-556c-11ea-8114-c9995f1eceff.png)

![image](https://user-images.githubusercontent.com/41747264/75097090-24c5e780-556c-11ea-87cd-adfbee4f6d29.png)

![image](https://user-images.githubusercontent.com/41747264/75097101-3ad3a800-556c-11ea-9039-31d302db6904.png)

**Version**
HA: 0.105.5
Integration: 2.15

**Comment by eldirinice** [comment]
I should also add - I attempted to set this component up as every two weeks instead of every 14 days. It exhibited the same behavior with either configuration.

**Comment by bruxy70** [comment]
Weird. I have configured mine exactly the same (starting 2020-01-06, every 14 days)
![image](https://user-images.githubusercontent.com/44951610/75115854-ee1ec880-5662-11ea-979a-35d555aae12a.png)
I do not really work with number of days per month. All I do is, I calculate difference between dates (today-first date), take the remainder of dividing it by the period, and if it is non-zero, calculate the remaining offset and again, use standard python today + timedelta(days=offset)
So I rely on Python to know how many days there is between the dates and that this year is leap year. Could it be that your version of Python handles that differently than mine (I use latest hass.io).

**Comment by eldirinice** [comment]
That is strange... I'm running Home Assistant using the official Docker container, which appears to be using Python 3.7.6. I've worked around it for now by deleting and re-creating the configuration for this one, then setting the start date as March 2nd, but still curious as to this behavior.

Looking at your screenshot, I did notice something. Your next date includes a timezone offset. Mine does not, even though my Home Assistant is using the America/Chicago timezone:
![image](https://user-images.githubusercontent.com/41747264/75116380-64a0d380-562d-11ea-88b8-ee93401bbe59.png)

![image](https://user-images.githubusercontent.com/41747264/75116384-6e2a3b80-562d-11ea-8683-2a7ea519b0d4.png)

I don't know whether that's playing a role, but I suppose it might be possible. Why would your next date show a timezone offset while mine does not?

**Comment by bruxy70** [comment]
No idea. I added the timezones in 2.0 I think. It was causing issues in Australia. It works since then. When was testing that, I was trying to change my timezone to Sydney using the location. But that did not work, I did back and forth with people over there to test each change, quite a nightmare. My tz is set right, but do not quite understand how to change it. It could be it takes it from the host OS?

**Comment by eldirinice** [comment]
Might be onto something there. I connected to the container running Home Assistant, and it shows the time as UTC. My timezone is set to America/Chicago through the Home Assistant configuration UI.

**Comment by bruxy70** [comment]
I think mine is set to UTC too.
```
➜  /config cat /etc/timezone
Etc/UTC
```

**Comment by bruxy70** [comment]
But in Home Assistant it is set to UTC+1
![image](https://user-images.githubusercontent.com/44951610/75116868-d64c4200-566c-11ea-833f-bec7715a26df.png)

**Comment by bruxy70** [comment]
And it shows it on System Health too
![image](https://user-images.githubusercontent.com/44951610/75116881-f845c480-566c-11ea-8a72-ddcf811334e8.png)

**Comment by eldirinice** [comment]
I really don't have an explanation :/ 

Times seem to convert properly elsewhere in Home Assistant. If I look at States in developer tools, pretty much every time shows as UTC, but it's converted properly in the UI to reflect my local timezone. 

I updated my Home Assistant compose file for Docker to include /etc/timezone (before, I was only passing /etc/localtime). It looks like /etc/timezone is set to UTC. However, that didn't seem to make a difference.

**Comment by bruxy70** [comment]
Ok, I have tried to change the method of calculating the time difference from standard `datetime` to `dateutil`. Since I do not know what is causing it, I have no idea if this will change anything. I have found some posts that it could. Would you like to try? I made a 2.16-beta release with that (you have to show beta under ⁞ . It works for me (makes no difference - it worked before as well). Hopefully it will not break the Aussies.

**Comment by eldirinice** [comment]
👏 That seems to have done it! I created a test trash entry, set it to repeat every 14 days, and set the start date as 2020-01-06. It correctly shows the next pickup day as March 2nd, 2020. I also updated my existing recycling entry and put the start date as 2020-01-06, and it is also showing the correct pickup date of March 2nd.
